### ISSUE TITLE
the ability to select the type of charts

### ISSUE THREAD

**Issue by arturmon** [mycontroller-org/mycontroller#108]
perhaps it has already been implemented, but I just found a linear chart.
it is possible to select the type of schedule?
such as:
http://jtblin.github.io/angular-chart.js/
http://www.fusioncharts.com/angularjs-charts
http://www.zingchart.com/blog/2015/11/09/angularjs-chart-examples/

**Comment by jkandasa** [comment]
@arturmon we are using http://krispo.github.io/angular-nvd3/#/ in current implementation. I feel this chart is good to go. Do you feel any drawback on the current implementation?

**Comment by jkandasa** [comment]
@arturmon you can `line/bar` chart select option?

**Comment by arturmon** [comment]
not very nice is obtained by using the toggle switch on

**Comment by arturmon** [comment]
maybe this one will be better on the charts where only two values. multiBarChart

**Comment by arturmon** [comment]
http://krispo.github.io/angular-nvd3/#/dashboard
wow that's a good board control resizable.

**Comment by jkandasa** [comment]
available in 0.0.3-alpha1
