### ISSUE TITLE
[Enhancement] Modify Sensors API Json response

### ISSUE THREAD

**Issue by S0rc3r3r** [mycontroller-org/mycontroller#124]
Status field from Sensors api response should be a map between variableType and variableType.value:
..........
	"status": [{
			"value": "23.56 °C",
			"variableType": "V_TEMP"
		}, {
			"value": "22",
			"variableType": "V_HVAC_SETPOINT_COOL"
		}, {
			"value": "20",
			"variableType": "V_HVAC_SETPOINT_HEAT"
		}

	],
	"enableSendPayloadRaw": null,
..............

Also +1 on https://github.com/mycontroller-org/mycontroller/issues/24

**Comment by S0rc3r3r** [comment]
If you have not started I can do it myself...the backend stuff. 
I assume that UI changes are also needed and maybe you can have a look over that implementation.

~Regards

**Comment by jkandasa** [comment]
@S0rc3r3r I didn't start yet. What we have to add on this is, 
- we have to create new java class (with JSON support)
- variables on this new class `value, unit, variableType`
- If local unit is not available supply with global units (if global unit available)

**Comment by jkandasa** [comment]
@S0rc3r3r I'm working on this, i will push my changes on tomorrow

**Comment by jkandasa** [comment]
implemented this one,
example 1:
```
"status":[{"variableType":"V_STATUS","value":"1","unit":"","friendlyValue":"ON ","timestamp":1449530181486},{"variableType":"V_WATT","value":"34","unit":"W","friendlyValue":"34 W","timestamp":1449530189909}]
```
example 2:
```
"status":[{"variableType":"V_TEMP","value":null,"unit":"°C","friendlyValue":"- °C","timestamp":null},{"variableType":"V_HVAC_FLOW_STATE","value":null,"unit":"","friendlyValue":null,"timestamp":null},{"variableType":"V_HVAC_SETPOINT_HEAT","value":null,"unit":"","friendlyValue":null,"timestamp":null}]
```

![action_board_124](https://cloud.githubusercontent.com/assets/1004403/11651798/82d47630-9db9-11e5-8e9e-e173a1fde2d9.png)
