### ISSUE TITLE
[New-Feature] Add 3rd party module support.

### ISSUE THREAD

**Issue by S0rc3r3r** [mycontroller-org/mycontroller#125]
We should allow 3rd party applications to integrate with Mycontroller as modules.

**Comment by S0rc3r3r** [comment]
Here is a tutorial of the whole idea.
http://www.javaworld.com/article/2077837/java-se/hello--osgi--part-1--bundles-for-beginners.html

Unfortunately i don't have so much experience in programming . If you could have a look and discuss afterwords would be nice.

**Comment by jkandasa** [comment]
@S0rc3r3r looks interesting...

**Comment by jkandasa** [comment]
@S0rc3r3r we are not going to support plugin type, as it leads huge memory consumption. But we can add new plugins with core module
