### ISSUE TITLE
Feature Request : Option for autorefresh page

### ISSUE THREAD

**Issue by TheAbhor** [mycontroller-org/mycontroller#127]
Hi Jeeva, great project,

Is it possible to make a setting in the controller settings for an option 'always autorefresh' or something like that ?
every time If goto 'Action board' the standard now is -- never refresh --

GreetZz

**Comment by jkandasa** [comment]
@TheAbhor I will save last change by user and use it.

**Comment by TheAbhor** [comment]
Your the best ;-)
Another little thing, is there a notice for an update in MyController ?

**Comment by jkandasa** [comment]
@TheAbhor you mean next release?

**Comment by TheAbhor** [comment]
yes

**Comment by jkandasa** [comment]
@TheAbhor currently I'm working on to support,

* Multiple gateways
* New GUI (https://www.patternfly.org)
* And bug fixes

roughly it will take around more than two weeks

**Comment by TheAbhor** [comment]
@jkandasa 
Looks great, new looking for mycontroller ? Or what ?
Is it possible for me somewhere in your program to delay a light time when triggered by a motion sensor ?

**Comment by jkandasa** [comment]
@TheAbhor could you come to https://gitter.im/mycontroller-org/mycontroller?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by jkandasa** [comment]
@TheAbhor  we will track motion sensor delay issue with https://github.com/mycontroller-org/mycontroller/issues/128
