### ISSUE TITLE
Dashboard and triggers 

### ISSUE THREAD

**Issue by chrigui** [mycontroller-org/mycontroller#132]
hi, this is some great work you are doing!
i have 2 questions please
1- do you have any road map ?
the reason i ask is just to estimate when you will have a dashboard ?

2- are you please to create some sort of triggers ?
eg: if temp1 is bellow x then turn on fan1.

thanks.

**Comment by jkandasa** [comment]
@chrigui 

>1- do you have any road map ?
the reason i ask is just to estimate when you will have a dashboard ?

Currently I'm working on next version with huge changes, this will give dashboard also. may be released by this month end.

>2- are you please to create some sort of triggers ?

This feature already available with the name of 'Alarms'

**Comment by chrigui** [comment]
Thank you for your reply!!

**Comment by jkandasa** [comment]
https://github.com/mycontroller-org/mycontroller/issues/82

dashboard available
