### ISSUE TITLE
sending several notifications when the alarm goes off.

### ISSUE THREAD

**Issue by arturmon** [mycontroller-org/mycontroller#138]
![1](https://cloud.githubusercontent.com/assets/7686999/12931230/c2028cce-cf8d-11e5-9ff9-6ed002c8cec4.jpg)

**Comment by jkandasa** [comment]
https://github.com/mycontroller-org/mycontroller/commit/ee3d40108b2c855d19ff1ff80162e9fc92c754ef

implemented multiple notification for alarm definitions
