### ISSUE TITLE
add custom action button

### ISSUE THREAD

**Issue by gbrd** [mycontroller-org/mycontroller#140]
Very nice work ! Finally a modern controller for mysensors !

We have "send Raw Message" and what we could call "automatically configured buttons" functions,
it would be nice to be able to add custom button on each node/sensor.

I have several custom/complex mysensors nodes in my network, and I would need to be able to send specific messages.

**Comment by jkandasa** [comment]
@gbrd yes, we had send raw message option and was not implemented yet with this 0.0.3 release. will be added soon.

Also custom button will be added https://github.com/mycontroller-org/mycontroller/issues/47

**Comment by gbrd** [comment]
My sensors implements "REQ" msgType (=2).  I use it to manualy ask an update. 
Would be great to be able to choose msgType too when sending message on a custom button or in a "notification" / "send payload"

**Comment by jkandasa** [comment]
>My sensors implements "REQ" msgType (=2). I use it to manualy ask an update. 
Would be great to be able to choose msgType too when sending message on a custom button or in a "notification" / "send payload"

@gbrd Added new operation type `Request payload`. We can include `Operations` in `Timer` and/or in `Rules`
Version: `0.0.3-Alpha2`

##### Steps:
* Create `Operation`, type `Request payload`
* Configure created operation in `Timer` and/or in `Rules`

##### To create `Request payload` operation:
Navigate to `Resources -> Operations`. Update details as shown in the image.
![image](https://cloud.githubusercontent.com/assets/1004403/14555117/4c2c37b6-030e-11e6-8b62-15c90b56b6af.png)

##### To configure `Operation` in timer:
Navigate to `Resources -> Timers`
Following image show how to configure `Operation` in `Timer`. In this example I have selected `Simple timer` with the option, run every 1 minute(60 seconds) and never stop (`-1` infinite job).
![image](https://cloud.githubusercontent.com/assets/1004403/14555180/b9f20e24-030e-11e6-868d-a547fdcefcfe.png)

**Comment by jkandasa** [comment]
##### Send raw message
With `Send raw message` feature we can send any type of message to node/sensors.
Navigate to `Action board -> Send raw message`.
* Select a gateway
* Enter `Node EUI` and `Sensor id`
* Select `Type` and `Sub type`
* Select `Acknowledge` type
* `Payload` is optional
![image](https://cloud.githubusercontent.com/assets/1004403/14580573/c6e22df4-03ee-11e6-95ce-f2727b6cd514.png)
