### ISSUE TITLE
Add automatic geolocation.

### ISSUE THREAD

**Issue by arturmon** [mycontroller-org/mycontroller#143]
automatically determine your location through your browser. it is more convenient than manually entering coordinates.
Here is an example: http://html5demos.com/geo
![1](https://cloud.githubusercontent.com/assets/7686999/13340285/3fc99e86-dc40-11e5-9975-e1c0131eead9.jpg)

**Comment by anarro** [comment]
Hi,
Yes,I think thats a good idea.

**Comment by anarro** [comment]
Hi, where I can download this version?

**Comment by jkandasa** [comment]
@anarro You can compile the source code locally. However I have uploaded SNAPSHOT version here https://oss.sonatype.org/content/repositories/snapshots/org/mycontroller/standalone/mycontroller-dist/0.0.3.Alpha2-SNAPSHOT/ You can download latest version from here. `.zip` and `.tar.gz` versions are available.
