### ISSUE TITLE
New dashboard item - Static image with auto-reload from disk

### ISSUE THREAD

**Issue by manusovich** [mycontroller-org/mycontroller#145]
That will be nice to have one more dashboard item type - static image from disk + refresh period for that on dashboard. It can be worth when we have another systems in our home network and they are producing such images. For example for me it is traffic in the city or image from webcam

**Comment by jkandasa** [comment]
New widget will be available in the name of `Display image file`. Set image location under `Settings-->System-->MyController-->Widget image files disk location`

This widget supports local disk image as well as with remote image with http url.

**Comment by manusovich** [comment]
I see that there is 1MB limit for image size. Is it possible to change this
limit? 1MB for image is very small size. All my images for example between
2MB and 4.

Alex

**Comment by jkandasa** [comment]
@manusovich if we put more than 1 MB limit leads out of memory exception as are using only 40 MB for JVM. we should increase JVM heap space in this case. I will find a way to do that.

**Comment by jkandasa** [comment]
@manusovich Increased file size limit to 7 MB!

Changes: 
- supports up to 7 MB file size.
- will not list files if the size is more than 7 MB
- list files include sub directory also
- Returns only first 500 files, if we have more than that we should change base directory to narrow down file counts.

in upcoming release we may need to increase JVM heap size. Currently it is 40 MB.

**Comment by jkandasa** [comment]
@manusovich When we use `disk` option, without authentication no one take your image outside world as it is passing throw validations and returns as REST object. limitations are required when it is passing throw JVM.

But with `url` option you can serve without limitation of the size. 
If you put your images under `mycontroller/www/` can access via url.

Example: create a directory under `mycontroller/www//myimages`. and place image files (`file1.jpg`). Now I can access `file1.jpg` from `https://mycontroller-ip:8443/myimages/file1.jpg` select `url` option in dashboard widget and give this url. It should work.
**IMPORTANT**: any one can access your image without authentication in this method.
