### ISSUE TITLE
Purging RESOURCES_LOGS_DETAIL

### ISSUE THREAD

**Issue by WimVerhaert** [mycontroller-org/mycontroller#146]
After I purge the RESOURCES_LOGS_DETAIL it does not seem to fill it with new information.
See http://demo.mycontroller.org/#/status/resourceslogs//

**Comment by jkandasa** [comment]
this should not be a bug, it's deleted all the resources log. Will fill with new information once it receives.

**Comment by WimVerhaert** [comment]
mmm, mine does not seem to do it,... but my sensor data is being updated ?
Anything on filessystem I can check?

**Comment by jkandasa** [comment]
if you do some actions like turn on Light. you can see the log

**Comment by jkandasa** [comment]
yes, sensors data will not be removed. this will just purge communications logs

**Comment by WimVerhaert** [comment]
My node is a sensor (temp/hum), so only incoming data for mycontroller,... but the resource log does not show this anymore, nor does it show me eg a requestTime.

**Comment by jkandasa** [comment]
Once every 30 minute MyController will send alive request. you can see that

**Comment by WimVerhaert** [comment]
Rebooting my sensor should do the trick as well, not? 
I do not seem to get my resource log back :(
Can the alive requests also be increased in frequency?

**Comment by jkandasa** [comment]
create some dummy node with sensors like switch and do action on that

**Comment by WimVerhaert** [comment]
negative :(
created node -dimmer -> actionboard -> toggle on/off => nothing in resource log

**Comment by jkandasa** [comment]
do you see any error log in mycontroller.log? `Status-->MyController server log` or in server `mycontroller/logs/mycontroller.log`

**Comment by WimVerhaert** [comment]
got it,... problem was 'user error', I already turned the setting->system->Resources logs levelTrace to ERROR, ... now at 'trace' it is filling up again.
Sorry for the trouble :)

**Comment by jkandasa** [comment]
no problem :)
