### ISSUE TITLE
Sensors naming rules in case if name is not defined 

### ISSUE THREAD

**Issue by manusovich** [mycontroller-org/mycontroller#147]
1. When controller discover sensor for the first time and we are adding that to the graph, graph has null for sensor name. Item in agenda is looking like null-Temperature. Also you can see this null in sensor picker. 

2. After we edit sensor information and leave sensor name field empty we don't have null in sensor name anymore and it is looking like "-Temperature". That is another bug - when sensor doesn't have name, we should show just sensor type. So in agenda it should be something like "Temperature" if we don't have name and "Name-Temperature" if we have it.

**Comment by jkandasa** [comment]
@manusovich Can you add screenshot?

**Comment by manusovich** [comment]
Sure. Attached
<img width="192" alt="screen shot 2016-03-03 at 8 25 21 pm" src="https://cloud.githubusercontent.com/assets/2063812/13721172/4dfce194-e7e3-11e5-843f-118389a28b24.png">
<img width="572" alt="screen shot 2016-03-03 at 8 25 12 pm" src="https://cloud.githubusercontent.com/assets/2063812/13721173/4e0c7104-e7e3-11e5-8da2-a79662bc0179.png">
<img width="491" alt="screen shot 2016-03-11 at 11 45 57 pm" src="https://cloud.githubusercontent.com/assets/2063812/13721176/72065494-e7e3-11e5-83e8-38ac9b71a0be.png">
