### ISSUE TITLE
Post processing a raw datavalue

### ISSUE THREAD

**Issue by WimVerhaert** [mycontroller-org/mycontroller#149]
It would be interesting to do some post processing on an incoming value, eg raw data of a air quality= 60%, which I translate into air = good (green).

**Comment by WimVerhaert** [comment]
maybe even use the incoming value to change a user-defined variable.

**Comment by WimVerhaert** [comment]
Simple example is:

- My sensor sends value 1000kWh
I want to show to the enduser = 1000kWh * (price kWh)  =1000 * 0.2 =200 $
 
-My sensor sends value 1000kWh
I want to add a base value to it since my meter already has 9000kWh on it before I added my sensor

**Comment by WimVerhaert** [comment]
Maybe it could be useful to allow the user to create custom variables in the Variables Mapper table, Variables that can be used elsewhere (as a fake sensor?).

**Comment by jkandasa** [comment]
To address this, have to implement [JSR223](https://www.jcp.org/en/jsr/detail?id=223) by default it comes with `javascript` support. We can also add `python`, `ruby`, `groovy` support easily

**Comment by WimVerhaert** [comment]
without just copying what openhab has,.... they have a similar implementation (i even saw the jsr223 in their core directory)
cfr:https://github.com/openhab/openhab/wiki/Scripts
