### ISSUE TITLE
Different widget

### ISSUE THREAD

**Issue by WimVerhaert** [mycontroller-org/mycontroller#150]
As an end-user 
I would like to have a widget on my dashboard that displays the data of a sensor as :

- a gauge/dial (eg http://www.visokio.com/files/Resources/OUGuide/381_ViewsRef/15-DialView492/492_DialViewSpeedometer_272x264.png) with a range indication

**Comment by jkandasa** [comment]
@WimVerhaert for now I do not see any widget like this in `NVD3` and in `c3`. We may use `bullet-graph` similar. However using `Custom widget` we may achieve this.

**Comment by jkandasa** [comment]
@WimVerhaert I am closing this issue, as we can use this with "Custom widget" in dashboard.
