### ISSUE TITLE
Rules

### ISSUE THREAD

**Issue by WimVerhaert** [mycontroller-org/mycontroller#151]
Is it possible to create some 'rules' in MyController (cfr what openhab has).

Eg: when I get a sensor indicating a door opening I want to turn on a light on an other sensor.

This would be different than forwarding a payload.

**Comment by WimVerhaert** [comment]
Just noticed this to be in the Alarms,...
Maybe rename Alarms into Rules :)

**Comment by jkandasa** [comment]
Yes, It's good to rename `alarm` to `Rules` and `Notifications` to `Actions`

**Comment by Thar0l** [comment]
Another solution is to add scripts support. It allow not only send constant payload but modify original. (e.g. calculate average temp from some sensors and turn on/off heater. (Current facility with alarm/notifications doesn`t allow such actions))

**Comment by WimVerhaert** [comment]
These new  'Rules' would probably go hand in hand with the enhancement in https://github.com/mycontroller-org/mycontroller/issues/149

**Comment by arturmon** [comment]
It may be necessary to add Node-RED?

**Comment by jkandasa** [comment]
Node-RED not supported. But scripting will be supported for conditions and operations. Add changes in development branch

**Comment by jkandasa** [comment]
@Thar0l added script support. and renamed as new suggestions
