### ISSUE TITLE
refresh button on 'resources logs'

### ISSUE THREAD

**Issue by WimVerhaert** [mycontroller-org/mycontroller#152]
As an admin user I want to monitor incoming events/sensor data in the resources logs without having to hit browser refresh all the time.

Is it possible to do an automatic refresh of the this log?

**Comment by jkandasa** [comment]
It is a good request already we have global page refresh attribute, I will implement to this page.

**Comment by jkandasa** [comment]
Added refresh button and included auto refresh. Auto refresh will happen based on global page refresh time. Default is 30 seconds, we can change this under settings-->system
