### ISSUE TITLE
MySQL database

### ISSUE THREAD

**Issue by avoloshyn79** [mycontroller-org/mycontroller#154]
Please, add the ability to use MySQL

**Comment by arturmon** [comment]
then it is better HSQLDB

**Comment by jkandasa** [comment]
@avoloshyn79 @arturmon to implement MySql, HSQLDB, other databases, we have to check `ormlite` support and `flywaydb` support. also other factors.

May I know what leads to move out from `h2` db?

**Comment by gbrd** [comment]
If you change database,  why not something more modern and fun like mongodb or another nosql database ;)  ?  (An online db as a service would be fun too but it would make us less independent)

**Comment by jkandasa** [comment]
@gbrd Right now our design with RDBMS. We may switch easily between RDBMS vendors. But to switch to NoSql databases more changes needed.

**Comment by WimVerhaert** [comment]
Is it possible to get easy access to the H2 database, which app do you use?

**Comment by jkandasa** [comment]
@WimVerhaert [download](http://www.h2database.com/html/main.html) from h2 website. you can use it as web console or command line console.

in MyController.org h2 db is running in embedded mode. Which means while MyController.org is running you cannot access database. You can see all the data when you extract your backup file.

**Comment by jkandasa** [comment]
@avoloshyn79 MySQL database support added, kindly check and report if you see any errors. Thank you! You can download SNAPSHOT version [from here](https://drive.google.com/drive/u/0/folders/0BzuumrtRA7p6dXZ5THdURUc1blU)

**Comment by jkandasa** [comment]
Currently MyController supports for `MySQL`, `MariaDB`, `PostgreSQL`, `H2DB`, and `H2DB Embedded`. 

By default MyController comes with `H2DB Embedded` database

**Comment by jkandasa** [comment]
I am closing this issue, as this feature has implemented.
