### ISSUE TITLE
Issue with restore a Backup

### ISSUE THREAD

**Issue by anarro** [mycontroller-org/mycontroller#155]
Hi jkandasa, 
I think that we have an issue with the Backup/Restore.., Today I tried update your app.

First I checked that we had some Backup files, then I stopped the services (./stop.sh script), that´s ok, and I erased and copied a new files and I started the service (./start.sh script), clicked in "Settings -> Backup" and clicked in "Action->Restore" and I accepted the message dialog and the Apps shows an error "NO RESPONSE, Check you network connection[s]...)", and the web services was down, I started your Apps and I show thats my settings and configs it´s restored..

Sorry for my language!!
Antoni.

**Comment by arturmon** [comment]
run the recovery from the menu. after the upgrade you need to manually start (start.sh). Let it be for now.

**Comment by jkandasa** [comment]
@anarro It is not an issue. After restore all services will be stopped. Hence you are seeing `NO RESPONSE` error. we have to start the service manually.

On the popup dialog we have mentioned server will be stopped after restore,

![mc-backup](https://cloud.githubusercontent.com/assets/1004403/13554055/c6827a9e-e3c3-11e5-81db-b2b496c99e6a.png)

**Comment by anarro** [comment]
Sorry !! Oo, I had not read it.
Thank you.

**Comment by arturmon** [comment]
my this is just not enough. start the service after the restore. and as I understand it is more dependent on the operating system it is running mycontroller/
