### ISSUE TITLE
Purge sensor data

### ISSUE THREAD

**Issue by WimVerhaert** [mycontroller-org/mycontroller#156]
As a user I want to remove some old (invalid) data that is shown in my graphs.
Is it possible to purge sensor data, maybe select some criteria like 'before date x'?

**Comment by jkandasa** [comment]
@WimVerhaert right now we do not have any option to purge. It is good feature request.

**Comment by cimba007** [comment]
I decided that I no longer need the V_ARMED variable on my sensor node. Hitting purge will clearn all data but the button/graph will not disappear. **Please remove all data if hitting purge without a timelimit.**
