### ISSUE TITLE
Get data from custom url

### ISSUE THREAD

**Issue by Werwolfx** [mycontroller-org/mycontroller#158]
Nice work, thank you.

may be you add function to get data from custom url, custom site?
for example get data from weather site, parse value temperature and store it to database and show it in dashboard.

sorry for my english.

**Comment by jkandasa** [comment]
@Werwolfx we are not going to store any data locally. but we can store template and configuration locally. We can achieve this with `Custom widget` in dashboard.

To add weather site see an example: http://blog.forecast.io/forecast-embeds/

**Comment by Werwolfx** [comment]
Thank you , great job .
Where can I download 0.0.3.Alpha2 for test ?

**Comment by jkandasa** [comment]
@Werwolfx You can build `SNAPSHOT` builds locally. For now I have uploaded here https://oss.sonatype.org/content/repositories/snapshots/org/mycontroller/standalone/mycontroller-dist/0.0.3.Alpha2-SNAPSHOT/mycontroller-dist-0.0.3.Alpha2-20160510.085507-7-bundle.zip

**Comment by Werwolfx** [comment]
Please tell me how i add info to custom widget?
I create Templates in content 
<html>
<iframe id="forecast_embed" type="text/html" frameborder="0" height="245" width="100%" src="http://forecast.io/embed/#lat=42.3583&lon=-71.0603&name=Downtown Boston&color=#00aaff&font=Georgia&units=uk"> </iframe>

</html>

Select in custom widget this Template, but not see info =(
What i not correct do?
