### ISSUE TITLE
Bug: Node state is down all the times 

### ISSUE THREAD

**Issue by manusovich** [mycontroller-org/mycontroller#159]
Hi there, please check MySensorsMessageEngine.executeMessage in case when it is receiving C_SET message, it doesn't look like it is setting node state back to UP if it was DOWN before. recordSetTypeData method from this class is not doing that. Some of messages (with type internal) like I_BATTERY_LEVEL are setting node state = UP by calling updateNode(node) but doesn't look like we are doing that in C_SET.

**Comment by jkandasa** [comment]
@manusovich nice catch!

**Comment by jkandasa** [comment]
https://github.com/mycontroller-org/mycontroller/commit/4edcf6a3c883340561e27b29d2829abae796251a fixes this issue. Kindly reopen this issue if you face.
