### ISSUE TITLE
Enhancement: Dashboards routing

### ISSUE THREAD

**Issue by manusovich** [mycontroller-org/mycontroller#160]
Please consider to add angular routing for dashboards. Right now all of them have url /dashboard and in case if some of us have auto page refresh in browser it is always loading first dashboard after refresh even if another has been opened. That will be nice to have dashboard id in url also.

**Comment by jkandasa** [comment]
@manusovich Thanks for reporting this. we does not have url with dashboard id. however dashboard was designed to store last selected dashboard in local cookies and displays selected one, until we logout. But it is not working. we have to fix this.
https://github.com/mycontroller-org/mycontroller/blob/0.0.3-alpha1/src/main/package/www/controllers/dashboard.js#L27
