### ISSUE TITLE
Enhancement: Dashboards header

### ISSUE THREAD

**Issue by manusovich** [mycontroller-org/mycontroller#162]
Please consider remove header on dashboards page "Dashboards". We already have Dashboards in main menu and there is no need to have that on the page as well:
<img width="235" alt="screen shot 2016-03-17 at 8 22 16 pm" src="https://cloud.githubusercontent.com/assets/2063812/13865876/2af99ff8-ec7e-11e5-8ea9-ce1b8c650de7.png">

For example on resources page we don't have "Resources" header:
<img width="310" alt="screen shot 2016-03-17 at 8 22 25 pm" src="https://cloud.githubusercontent.com/assets/2063812/13865882/3f5c9496-ec7e-11e5-96c2-baada8d8c641.png">

By removing this unnecessary header "Dashboards" we are saving space for case when we are using smart home panels and we can fit more useful data. For example mine terminal:
![img_0393](https://cloud.githubusercontent.com/assets/2063812/13865911/7f360214-ec7e-11e5-8e81-2fc358f05119.JPG)

**Comment by jkandasa** [comment]
@manusovich we are using patternfly.org for GUI framework. If we remove submenu, it looks dark black in that location. So I kept `Dashboards` as sub menu. I will try to figure out the way to remove this duplicate menu.

**Comment by jkandasa** [comment]
For now we are not going to remove this field. However by hide main menu we can save some space. In future if we get any solution we can fix this layout. https://github.com/mycontroller-org/mycontroller/commit/676c29386d6ba0ea921e4aafd175d21d72320461

**Comment by manusovich** [comment]
@jkandasa Thank you. That is cool feature.

**Comment by manusovich** [comment]
@jkandasa there is bug with this. when user clicks hide menu - everything is fine (main content takes whole space). But if you will reload page after that, main content is not taken space where main menu was. See picture:

<img width="1181" alt="screen shot 2016-04-06 at 8 29 29 pm" src="https://cloud.githubusercontent.com/assets/2063812/14337755/4f8a2e92-fc36-11e5-8724-e2919e110994.png">

**Comment by jkandasa** [comment]
@manusovich can you clear your browser cache and try again?

**Comment by manusovich** [comment]
Same issue
