### ISSUE TITLE
Enhancement: Optional main header 

### ISSUE THREAD

**Issue by manusovich** [mycontroller-org/mycontroller#163]
Please consider to have option in settings which is hiding main header (where is logo, language, help & user buttons). Profile is always available from settings. 
That will make mycontroller.org usage on terminals much more user friendly. Now it is taking vertical space + if user clicking on logo it is loading external site in terminal frame. In case if terminal doesn't have buttons it become problem how to return back. 
That is how it is looking on terminal now: 
![img_0393](https://cloud.githubusercontent.com/assets/2063812/13866247/66b3e118-ec81-11e5-9819-2718ea8d4782.JPG)

**Comment by jkandasa** [comment]
@manusovich how about implementing vertical navigation.

https://rawgit.com/patternfly/patternfly/master/tests/vertical-navigation.html

**Comment by manusovich** [comment]
@jkandasa It is still takes space. IMHO navigation right now is great. This proposal only about header above navigation with logo, support & user links.

**Comment by jkandasa** [comment]
@manusovich added option to show hide main menu, this will create more space on dashboard.
https://github.com/mycontroller-org/mycontroller/commit/676c29386d6ba0ea921e4aafd175d21d72320461
