### ISSUE TITLE
Modular core-functionality? 

### ISSUE THREAD

**Issue by mannkind** [mycontroller-org/mycontroller#169]
I love MyController. I find it extremely useful for managing my MySensors nodes - assigning IDs, remote reboots, and OTA firmware updates.

However, since I already have a large/complex automation setup that MyController isn't able to replicate (lots of non-MySensors stuff) there is a lot of unused MyController core-functionality:  alarms, groups, rooms, data collection, charts, etc.

Are there any thoughts/plans about making the system more modular so that core-functionality can be enabled/disabled as needed? 

Thanks again for all your work!

**Comment by jkandasa** [comment]
@mannkind thank you! recently I have changed to support multiple providers. base ready to support for multiple vendors. However for now it supports only for `MySensors`.
https://github.com/mycontroller-org/mycontroller/tree/development/modules/core/src/main/java/org/mycontroller/standalone/provider/

Can you update your requirement?

**Comment by mannkind** [comment]
It's neat that you're going to support different providers. I guess I was thinking that it'd be nice to be able to disable the functionality that I cannot utilize due to an pre-existing IoT solution. Ah well, it was just a thought! :)
