### ISSUE TITLE
Grouping Graphical reports

### ISSUE THREAD

**Issue by jkandasa** [mycontroller-org/mycontroller#17]
In current design graphical report shows only single sensor, which is ok but many times in field user want to compare with some other sensor result, example: on three phase voltage show all the three voltage differently. If we club all the sensors value in to single graph, user can understand easily whats going on.

**Comment by arturmon** [comment]
evidence of multiple sensors seems to me better to use on dashboards.

**Comment by jkandasa** [comment]
https://github.com/mycontroller-org/mycontroller/commit/b7e521ffb19f2c8df9068342d6373802cf184109
