### ISSUE TITLE
Add a choice of the number of the displayed information in the tables.

### ISSUE THREAD

**Issue by arturmon** [mycontroller-org/mycontroller#170]
![1](https://cloud.githubusercontent.com/assets/7686999/14229351/789ea1ea-f93a-11e5-83e9-48858cd369ca.jpg)
Add this possibility wherever there is only a table ( gateways, nodes, sensors, etc )

**Comment by jkandasa** [comment]
@arturmon I will add in global settings to change number of rows to display in tables.
