### ISSUE TITLE
Get nonce response

### ISSUE THREAD

**Issue by Dietmar-Franken** [mycontroller-org/mycontroller#172]
@jkandasa 
I need a explanation to translate this please

**Comment by jkandasa** [comment]
@Dietmar-Franken please refer https://github.com/mycontroller-org/mycontroller/blob/development/modules/core/src/main/java/org/mycontroller/standalone/message/McMessageUtils.java#L114

**Comment by Dietmar-Franken** [comment]
you don´t understood me,because i haven´t found anything at google nor any translator tool can help me.please give me a clue

**Comment by jkandasa** [comment]
@Dietmar-Franken it is a signing support of MySensors.rog. you can see more details here http://forum.mysensors.org/topic/1021/security-introducing-signing-support-to-mysensors

This request/response usually answered by Gateway. Never reach controller(controller do not know how to answer for this message). If it reaches controller we need to log it in our resources logs table.

**Comment by Dietmar-Franken** [comment]
Thank you
