### ISSUE TITLE
Node Alive Check

### ISSUE THREAD

**Issue by WimVerhaert** [mycontroller-org/mycontroller#174]
My 'Noded alive check interval' is set to 20 minutes.
In the log I do see the messages being sent, 
However my nodes are sleeping quite a lot but also sending data frequently.
Why are the nodes still showing as 'down'?

**Comment by jkandasa** [comment]
@WimVerhaert This issue was fixed recently in https://github.com/mycontroller-org/mycontroller/issues/159
