### ISSUE TITLE
Unused class

### ISSUE THREAD

**Issue by pgh70** [mycontroller-org/mycontroller#177]
The class: org.mycontroller.standalone.uidtag.UidTagMapper is never used.. error or can it be removed?

**Comment by jkandasa** [comment]
@pgh70 We were using UID tag in earlier versions to give unique identifications number for each sensor variable. I will modify this feature to recent version.

Thanks to report this.

**Comment by jkandasa** [comment]
first level correction https://github.com/mycontroller-org/mycontroller/commit/9e10496cd93bdf4c07936ecff2d3feaf4273b9c0
