### ISSUE TITLE
Add generic http and https post notification

### ISSUE THREAD

**Issue by bpair** [mycontroller-org/mycontroller#180]
When a sensor sends a SET message I like to post that data to a database (Grafana) via an http post. Can this be a new notification type? Ideally it would support basic authentication and also SSL.

**Comment by gbrd** [comment]
+1
+ HTTP GET support  too (I like graphs of https://emoncms.org)

**Comment by jkandasa** [comment]
@bpair 
>When a sensor sends a SET message I like to post that data to a database (Grafana) via an http post. Can this be a new notification type? Ideally it would support basic authentication and also SSL.

We may include this as send metrics data to Grafana as separate thread.

**Comment by jkandasa** [comment]
@gbrd 
> HTTP GET support too (I like graphs of https://emoncms.org)
I could not get this requirement exactly. Can you please elaborate bit more?

**Comment by gbrd** [comment]
It would be a generic functionality that allows to send data through a customizable http request to an external database. 

Emoncms is available "as a service ". It receives http get request (Rest api) with a personalkey and some temporal value (from  sensors from example). And that is able to plot several kind of graphs from all data.

**Comment by jkandasa** [comment]
@bpair can you point out API documentation to post data to  database (Grafana)?

**Comment by bpair** [comment]
Grafana is a graphing/web app that fronts a database like Graphite or InfluxDB. The link below explains the http api for influxDB. For pushing data it is pretty simple, database name, measurement name, key, value. You can optionally pass the time. So for me:    -the database name is fixed     -the measurement is really the type of data (Temperature),     -key is my node_id (50) sensor_id(1) identifier but in a human readable form such as Tank1_Temp    -value is the value

InfluxData Documentation

  
|  
|   |  
InfluxData Documentation
 Documentation for InfluxDB, Telegraf, Chronograf, and Kapacitor  |  |

  |

 

thanks for all your hard work!
Brit

**Comment by jkandasa** [comment]
https://github.com/mycontroller-org/mycontroller/commit/bffa84207bc934351a2838fd5bc31b44ecb7b0ad supports for POST data to,
- influxDB (v0.13.0)
- https://emoncms.org/
- https://data.sparkfun.com / phant.io
