### ISSUE TITLE
Upgrade Instructions with Backup 

### ISSUE THREAD

**Issue by bpair** [mycontroller-org/mycontroller#182]
To upgrade from 0.0.3-alpha1 to 0.0.3-alpha2-SNAPSHOT I created a backup. Downloaded zip, extracted in new location and started the new mycontroller app. No backups were available because it is looking for backups in the new installation. It may be better to have the default backup location be in the user home directory and you should be able to search for existing backups to use.

**Comment by jkandasa** [comment]
@bpair User location also might not give proper solution for this. as user may change their location at anytime. I feel this is one time work setting correct backup location when we upgrade to new version.

**Comment by jkandasa** [comment]
@bpair we will document this approach.
