### ISSUE TITLE
Last seen does not always update

### ISSUE THREAD

**Issue by bpair** [mycontroller-org/mycontroller#183]
My sensor was loaded from a backup after upgrading and although the sensor value was being updated and the graph updated the "last seen" continued to say never.
![lastseennotupdating](https://cloud.githubusercontent.com/assets/11282848/14587590/6e1f55ee-0483-11e6-9c31-c0308da5a1b3.png)
![lastseenandnoalarm](https://cloud.githubusercontent.com/assets/11282848/14587592/70b98504-0483-11e6-9bfc-3de588744b4c.png)
![system](https://cloud.githubusercontent.com/assets/11282848/14587593/7b6be19a-0483-11e6-9cd2-0c1d81dc4546.png)

**Comment by jkandasa** [comment]
@bpair Thanks to report this issue. This might be a bug. Let me find out.

**Comment by jkandasa** [comment]
@bpair it looks like you are using old version. In recent version I do not see `Alarm definition` and `Timer` in sensor details page. can you please check once again?

**Comment by jkandasa** [comment]
@bpair I am unable to reproduce this issue. Please reopen this issue if you face this issue in recent version.
