### ISSUE TITLE
Selected Row Highlight Makes Enabled appear as Disabled

### ISSUE THREAD

**Issue by bpair** [mycontroller-org/mycontroller#184]
This was a bit confusing for me as I was troubleshooting why a rule was not triggering. The rule is enabled, but if I select the rule then it appears as disabled.
![highlightedrowchangesenabledicon](https://cloud.githubusercontent.com/assets/11282848/14587605/b7e38da8-0483-11e6-8e8d-27e1457cb0e4.png)

**Comment by jkandasa** [comment]
@bpair It is design when we select a row in a table make all the text to `White` color. Disabled will be looking as circle and enabled will be like ball. 

![image](https://cloud.githubusercontent.com/assets/1004403/14669854/50ad782e-0708-11e6-9f3c-f13ade74dea2.png)

I hope we can find out easily, Is in enabled or disabled state.
