### ISSUE TITLE
Need documentation and examples for rules

### ISSUE THREAD

**Issue by bpair** [mycontroller-org/mycontroller#185]
I could not get the rule to trigger for a binary/door sensor. I probably am configuring it incorrectly but the manual needs to explain the options and provide examples.
![ruleshardtodefinewoexamples](https://cloud.githubusercontent.com/assets/11282848/14587629/efa27614-0483-11e6-98b7-46ceb15a726b.png)

**Comment by jkandasa** [comment]
@bpair Sure I will add it soon.

**Comment by jkandasa** [comment]
@bpair working on `Rules` documents http://forum.mycontroller.org/topic/24/rules-introduction
