### ISSUE TITLE
Alarm/Rule Association does not appear on sensor

### ISSUE THREAD

**Issue by bpair** [mycontroller-org/mycontroller#186]
I created a rule for a particular sensor but the sensor detail view does not show that rule being associated. Also the sensor detail view is using the term Alarm rather than Rule.
![lastseenandnoalarm](https://cloud.githubusercontent.com/assets/11282848/14587639/21ad0732-0484-11e6-964e-b774d9cc8e76.png)

**Comment by jkandasa** [comment]
@bpair Alarm definition no more mapped with resources. We have to remove this field from sensors detail. Thank you! I will remove it.

**Comment by jkandasa** [comment]
In recent version this details not all available. only shows `Resources groups`
