### ISSUE TITLE
View of details allows updating of buttons

### ISSUE THREAD

**Issue by bpair** [mycontroller-org/mycontroller#187]
Not sure how this works for roles but I think when viewing the details you want the user to have to click "edit" before having active elemen
![viewscreenallowsupdateofbuttons](https://cloud.githubusercontent.com/assets/11282848/14587670/9b009518-0484-11e6-8c6c-d15fc6815f35.png)
ts to edit. Currently the text fields are view only but the buttons are editable.

**Comment by jkandasa** [comment]
@bpair I tried to make disable `state` button as disabled. But unable to make it. however if user changes button state, edit mode will be enabled automatically. And user should save to make change permanently.
