### ISSUE TITLE
MQTT Broker Host suggests http:// but only accepts tcp://

### ISSUE THREAD

**Issue by rollercontainer** [mycontroller-org/mycontroller#189]
By creating or editing the Broker Host, you have to type tcp://.....

Shoudn't it be http:// ?

**Comment by jkandasa** [comment]
@rollercontainer  As far as i know, MQTT protocol supports only `tcp://` and `ws://`. So we cannot use `http://`. Please correct me if I am wrong.

**Comment by rollercontainer** [comment]
How about an IP input field without protocol info if it is fix?

**Comment by jkandasa** [comment]
@rollercontainer  You should give IP or hostname with protocol and port information information, as `MQTT` supports for `tcp` and `ws`. Most of us using `tcp://`

**Comment by rollercontainer** [comment]
Ok, close it. :-)
