### ISSUE TITLE
Error when adding gateway MySensors Arduino Library v2.0.0-beta

### ISSUE THREAD

**Issue by jgate** [mycontroller-org/mycontroller#191]
Hi
I started testing the new release 0-0-3-alpha2. I started from scratch with an empty database. I'm using  MySensors Arduino Library v2.0.0-beta.

The attached contains the gateway entry that causes the issue
![2016-05-04 18_10_06-mycontroller org - resources-issue 1](https://cloud.githubusercontent.com/assets/3542189/15021895/7e1e4618-1229-11e6-8101-d1d6066b6e75.png)
See what is happening in the log file:
[2016-05-04 18_10_06-MyController.org - Resources-Issue.txt](https://github.com/mycontroller-org/mycontroller/files/249210/2016-05-04.18_10_06-MyController.org.-.Resources-Issue.txt)

Regards

**Comment by jkandasa** [comment]
@jgate Thanks to report this issue. I will find out the root cause.

**Comment by jgate** [comment]
Thanks it is working now
