### ISSUE TITLE
Two wishes

### ISSUE THREAD

**Issue by jgate** [mycontroller-org/mycontroller#192]
Hi

Is it possible to get a **Test connection** button when defining email host data:
![2016-05-04 17_49_41-mycontroller org - test-connection-button](https://cloud.githubusercontent.com/assets/3542189/15022171/ab9d584e-122a-11e6-9f21-04e12a99adf5.png)

and the edit button also on the top:
![2016-05-04 17_55_06-mycontroller org - metrics-edit-button](https://cloud.githubusercontent.com/assets/3542189/15022177/b1d91ef0-122a-11e6-98d3-2bb082b51e57.png)

Thanks and regards

**Comment by jkandasa** [comment]
@jgate good request. Will try to address in 0.0.3.Alpha2

**Comment by jgate** [comment]
Many thanks for this, it is working.
