### ISSUE TITLE
Heatmap legend is not visible

### ISSUE THREAD

**Issue by jgate** [mycontroller-org/mycontroller#193]
Hi

When I ckeck "Show legends", no legend is visible:
![2016-05-04 20_31_46-mycontroller org - heatmap-legend-propertie](https://cloud.githubusercontent.com/assets/3542189/15025023/9a0d08ec-1237-11e6-8665-d2e63a416740.png)
![2016-05-04 20_31_46-mycontroller org - heatmap-legend](https://cloud.githubusercontent.com/assets/3542189/15025030/a1565324-1237-11e6-83dd-c8642fd50b66.png)

Regards

**Comment by jkandasa** [comment]
@jgate `Show legends` to display color data in bottom. here it is `Up, Unavailable, Down`
When you mouse over on the box, you will get tooltip of the box and when you click it will take you to the actual page.

**Comment by jgate** [comment]
Sounds good thank for this information. But something like thid this would be helpful:
![2016-05-04 20_31_46-mycontroller org - heatmap-legend](https://cloud.githubusercontent.com/assets/3542189/15025403/665a5c78-1239-11e6-97d7-ffd03a5c2afd.png)

Regards

**Comment by jkandasa** [comment]
@jgate I see tooltip, even it is available in demo site also. demo.mycontroller.org

![heat-map](https://cloud.githubusercontent.com/assets/1004403/15025910/3cb9f48a-1259-11e6-9fd4-277f7ef6efbc.png)

**Comment by jgate** [comment]
Yes it is working on demo.mycontroller.org but not on my installation.

**Comment by jkandasa** [comment]
what is your browser and operating system are you using?

**Comment by jgate** [comment]
Windows 10 and Google Chrome Version 49.0.2623.112 m

**Comment by jgate** [comment]
Sorry there was a pending restart for the browser after update. Restart browser solved the issue.

**Comment by jkandasa** [comment]
@jgate great :+1:  no worries.

**Comment by jkandasa** [comment]
@jgate Thanks to take time to analysis MyController.org and reporting issue :+1:
