### ISSUE TITLE
Unit button Save not change back to Edit after saving a change

### ISSUE THREAD

**Issue by jgate** [mycontroller-org/mycontroller#194]
Hi 

The button Save is not change back to Edit after saving. When you click on Cancel the button name is changing back to Edit.
![2016-05-05 16_27_13-mycontroller org - unit-issue](https://cloud.githubusercontent.com/assets/3542189/15046167/bcc19432-12de-11e6-8463-98c8a8a23b7a.png)

and also on this dialog it would be great when the Edit button is also available on the top of the page:
![2016-05-05 16_27_42-mycontroller org - unit](https://cloud.githubusercontent.com/assets/3542189/15046205/dc411198-12de-11e6-85a1-1dea41b144e7.png)

Thanks and regards
Rolf

**Comment by jkandasa** [comment]
@jgate we might remove this page permanently soon as units never change.
received feedback from @S0rc3r3r and finalized that, we can hard code units in code itself.

**Comment by jkandasa** [comment]
removing edit unit not in near future list. fixed this issue in https://github.com/mycontroller-org/mycontroller/commit/a3787358f3ff681e7ee4f9907d4969dd52ac15f4
