### ISSUE TITLE
Sort by Node EUI

### ISSUE THREAD

**Issue by Werwolfx** [mycontroller-org/mycontroller#195]
1. You can add more than 10 lines shown in the tables in the sensor sections and add a button to "Show all " . 
![default](https://cloud.githubusercontent.com/assets/14030285/15181257/e0bfcf48-178e-11e6-9331-20645afcb37b.JPG)

2. And also add sorting by NODE EUI

**Comment by jkandasa** [comment]
@Werwolfx for the comment 1. you can change this under `Settings >> System >> MyController >> Table rows limit`
I will add sort by `Node EUI`

**Comment by Werwolfx** [comment]
Thank you/
i will rename issues to Sort by Node EUI
