### ISSUE TITLE
Trace a specific node

### ISSUE THREAD

**Issue by WimVerhaert** [mycontroller-org/mycontroller#198]
When troubleshooting I want to be able to trace a specific node.
Would it be possible to allow to trace just individual nodes instead of ALL nodes?

**Comment by jkandasa** [comment]
@WimVerhaert With current approach, which is not possible. I will take this as feature requirement and implement it.

I believe this ticket relevant to this one #157

**Comment by seant100** [comment]
I assume this means filtering Resource Logs by sensor. That would be a great feature to add.

**Comment by jkandasa** [comment]
https://github.com/mycontroller-org/mycontroller/issues/473 may address part of the issue. we are not going to support fully in 1.x
