### ISSUE TITLE
No donation option

### ISSUE THREAD

**Issue by githubcdr** [mycontroller-org/mycontroller#20]
This is such a cool project that I want to donate some beers. (or coffees if you will)

The interface and website do not feature a donate option, how can users donate to this project?

**Comment by jkandasa** [comment]
@githubcdr Thank you very much for your support! This will help me to buy new hardware for MyController server. I'm working on creating donation account. I will update you once it get ready!

Thank you very much!

**Comment by githubcdr** [comment]
np, really like your effort and your dedication

**Comment by Dietmar-Franken** [comment]
@jkandasa 
You forgot to close this?

**Comment by jkandasa** [comment]
@Dietmar-Franken yet to add this in main site. Will close soon. thank you!

**Comment by jkandasa** [comment]
Donation option added in main site. [MyController.org](http://www.mycontroller.org/)
