### ISSUE TITLE
Group Logical State Operation (Feature Request)

### ISSUE THREAD

**Issue by Takero1978** [mycontroller-org/mycontroller#202]
At the Moment all Groups are "AND" Related. It would be nice if it is possible to set up to an other relationship, e.g. "OR". 

For Example:
- I have four Windows in one Living Room
- I have one LED to illuminate the State of my Windows in these one Living Room

Now i need an OR operation to get the State of my Windows and send the single Payload to my LED-Node.

**Comment by jkandasa** [comment]
@Takero1978 Can you please elaborate bit more about this.  Which grouping you are pointing out.

We can achieve your requirement with scripts.

**Comment by Takero1978** [comment]
Ok i will try . . 

I think the Problem or the Feature is maybe also a rules feature. 

The Problem is, Groups are Working only in one direction. If you have an group with two lamps and u set the Group-Button to On/Off, everything is OK. But if you manually put Lamp1 and Lamp2 on separately, the group button will not intact with it. 
In this case we need a compare of the group entries in booth directions, and the state of the group Item.

Or . . . we need a possibility of an rule with more variables and logical dependencies. 

In my case with the Windows:
If you haven an Indication LED or something else to inform you in this Room is one Window open. For Example in this room you have 4 windows, it will make following possibilities (In brackets the value for LED Indication): 

- 0 0 0 0 (0)
- 0 0 0 1 (1)
- 0 0 1 0 (1)
- 0 0 1 1 (1)
- 0 1 0 0 (1)
- 0 1 0 1 (1)
- 0 1 1 0 (1)
- 0 1 1 1 (1)
- 1 0 0 0 (1)
- 1 0 0 1 (1)
- 1 0 1 0 (1)
- 1 0 1 1 (1)
- 1 1 0 0 (1)
- 1 1 0 1 (1)
- 1 1 1 0 (1)
- 1 1 1 1 (1)

Greetings

**Comment by jkandasa** [comment]
@Takero1978 Thank you for the explanation. Let me find out a solution to fix this request.

**Comment by jkandasa** [comment]
@Takero1978 if you still interested in this feature, reopen this issue
