### ISSUE TITLE
are not displayed at the bottom of the sensor names in the topology

### ISSUE THREAD

**Issue by arturmon** [mycontroller-org/mycontroller#203]
cut off the names
![43423](https://cloud.githubusercontent.com/assets/7686999/15465754/e7c03f86-20de-11e6-9eef-469fd3222cbd.jpg)

**Comment by jkandasa** [comment]
@arturmon It is by design. Name of the sensor will be shown on bottom. If we see in small screen will be looking like this. However we can drag the sensor and can get complete view. Please reopen this issue if you cannot drag.
