### ISSUE TITLE
Status page, resource log hangs when items per page set to 500

### ISSUE THREAD

**Issue by turbatus** [mycontroller-org/mycontroller#205]
When changing the number of items to display to 500, MyC runs very slow, hangs for few seconds. Tested on demo site and on local RPi2. System CPU load jumps to 100%.

**Comment by jkandasa** [comment]
@turbatus Yes, loading more number of rows at a time will lead performance issue on server side as well as on client side (on browser).

**Comment by turbatus** [comment]
Well, I kinda thought that way myself. But, since this can cause problems, is really needed to display 500 items at once? i think 250 will do just fine. my opinion...

**Comment by jkandasa** [comment]
@turbatus I do not face hangs issue with our demo site as well as with RPi2. I hope you are running browser on low-end system.

For me it takes around ~3 seconds. My RPi2 running with `Raspbian` and no desktop installed on it. Java (oracle): 1.8.0_65-b17

**Comment by turbatus** [comment]
well, then it was a false alarm. I'll close this issue, then. Thank you.

**Comment by jkandasa** [comment]
@turbatus Thank you!
