### ISSUE TITLE
Showing NaN to NaN of 15 items

### ISSUE THREAD

**Issue by WimVerhaert** [mycontroller-org/mycontroller#206]
under the tab action board =>sensors action => at bottom of page it shows 
Showing **NaN** to **NaN** of 15 items.

sounds like an unknown value

**Comment by jkandasa** [comment]
@WimVerhaert can you check `Settings >> System >> MyController >> Table rows limit`? You have to set this, if it is not set already.

**Comment by WimVerhaert** [comment]
it seemed to have been set with value 10, but resetting it to value 11 it resolved the problem

**Comment by jkandasa** [comment]
@WimVerhaert in that cause logout and login with browser refresh will help you
