### ISSUE TITLE
subject in email not correct

### ISSUE THREAD

**Issue by WimVerhaert** [mycontroller-org/mycontroller#207]
I have a rule to send an email upon a sensor value coming in.
The subject line according to the config under 'operations' should be 
`CatDoor Motion detected`

However when I receive my email the subject shows: 
`**#set(org.mycontroller.standalone.operation.Notification notification)**CatDoor Motion detected `

**Comment by jkandasa** [comment]
@WimVerhaert recently I changed template engine from `httl` to `freemarker`, I forget to remove `httl` entries. I will fix this. Thank you!
