### ISSUE TITLE
Implements pending command to node that uses smartSleep

### ISSUE THREAD

**Issue by pebri86** [mycontroller-org/mycontroller#208]
Please implements smartSleep feature on MySensors v2.0.0beta, all of mysensors nodes use this feature to save battery. This feature is really depends on controller support.

thanks,

**Comment by cimba007** [comment]
Just to sum up what smartSleep does (according to the mysensor-code):

int8_t smartSleep(unsigned long ms) {
	int8_t ret = sleep(ms);
	// notifiy controller about wake up
	sendHeartbeat();
	// listen for incoming messages
	wait(MY_SMART_SLEEP_WAIT_DURATION);
	return ret;
}

As mycontroller does not know if the node is using smartsleep the following should be done:

- Publish commands to the MQTT-Broker .. 
- Add the command to a queue specific to the node .. 
- If the node sends a heartbeat mycontroller had to resend the last command ..

This is not consistent if mycontroller does not know if the other nodes use smartsleep so at best this feature had to be implemented in the mysensor-mqtt gateway.

If it had to be implemented on mycontroller .. it would be best to make a checkbox for each node and queue up commands until there is a heartbeat message .. 

PS: Sending all queueud commands at once might cause congestions .. so this is no simple topic .. maybe add a configurable delay to the send-queue

**Comment by fab33** [comment]
+1

**Comment by jkandasa** [comment]
@pebri86 @cimba007 @fab33 smart sleep support added, but not tested fully.
Supports other than `stream` message types. When node sends `Heartbeat response` to controller. Controller sends available messages for that node. We have to enable `Smart sleep enabled` on node edit page of controller. 

NOTE: When you enabled `Smart sleep enabled`, Controller never send message to that particular node. Only sends when controller receives `Heartbeat response` from that node.

![image](https://cloud.githubusercontent.com/assets/1004403/19549270/02519a0e-96c1-11e6-8c9e-83938e4ee228.png)

**Comment by jkandasa** [comment]
closing this request, as this feature has implemented.

**Comment by iotmodules** [comment]
@jkandasa Hi and thanks for the link to the snapshot build. I have tried to test the support for SmartSleep however on the update node screen i don't get the Smart Sleep Enabled checkbox to tell the node it supports it.

I'm Using 

MyController
Version
0.0.3.Alpha2
Database version
1.02.10 - 2016 Jul 29
Git commit:branch
e8afb0266ab685dcfc59b0691ec301d3a17d3fd6:master
Built on
2016-07-30T01:04:37+0530
Build JDK
1.8.0_92
Build tool
Apache Maven 3.3.9
Java virtual machine specification
VM vendor
Oracle Corporation
VM name
Java HotSpot(TM) Client VM
VM version
1.8.0_65-b17
Java home
/usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt/jre
Operating system
Operating system
Linux
Architecture
arm
Version/Kernel
4.4.21-v7+

**Comment by jkandasa** [comment]
@iotmodules Your version indicates older one **0.0.3.Alpha2**

You should download and install [from here](https://drive.google.com/drive/u/0/folders/0BzuumrtRA7p6Z0hCX2V6cVh2ckU)

**Comment by iotmodules** [comment]
Hi have installed from the location you recommended still no sign of the
checkbox for smartsleep

Version0.0.3.Final-SNAPSHOTDatabase version1.03.04 - 2016 Oct 19Git
commit:branch2246de227ec1f6f6937972242a719e27cdb617ea:developmentBuilt on
2016-11-15T14:43:35+0530Build JDK1.8.0_111Build toolApache Maven 3.3.9

**Comment by jkandasa** [comment]
@iotmodules I guess you are facing GUI casing issue. Can you try to clear your browser cache? GUIDE: http://forum.mycontroller.org/topic/47/gui-caching-issue-problem

**Comment by iotmodules** [comment]
Hi

That sorted it the cache cleared and the new pages now show.

Cheers

Doug

**Comment by seant100** [comment]
Hi

If smartSleep is enabled for a node then a request for time is not sent by MyController. Is there a way to receive a time request for a node that sleeps.

Thanks
