### ISSUE TITLE
Feature: support for HTTP GET/Post

### ISSUE THREAD

**Issue by chrigui** [mycontroller-org/mycontroller#212]
it would be great to add support for HTTP GET and post to communicate with other web  devices/services. 
this features will open support for a wide range of devices and online services.

thanks.

**Comment by jkandasa** [comment]
@chrigui We could nit give generic support. However we can develop small amount of code to achieve specific service.

I have implemented https://data.sparkfun.com support on https://github.com/mycontroller-org/mycontroller/commit/bffa84207bc934351a2838fd5bc31b44ecb7b0ad
