### ISSUE TITLE
Time conditional rules

### ISSUE THREAD

**Issue by mariusvaida** [mycontroller-org/mycontroller#213]
First of all, thank you for this great controller. I love it!
However, i have a scenario for which i can't seem to find a solution:
A motion sensor which triggers a rule that is switches on a light or an alert. Over certain hours i would like to bypass this sensor, but i didn't found a way to do so.

**Comment by jkandasa** [comment]
@mariusvaida you mean you want to disable this rule for a particular time period?
If yes, we do not have direct control in rule. however we can create timer to `Enable` or `Disable` this rule.

**Comment by mariusvaida** [comment]
Ups, you right! :)
Thank you very much, i really didn't noticed that.
