### ISSUE TITLE
date not showing

### ISSUE THREAD

**Issue by WimVerhaert** [mycontroller-org/mycontroller#218]
On my dashboard I have a graph tha does not show the timestamp in human readable format,.. .other graphs are fine ,...
![image](https://cloud.githubusercontent.com/assets/17579415/15816751/a1ebf224-2bd4-11e6-9c16-21f2c2962ac1.png)

**Comment by jkandasa** [comment]
@WimVerhaert Yes, it is kind of issue with NVD3 graph, We have to find out a workaround for this.

When we uncheck ` Use interactive guide line` will show proper timestamp.

**Note:** I have seen many times that, `Y1` and `Y2` sensors data will not match properly with `X` access timestamp. This is also issue with NVD3

![image](https://cloud.githubusercontent.com/assets/1004403/15819641/182b3a44-2c02-11e6-98de-791908efe641.png)
