### ISSUE TITLE
Timestamp last communication

### ISSUE THREAD

**Issue by WimVerhaert** [mycontroller-org/mycontroller#219]
Is it possible to add a timestamp in the dashboard to indicate the last communication of a sensor node or a sensor variable?
Now I always have to scroll over a graph to see the last communication of the node or go to the action board,... would be nice to just add it to the dashboard.

**Comment by jkandasa** [comment]
@WimVerhaert We can use custom widget for this requirement. I will update any example

**Comment by jkandasa** [comment]
@WimVerhaert here is the example for node `last seen`

##### Java script
---
```
var HashMap = Java.type("java.util.HashMap");
var options = new HashMap();

//Sort by lastSeen. (there is typo in 'laseSeen' --> we have to fix this)
options.put("orderBy", "laseSeen");
//Order by descending
options.put("order", "desc");
//Get nodes data
var nodes = mcApi.node().getAll(options);
```

##### HTML Template
```
<table class="table table-hover table-bordered table-striped mc-table">
  <thead>
    <th>Status</th>
    <th>EUI</th>
    <th>Name</th>
    <th>Type</th>
    <th>Battery level</th>
    <th>Last seen</th>
  </thead>
  <tbody>
    <#list nodes.data as item>
      <tr>
        <td class="text-center">
          <#if item.state == "UNAVAILABLE">
            <i class="pficon pficon-help text-color-gray fa-lg"></i>
          <#elseif item.state == "DOWN">
            <i class="pficon pficon-error-circle-o fa-lg"></i>
          <#elseif item.state == "UP">
            <i class="pficon pficon-ok fa-lg"></i>
          </#if>
        </td>
        <td>${item.eui}</td>
        <td>${item.name}</td>
        <td>${item.type.text}</td>
        <#if item.batteryLevel??>
          <td><span>${(item.batteryLevel)!"-"} %</span></td>
        <#else>
          <td><span>-</span></td>
        </#if>
        <td><span>${mcApi.utils().friendlyTime(item.lastSeen)}</span></td>
      </tr>
    </#list>
  </tbody>
</table>
```
You can add remove the columns whatever you want.

In dashboard select `Custom widget` (by default `-1` will not get refresh, change `-1` to some value, example: `30` seconds) then, select your script file and template file.

**Note:** you should use the latest version of MyController

**Comment by WimVerhaert** [comment]
thx for the quick feedback,..

I tried it on the demo site and it works,
On my site however it is giving error "TypeError: org.mycontroller.standalone.api.NodeApi@186110c has no such function "getAll" in  at line number 9"

Mycontroller version is ,...
![image](https://cloud.githubusercontent.com/assets/17579415/15849906/319cd210-2c95-11e6-85ad-06ab10610a9e.png)


also can I do the same thing for sensors?

**Comment by jkandasa** [comment]
@WimVerhaert Yes, I have added some changes in code, you have to use latest version of MyController

For latest version check, https://gitter.im/mycontroller-org/mycontroller?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by jkandasa** [comment]
@WimVerhaert Here is sample code for sensors last seen status,

##### Java script
---
```
var myImports = new JavaImporter(java.io, java.lang, java.util);

with(myImports) {
  var options = new HashMap();
  //Sort by lastSeen.
  options.put("orderBy", "lastSeen");
  options.put("pageLimit", new Long(5));
  //Order by descending
  options.put("order", "desc");
  //Get sensors data
  var sensors = mcApi.sensor().getAll(options);
}
```

##### HTML code(template)
---
```
<table class="table table-hover table-bordered table-striped mc-table">
  <thead>
    <th>Node name</th>
    <th>Node EUI</th>
    <th>Sensor Id</th>
    <th>Name</th>
    <th>Type</th>
    <th>Last seen</th>
  </thead>
  <tbody>
    <#list sensors.data as item>
      <tr>
        <td>${(item.node.name)!}</td>
        <td>${(item.node.eui)!}</td>
        <td>${(item.sensorId)!}</td>
        <td>${(item.name)!}</td>
        <td>${(item.type.text)!}</td>
        <td><span>${mcApi.utils().friendlyTime(item.lastSeen)}</span></td>
      </tr>
    </#list>
  </tbody>
</table>
```
![image](https://cloud.githubusercontent.com/assets/1004403/15857053/ee6f9198-2cd6-11e6-83f9-ffe05c6d1667.png)
---
![image](https://cloud.githubusercontent.com/assets/1004403/15857046/e18a86b8-2cd6-11e6-91a9-7477a030cfa7.png)

**Comment by jkandasa** [comment]
@WimVerhaert I made some changes, kindly check and report if you face any error. Thank you.

**Comment by WimVerhaert** [comment]
thx for this update...

I updated the version to the alpha2-snapshot,... and everything works,...
great work.

Question: where can I find information on how to write these javascripts, 
I'd like to request the info for a specific  node or sensor instead of doing a getAll....

**Comment by jkandasa** [comment]
@WimVerhaert I am working on the document for scripts. You can see API details here, but you may expect slight change before release, http://www.mycontroller.org/files/docs/javadoc/apidocs/index.html?org/mycontroller/standalone/api/package-summary.html

To filter specific node/sensor, you can pass the following filters,

##### For Node
```
var myImports = new JavaImporter(java.io, java.lang, java.util);

with(myImports) {
  var options = new HashMap();
  //Sort by node eui
  options.put("orderBy", "eui");
  //Order by ascending
  options.put("order", "asc");

  //Filter by Node EUI
  options.put("eui", Arrays.asList("1", "2"));
  //Filter by Name
  options.put("name", Arrays.asList("node-1", "node-2"));

  //Get nodes data
  var nodes = mcApi.node().getAll(options);
}
```

##### For Sensor
```
var myImports = new JavaImporter(java.io, java.lang, java.util);

with(myImports) {
  var options = new HashMap();
  //Sort by Sensor ID
  options.put("orderBy", "sensorId");
  //Order by ascending
  options.put("order", "asc");

  //Filter by Sensor ID (Integer)
  options.put("sensorId", Arrays.asList(1, 2, 3));
  //Filter by Sensor name (String)
  options.put("name", Arrays.asList("sen-1", "sen-2"));

  //Get nodes data
  var nodes = mcApi.sensor().getAll(options);
}
```

**Comment by jkandasa** [comment]
@WimVerhaert I am closing this issue. Please reopen if you face any problem on this.
