### ISSUE TITLE
Button to save changes in the "My_controller" section

### ISSUE THREAD

**Issue by aldepas** [mycontroller-org/mycontroller#221]
0.0.3.Alpha2-SNAPSHOT

When I want to edit the configuration "My_controller", the "Save" button is disabled. 
![mysensor](https://cloud.githubusercontent.com/assets/19816779/15890313/30a49872-2d6f-11e6-92f5-370c64b1f914.JPG)

**Comment by jkandasa** [comment]
@aldepas It is because I made `Widget image file disk location` as mandatory field. I will make this field as optional or add default location.

Thank you!
