### ISSUE TITLE
Improved Topology

### ISSUE THREAD

**Issue by aldepas** [mycontroller-org/mycontroller#222]
1-When I see the topology graphically names are not displayed. When I select "Display names" and "Refresh", the names do not appear automatically. In order to display the names have to click the icons that represent to disable and re-enable them.

![captura5](https://cloud.githubusercontent.com/assets/19816779/15891908/2548f1c8-2d77-11e6-93c8-054180872a80.JPG)

2- The name of the sensors are never shown in the topology.
![captura3](https://cloud.githubusercontent.com/assets/19816779/15891989/7563285e-2d77-11e6-9011-6b37a0ae7f46.JPG)

3-It is confusing to see the "Gateway" also represented as a node and sensor as an attachment. Personally I remove that representation. In the event of a sensor connected to the "Gateway", would represent directly. Example:

![captura4](https://cloud.githubusercontent.com/assets/19816779/15891926/36d0a738-2d77-11e6-8a7a-12d77f60ae66.jpg)

4-generally in "Resources" the "Gateway" does not show or as a node or as a sensor, or at least, give the option to hide it.

![captura8](https://cloud.githubusercontent.com/assets/19816779/15892372/a0ea9b54-2d79-11e6-87b4-f26d602240b8.JPG)

![captura9](https://cloud.githubusercontent.com/assets/19816779/15892377/a39e31c6-2d79-11e6-92f7-88f31340d788.JPG)

5-Once ordered topology, to refresh the page, this structure is lost, it would be ideal to save the once orderly structure. Would add the option to add a background image in the topology to display more close to reality. Example:

![captura7](https://cloud.githubusercontent.com/assets/19816779/15892247/06f6eb6a-2d79-11e6-95d9-0bb0427a069b.jpg)

**Comment by jkandasa** [comment]
@aldepas Thank you very much for the great time with MyController!

> 1-When I see the topology graphically names are not displayed. When I select "Display names" and "Refresh", the names do not appear automatically. In order to display the names have to click the icons that represent to disable and re-enable them.
> 2- The name of the sensors are never shown in the topology.

Good catch, when we do not have name for some resources, this problem occurs, I will fix this

> 3-It is confusing to see the "Gateway" also represented as a node and sensor as an attachment. Personally I remove that representation. In the event of a sensor connected to the "Gateway", would represent directly.

:+1: Will fix this issue

> 4-generally in "Resources" the "Gateway" does not show or as a node or as a sensor, or at least, give the option to hide it.

I guess https://forum.mysensors.org/topic/2669/gateway-ready-message-with-sensor-id-0-v-1-6-beta/9 leads this issue. Which version of MySensors are you using?

> 5-Once ordered topology, to refresh the page, this structure is lost, it would be ideal to save the once orderly structure. Would add the option to add a background image in the topology to display more close to reality. 

I believe with the current version of topology design, we may not achieve this one. I will try to address this one.


Thank you so much for your analysis and diagrams, Your diagrams explains everything! :)

**Comment by aldepas** [comment]
> @aldepas Thank you very much for the great time with MyController!

Thank you very much to you for the great work you are developing.

> I guess https://forum.mysensors.org/topic/2669/gateway-ready-message-with-sensor-id-0-v-1-6-beta/9 leads this issue. Which version of MySensors are you using?

1.5 - Latest Release

**Comment by jkandasa** [comment]
@aldepas Yes, in 1.5 release we have this issue, Which is fixed in `MySensors` 2.0.0 version.
