### ISSUE TITLE
Binary Sensors on Chrome for Android

### ISSUE THREAD

**Issue by rayvenwalker** [mycontroller-org/mycontroller#225]
When I use my phone to toggle a binary sensor (one of four) from the a dashboard the physical sensor is toggled but the webpage shows the one above it changed.

**Comment by jkandasa** [comment]
@rayvenwalker Current web page is developed for desktop. For android we have to develop new app. Can you check sensor order in both webpag and on your mobile?

**Comment by jkandasa** [comment]
@rayvenwalker I am closing this issue, as current web UI not developed for android browser.
