### ISSUE TITLE
mycontroller webpage on raspberrypi (Web 3.8.2)

### ISSUE THREAD

**Issue by rayvenwalker** [mycontroller-org/mycontroller#226]
When i use the default browser on the raspberrypi (Web 3.8.2) the cells of the dashboard appear only 100px or so tall.  I can see a bit of what is on the top line.

**Comment by jkandasa** [comment]
@rayvenwalker Browser supports angularJS and patternfly will work smoothly. For not supported browsers we may see some difficulties. Can you put screenshot?

**Comment by jkandasa** [comment]
@rayvenwalker I am closing this issue, as current web UI not developed for android browser.
