### ISSUE TITLE
[Improvement] Rule Trigger Throtteling

### ISSUE THREAD

**Issue by cimba007** [mycontroller-org/mycontroller#231]
One thing I noticed is somewhat unclear to me. If some rules tripp an action. e.g. "Send a mail" .. is there a way to specify how often this should happen? I see an option to completely disable the rule after one time trigger but it would be nice to have a way to reset this.

e.g.

1. rule is triggered
2. mail is send
3. rule is disable
4. after configurable time elapsed (1 hour?) the rule is automatically reenabled

This would prevent spam in case of broken sensor or unintended triggers.

To clarify: I have noticed the dampening feature .. but this might still not be enough. My case is when a sensor goes rogue for whatever reason .. and I send a notification to my work email address. Under NO NO circumstances the email should be send multiple time and I don't want to reenable the rule after triggering.

**Comment by jkandasa** [comment]
@cimba007 This is good feature request! I can implement this one.
For now we have workaround for this option.
Create a `rule` for your sensor with auto disable option.
Create a simple `timer` with one hour interval (`3600` seconds) and repeat count as `1`

- Create the following operations,

1. Send email for your work email
2. Enable your rule
3. Enable your timer

Now map operations like mentioned here,
- In the `Rule` select `Operation`'s,  1 and 3
- In the timer select `Operation` 2

**Comment by jkandasa** [comment]
Addressed this feature request on the above commit,
![image](https://cloud.githubusercontent.com/assets/1004403/17359800/df4c09ae-5985-11e6-9984-a49f3d8620f4.png)

**Comment by cimba007** [comment]
Perfect!!! I wish I could test the current snapshot build ;-)

**Comment by jkandasa** [comment]
For now I'm sharing SNAPSHOT build on G drive: https://goo.gl/WTrK6v

I will try to automate this one.
