### ISSUE TITLE
Test setup shows ERROR: MqttException, Reload this gateway when MQTT Broker comes UP

### ISSUE THREAD

**Issue by ragflyer** [mycontroller-org/mycontroller#232]
Just built a simple setup of
0.0.3.Alpha2 for Win64, everything set on default
Mysensors MQTT Gateway on Nodemcu board, IP 192.168.2.109
Mysensors Binary switch sensor

GW Serial output:
Starting gateway (RNNGE-, 2.0.0)
0;255;3;0;9;TSM:INIT
0;255;3;0;9;TSM:RADIO:OK
0;255;3;0;9;TSM:GW MODE
scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 3
cnt 

connected with TP-LINK_2D01BC, channel 1
dhcp client start...
0;255;3;0;9;TSM:READY
f r0, scandone
.............ip:192.168.2.109,mask:255.255.255.0,gw:192.168.2.1
.IP: 192.168.2.109
0;255;3;0;9;No registration required
0;255;3;0;9;Init complete, id=0, parent=0, distance=0, registration=1
pm open,type:2 0

Then after powering binary switch:
0;255;3;0;9;TSP:MSG:READ 255-255-255 s=255,c=3,t=7,pt=0,l=0,sg=0:
0;255;3;0;9;TSP:MSG:BC
0;255;3;0;9;TSP:MSG:FPAR REQ (sender=255)
0;255;3;0;9;TSP:CHKUPL:OK
0;255;3;0;9;TSP:MSG:GWL OK
0;255;3;0;9;TSP:MSG:SEND 0-0-255-255 s=255,c=3,t=8,pt=1,l=1,sg=0,ft=0,st=bc:0
0;255;3;0;9;TSP:MSG:READ 255-255-0 s=255,c=3,t=3,pt=0,l=0,sg=0:
0;255;3;0;9;TSP:MSG:READ 255-255-0 s=255,c=3,t=3,pt=0,l=0,sg=0:
0;255;3;0;9;TSP:MSG:READ 255-255-0 s=255,c=3,t=3,pt=0,l=0,sg=0:
0;255;3;0;9;TSP:MSG:READ 255-255-0 s=255,c=3,t=3,pt=0,l=0,sg=0:
0;255;3;0;9;TSP:MSG:READ 255-255-255 s=255,c=3,t=7,pt=0,l=0,sg=0:
0;255;3;0;9;TSP:MSG:BC
0;255;3;0;9;TSP:MSG:FPAR REQ (sender=255)
0;255;3;0;9;TSP:CHKUPL:OK
0;255;3;0;9;TSP:MSG:GWL OK
0;255;3;0;9;TSP:MSG:SEND 0-0-255-255 s=255,c=3,t=8,pt=1,l=1,sg=0,ft=0,st=bc:0
0;255;3;0;9;TSP:MSG:READ 255-255-0 s=255,c=3,t=3,pt=0,l=0,sg=0:
0;255;3;0;9;TSP:MSG:READ 255-255-0 s=255,c=3,t=3,pt=0,l=0,sg=0:
0;255;3;0;9;TSP:MSG:READ 255-255-0 s=255,c=3,t=3,pt=0,l=0,sg=0:
0;255;3;0;9;TSP:MSG:READ 255-255-0 s=255,c=3,t=3,pt=0,l=0,sg=0:
0;255;3;0;9;TSP:SANCHK:OK
0;255;3;0;9;TSP:MSG:READ 255-255-255 s=255,c=3,t=7,pt=0,l=0,sg=0:
0;255;3;0;9;TSP:MSG:BC
0;255;3;0;9;TSP:MSG:FPAR REQ (sender=255)
0;255;3;0;9;TSP:CHKUPL:OK
0;255;3;0;9;TSP:MSG:GWL OK
0;255;3;0;9;TSP:MSG:SEND 0-0-255-255 s=255,c=3,t=8,pt=1,l=1,sg=0,ft=0,st=bc:0
0;255;3;0;9;TSP:MSG:READ 255-255-0 s=255,c=3,t=3,pt=0,l=0,sg=0:
0;255;3;0;9;TSP:MSG:READ 255-255-0 s=255,c=3,t=3,pt=0,l=0,sg=0:
0;255;3;0;9;TSP:MSG:READ 255-255-0 s=255,c=3,t=3,pt=0,l=0,sg=0:
0;255;3;0;9;TSP:MSG:READ 255-255-0 s=255,c=3,t=3,pt=0,l=0,sg=0:
0;255;3;0;9;Client 0 connected

Now I add the gateway to mycontroller:
Name: nodemcu1
Network type :MySensors TypeMQTT Broker 
host: tcp://192.168.2.109:5003
Client id: 0
Topic publish: mygateway-in
Topic subscribe: mygateway-out
Username & Password empty

And get status down, ERROR: MqttException, Reload this gateway when MQTT Broker comes UP

Seems like a very basic setup to me, did I miss anything?
Kind regards
Marius

**Comment by jkandasa** [comment]
@ragflyer It looks like you are running `Ethernet gateway` **NOT** `MQTT gateway`. If you are running `MQTT gateway` you have to configure your MQTT broker details on your gateway too.

To configure `Ethernet gateway`,

![image](https://cloud.githubusercontent.com/assets/1004403/17396029/f2d91164-5a4e-11e6-8af8-dc5ac6a38de8.png)

**Comment by ragflyer** [comment]
Correct, sorry my mistake. I changed the type to Ethernet which seems to work and will try MQTT after gaining some experience, thanks for pointing that out so quickly!
