### ISSUE TITLE
Resubscribe after hibernate

### ISSUE THREAD

**Issue by cimba007** [mycontroller-org/mycontroller#234]
This might only be a small point as in an actual productive environment this would probably not happen.

After running the server on Windows 8.1 64bit and hibernating and resuming my pc the gateways seems to be recognized correctly but subscribing/processing of individual sensors-date is not working.

I am 100% positive this can be solved by restarting the application.

On the first picture you can see that mqtt-spy recieves the messages form my mosquitto broker but mycontroller doesn't seem to get the values:

![image](https://cloud.githubusercontent.com/assets/3453121/17398543/a05b1ccc-5a3d-11e6-8ba9-baf0a68ccfd8.png)

Although the gateway seems to be recognized:
![image](https://cloud.githubusercontent.com/assets/3453121/17398552/ae4921a8-5a3d-11e6-8e07-dd055ba48282.png)

PS: It is around 12:15pm

**Comment by jkandasa** [comment]
@cimba007 It might be a known issue for MQTT client with Java. You may resolve this issue by reloading your gateway, `Resources >> Gateway` select your gateway and do `Actions >> reload`.

We can fix this issue in MyController by running a thread to identify, Is your computer walk up from sleep/hibernate, if so do `reload` automatically. However what I feel is we will not use MyController server in sleep/hibernate environment on production mode. In production mode it will be running 24x7 on a server  and MyController developed with resources in mind(We can run it on raspberry PI also). This extra thread might occupy some resource.

Your thoughts on this?

**Comment by cimba007** [comment]
This was exactly my thought. Might not be a big problem as the mycontroller server probably never would go to hibernate.

I was just wondering why the gateways was detected after hibernate but not the sensors.

Thank you for the tip with the workaround. This was just some thought - maybe this is a quick fix. No need to run extra resource occupying slots.

Feel free to close this issue.

**Comment by jkandasa** [comment]
@cimba007 For now I'm closing this request. If we have any other request similar to this, we can merge this request also along with new one.

Thank you!
