### ISSUE TITLE
Ressources -> Rooms

### ISSUE THREAD

**Issue by jgate** [mycontroller-org/mycontroller#237]
It is not possible to have a room called kitchen on different foors.

This is what I tried to configure:

Floor-1
Floor-1 -> Kitchen

Floor-2
Floor-2 -> Kitchen

![image](https://cloud.githubusercontent.com/assets/3542189/17449141/e6ab0bf8-5b58-11e6-8ee8-7887b82a8b73.png)

Here the error when I try to add kitchen on floor-2

![image](https://cloud.githubusercontent.com/assets/3542189/17449188/3f5cd2fe-5b59-11e6-9bc8-c0bd9d8dc4d2.png)

It seems you have a contraint on the name field, extend it with parent then it would be possible.

**Comment by jkandasa** [comment]
@jgate Nice catch!
