### ISSUE TITLE
Changes needed for metrics calculation

### ISSUE THREAD

**Issue by jkandasa** [mycontroller-org/mycontroller#238]
For now the default metrics calculations happens as follows,

![image](https://cloud.githubusercontent.com/assets/1004403/17456615/cc91d85c-5bfb-11e6-88d2-089ad9efd8a3.png)

There is no overlap happen between ranges. But we should need overlap on all data. When we load data for some time we should not mix all the range. It gives improper data points in graph. To avoid this we have to keep metrics data even in all the range.

**Comment by cimba007** [comment]
I am not sure if this is what you meant but if so it would depict the insonsistent behaviour:

![image](https://cloud.githubusercontent.com/assets/3453121/17745282/88b134f8-64ab-11e6-9034-f53fdc8de592.png)

My default retention settings look a bit different, but are consistent with the "missing" min/max/avg separation in the "last 6 hour"

![image](https://cloud.githubusercontent.com/assets/3453121/17745308/a9845552-64ab-11e6-97ba-fc0a0d82bc71.png)

**Comment by jkandasa** [comment]
@cimba007 Yes, this problem related to this feature request. For now there is no uniform result. 

In your report, for last 12 hours, showing 5 minutes sample for 6 hours and 1 minute sample for next six hours. Which leads this confusion. I will make it uniform to avoid this.

Thanks to report this one!

**Comment by cimba007** [comment]
![image](https://cloud.githubusercontent.com/assets/3453121/17897513/bfd1cf76-6954-11e6-9b03-3260b93e2cfd.png)

In the current snapshot I am no longer able to have a look at the "raw" values. In the current version (0.0.3.Alpha2) the last 6 minutes where pretty close to raw data .. is it possible to include a new time intervall "raw" to check raw data?

**Comment by jkandasa** [comment]
@cimba007 I will introduce last 5 minutes without any aggregation.

**Comment by cimba007** [comment]
Yeah, that would be really nice. ;-)
