### ISSUE TITLE
Minor improvement: Save sorting on Gateways, Sensors, Nodes view

### ISSUE THREAD

**Issue by cimba007** [mycontroller-org/mycontroller#242]
Is it possible to remember the last selected sorting method? Sorting by name seems weird to me. Maybe save the sort-order in a cookies?

Sorting by sensor name doesn't seem to intuitive for me - at least save the setting if the user changes it.

![image](https://cloud.githubusercontent.com/assets/3453121/17651148/d455849c-6260-11e6-9c74-93620239a04c.png)

**Comment by cimba007** [comment]
PS: https://raspi:8443/#/status/resourceslogs//

Resourcelogs seems to already "remember" the selected number of items per page.

**Comment by jkandasa** [comment]
@cimba007 Yes, it is possible to store in cookies.

**Comment by cimba007** [comment]
Workaround: Name nodes according to sort-order.
