### ISSUE TITLE
Reached Maximun limit: 1000

### ISSUE THREAD

**Issue by rayvenwalker** [mycontroller-org/mycontroller#246]
The server webpage wouldn't respond this morning.  I power cycled the raspberrypi and started the server again and am receiving this message repetedly.

`2016-08-19 08:07:53,856 WARN [pi4j-single-executor-0] [org.mycontroller.standalone.message.RawMessageQueue:52] Reached Maximun limit: 1000, Unable to add new message. Dropped`

**Comment by jkandasa** [comment]
@rayvenwalker could you please attach logs from `mycontroller/logs`?

**Comment by rayvenwalker** [comment]
[mycontroller.zip](https://github.com/mycontroller-org/mycontroller/files/426977/mycontroller.zip)

**Comment by jkandasa** [comment]
@rayvenwalker How many nodes/sensors do you have attached with MyController?

**Comment by rayvenwalker** [comment]
6 Nodes, 35 Sensors

**Comment by jkandasa** [comment]
Queue size increased from 1000 to 7000. 
https://github.com/mycontroller-org/mycontroller/commit/fba818f969bc475c72975d6f34faf6c53e937ba7

**Comment by jkandasa** [comment]
from this commit message queue moved to of-heap. Now there is no fixed limit for messages queue. However it is limited as Integer.MAX_VALUE.

https://github.com/mycontroller-org/mycontroller/commit/6cd8da74471e82c7fa04022df5f8c6ffb67e5f21
