### ISSUE TITLE
More errors and exceptions ..

### ISSUE THREAD

**Issue by cimba007** [mycontroller-org/mycontroller#248]
Sensor page totally unresponsive ..

I didnt even touch the node that sends battery informations .. my current "experimental" node just sends simpel values VAR1 and VAR2

http://pastebin.com/6LPXjXJ0

additional error from browser console:

![image](https://cloud.githubusercontent.com/assets/3453121/17819421/17ed79cc-6648-11e6-9056-a1c5c4420d19.png)

**Comment by jkandasa** [comment]
@cimba007 Looks like database corrupted.

Stop MyController and run database recovery tool.

To run database recovery tool,

* [download h2db](http://www.h2database.com/h2-2014-04-05.zip)
* Extract
* `cd` to `mycontroller/conf/`
* run `java -cp /path/to/h2/bin/h2-*.jar org.h2.tools.Recover`

If you are unable to recover, You have to start from fresh installation :(

**Comment by jkandasa** [comment]
I always recommend you to configure auto backup, you can restore When there is a situation like this.

![image](https://cloud.githubusercontent.com/assets/1004403/17819601/49a33506-6666-11e6-8959-88fb53a922fc.png)

**Comment by cimba007** [comment]
No problem about data loss, nothing very "important" to loose. I just post these issues to improve the software ;-) But I will try out the backup, ty

**Comment by jkandasa** [comment]
@cimba007 Thanks to report this issue. For database corruption we may not find out the issue at first site. This is the first time I'm seeing this issue. We will look in to this issue if it happens again.

You can enable backup on sub-folder or where MyController have write access. Yes, 7 days backup with 1 day interval will be good to go with minimum safety.

I'm closing this issue, We will reopen this again if this issue occurred again.
