### ISSUE TITLE
[Minor Improvement request] Sensor-Detail page could need an autorefresh

### ISSUE THREAD

**Issue by cimba007** [mycontroller-org/mycontroller#249]
To improve user excperience I suggest a possibility to adjust auto-refresh settings.
These is nothing that should receive "high" priority but I thought it is still noteworthy.

![image](https://cloud.githubusercontent.com/assets/3453121/17862935/c5163278-6897-11e6-84a8-a3c951a11c79.png)

Several pages could profit from autorefresh.

If you stay on this page the time marked parts will increase over time althought there has been some newer values received in the meantime:

![image](https://cloud.githubusercontent.com/assets/3453121/17862963/e6653cda-6897-11e6-9e20-99d9806912f5.png)

![image](https://cloud.githubusercontent.com/assets/3453121/17862988/07cd2720-6898-11e6-88dd-d61ff500b6f9.png)

These two sections are not that important as it is only a minor issue. In the sensor detail view it is unclear when the page will refresh.

![image](https://cloud.githubusercontent.com/assets/3453121/17863013/1fe85c76-6898-11e6-92b1-f6b489e0c844.png)

If I wan't to do some "realtime" testing having a finer granularity like e.g. on grafana might be beneficial.

e.g. _show the last 10 minutes and refresh every 5 seconds_
http://play.grafana.org/?panelId=4&fullscreen

Update:

![image](https://cloud.githubusercontent.com/assets/3453121/17867520/1b940dce-68ab-11e6-934e-782027c9972c.png)

This is the effect I was talking about .. leaving the site open while doing nothing will increase the timer although I am 100% sure there were some messages in the mean time.

**Comment by jkandasa** [comment]
@cimba007 refresh problem addressed with the above commit. These pages are get refreshed based on `Global refresh` time.

**Comment by cimba007** [comment]
Just noticed the 5 minutes option! Very nice!!!

![image](https://cloud.githubusercontent.com/assets/3453121/18020964/916aed9c-6be4-11e6-9265-2ce9fdb15fe5.png)

Now I can easylie debug my sensor
