### ISSUE TITLE
Question: RSSI and variable mapping

### ISSUE THREAD

**Issue by cimba007** [mycontroller-org/mycontroller#250]
Does the RSSI-field have any functunallity? I think it is not yet implemented in mysensor but it would be nice if it could be implemented like the battery leavel.

Would it be possible to map specific mysensor-message types to a mycontroller-message-type RSSI?

Like Mapping mysensors VAR5 to mycontroller RSSI? I would love to implement some custom RSSI measurement .. even if it would be just a percentage to note how many messages got lost on the way.

**Comment by jkandasa** [comment]
@cimba007 `RSSI` was introduced for ESP8266. This is not yet implemented on MyController. I will try to address this soon. Thank you!

**Comment by cimba007** [comment]
Make sure it is customizable. For example in my setup (RF24) I don't have a RSSI availalbe, only a combination of (IS RSSI > -64db) and the # of failed transmissions. So something like a float with at least 2-3 decimalpoints would be needed if I wanted to show a number like 0-100.000%

Thanks for your hard work

**Comment by jkandasa** [comment]
@cimba007 MyController will not do anything on `RSSI`. receives and displays what you sent.

you have to send `RSSI` message as follows from MySensors,
```
MyMessage msg(CHILD_ID,V_VAR5);
msg.set("rssi:95 dBm");
  send(msg);
```

**IMPORTANT:** `message-type` should be `set`, `sub-type` should be `V_VAR5` and `payload` should starts with `rssi:` (**lowercase**)

**Comment by cimba007** [comment]
Thanks, that sounds very promising. I will try it out and report back, thank you ;-)

**Comment by cimba007** [comment]
rssi feature is working very good for now. I did some slightly abuse of the "db"-value

![image](https://cloud.githubusercontent.com/assets/3453121/17945266/71b95832-6a43-11e6-9b52-b58365006341.png)

Using my custom wrapper class for sending messages I try to keep track of some stuff:

```c
static void rssi(char * buff, int buff_size)
{
  // "rssi:95 dBm" 
  int s = snprintf(buff,buff_size,"rssi: %u|%u|%u|%u",_successful,_sendtotal,_retry,_failure);
  if(s >= buff_size)
  {
    snprintf(buff,buff_size,"rssi: %d%%",100*_successful/_sendtotal);  
  }  
  //Serial.println(buff);
}
```

in combination with your code snippet:

```c
    static char buf[25];
    rssi(buf,25);
  
    MyMessage msg(1,V_VAR5);
    msg.set(buf);
    send(msg);
```

With this I can keep track of #lost messages thus providing an "indirect" qualit of my link. 

**Remark:** I do **not** use the NRF24 hardware autoretry as it is buggy on my modules.

**Comment by jkandasa** [comment]
> I even added an RPD-counter for the software ack from mycontroller .. keeping track of the number of received acks with good signal quality (RPD==1)

I guess MyController will not send any ack response. Let me check the code and update you.

**Comment by cimba007** [comment]
I use this code and mycontroller or the gateways (don't know) is sending mysensor software ack and this is working very reliable!!
```c
        send(_message,true);
        while(!ok && c)
        {
          // Ack?!
          if(wait(ms,_message.getCommand(),_message.type))
          {
            r.rpd = RF24_readByteRegister(RPD);
            _rpd += r.rpd;
            r.elapsedtime = micros()-starttime;
            r.success = true;
            r.retrycount = retrycountlimit-c;

            _successful++;
            return r;
          }
```

**Comment by cimba007** [comment]
Is working very good at the moment. Thanks ;-)
