### ISSUE TITLE
Change Timezone?

### ISSUE THREAD

**Issue by cimba007** [mycontroller-org/mycontroller#252]
![image](https://cloud.githubusercontent.com/assets/3453121/17897847/f5552386-6955-11e6-9c79-ccd72fed81c2.png)

![image](https://cloud.githubusercontent.com/assets/3453121/17897860/fa483d2e-6955-11e6-934d-35bb8c8be9b9.png)

Maybe I am missing something grade but is there an option to change to "local timezone"? Couldn't find a hint the in web interface or the manual ( http://www.mycontroller.org/#/documents/user/0.0.3.Alpha2.html )

**Comment by jkandasa** [comment]
@cimba007 Can you try to logout and login once. I hope you might logged in before changing timezone. it stores timzone and some other conf while doing login.

**Comment by cimba007** [comment]
yep, this solved the issue, thanks ;_)

I received my new microsd-card and had to reinstall my raspberry
