### ISSUE TITLE
bad emoncms calls: values in key

### ISSUE THREAD

**Issue by gbrd** [mycontroller-org/mycontroller#254]
Mycontroller creates some strange inputs on emoncms :
![c1](https://cloud.githubusercontent.com/assets/1265055/17946058/e9957c02-6a46-11e6-8415-b878d82cf3d8.jpg)

**Comment by cimba007** [comment]
Hi gbrd,

could you provide more information about your setup? Are you processing topics from the MQTT-Broker in emcons cms?

**Comment by jkandasa** [comment]
@gbrd could you post screen shot of `External servers` settings for `emoncms` without write API key?

**Comment by gbrd** [comment]
I used default settings

![image](https://cloud.githubusercontent.com/assets/1265055/18035640/d52d0850-6d59-11e6-94d7-62ba1a6421a3.png)

**Comment by jkandasa** [comment]
@gbrd I am unable to reproduce this issue. Could you try with [latest version](https://drive.google.com/drive/u/0/folders/0BzuumrtRA7p6dXZ5THdURUc1blU)?
For me it is working as expected, 
![image](https://cloud.githubusercontent.com/assets/1004403/18042445/0a8424b8-6ddf-11e6-91f1-2f450cbcfecb.png)

**Comment by gbrd** [comment]
The problem is not systematic. I have some good inputs too.
But after some days or weeks, when I came back to emoncms inputs, I had this entries.
I will try again with latest version.

**Comment by gbrd** [comment]
Not reproduced for now an the new version.

**Comment by jkandasa** [comment]
@gbrd cool, I hope we fixed it some where. We will wait few more days and close this issue. If we cannot reproduce.

**Comment by jkandasa** [comment]
@gbrd Feel free to reopen if you face this issue.
