### ISSUE TITLE
Requestengine not available (python)

### ISSUE THREAD

**Issue by cimba007** [mycontroller-org/mycontroller#257]
Connected to my post here:

http://forum.mycontroller.org/topic/44/question-example-script-like-operation-send-mail

I just get the following error with the example for python from the documentation:

```
{
  "errorMessage": "Requested engine is not available! McScript(engineName=null, mimeType=null, extension=py, name=TestPython, canonicalPath=/home/pi/mycontroller/conf/resources/scripts/operations/TestPython.py, type=OPERATION, size=198, lastModified=1472223865000, bindings={})"
}
```

For now I am testing pushbullet! Seems to be very nice!

**Comment by jkandasa** [comment]
@cimba007 MyController supports for `Python` scripts. But by default it's not shipped with Python-Java support engine which is www.jython.org

You have to add it manually. For more details please refer MyController documents

##### Steps to add new script engine

Download jar file and place it under `mycontroller/lib/` and restart MyController services.
For example if you want to add `Python` support on MyController, you need to add `Jython` library.
* Download jython-standalone-*.jar from Jython website.
* Place it under `mycontroller/lib/`
* Stop MyContorller
* Start MyController

**Comment by cimba007** [comment]
I switched over to pushbullet which is working fine. At the same time I don't know if yowsup will be supported after 31.12.2016 as even my official blackberry whatsapp client will no longer work in 2017.
