### ISSUE TITLE
Add support for Metric or Imperial

### ISSUE THREAD

**Issue by bpair** [mycontroller-org/mycontroller#26]
Allow for configuring Metric or Imperial and automatically respond to sensors if they inquire.

**Comment by jkandasa** [comment]
@bpair Thank you for the feature request.
Right now MyController responds to sensors as 'Metric' https://github.com/mycontroller-org/mycontroller/blob/master/src/main/java/org/mycontroller/standalone/AppProperties.java#L140

I will add it in system settings, so user can select "Metric" or "Imperial". But the selection should be common for all the sensors.
