### ISSUE TITLE
[Improvement] Multiple Conditions and/or Multiple Operations at the same rule

### ISSUE THREAD

**Issue by cimba007** [mycontroller-org/mycontroller#261]
Currently it is not possible to disable multiple rules with the same operation.

At the same time it is not possible to check multiple values in rules:

If Sensor1\Value > X AND Sensor2\Value < Y .. not possible at the moment. To enable more complex rules /operations it should be possible to "checked" and/or "modified" multiple rules/values whatever at the same time.

The same applies to operations. I wan't to use multiple notifications methods at the same time. Use pushbullet AND send an email ;-)

**Comment by jkandasa** [comment]
@cimba007 You can create multiple operations to disable multiple rules and can add all the operations to a rule/timer.

yes, for now MyController won't support multiple value on GUI. However you can use script for Rule also. You can check whatever you want and return true or false to rule.

**Comment by cimba007** [comment]
Thank you,I will try this out.
