### ISSUE TITLE
[Improvment] Pushbullet "Friends"

### ISSUE THREAD

**Issue by cimba007** [mycontroller-org/mycontroller#262]
Currently you can only notify deviced linked to your own account. Is it possible to add a list of friends that should also be notified? For Example if there is something important going on I want to notifie all family memberes?

My Suggestion is an additional (optional) field with email-addresses of friends just like statet here:

https://docs.pushbullet.com/#create-push

If it is already possible to get the iden of a friend via the api please feel free to close the issue ;-)

**Comment by jkandasa** [comment]
@cimba007 I will check this and update you.

**Comment by jkandasa** [comment]
@cimba007 Added option to send Pushbullet with `device idens` , `emails`, `channel tags`. You can use single of multiple fields.

![image](https://cloud.githubusercontent.com/assets/1004403/18044958/e966f3e6-6ded-11e6-8f5d-9fc61f85bb72.png)

**Comment by cimba007** [comment]
You are working very fast ;-) With this feature it is easy to notifie everybody on my household if something important happens ;-)

**Comment by jkandasa** [comment]
@cimba007 Kindly check this and close if everything works as expected.
