### ISSUE TITLE
On the sensor page it is not possible to select individual sensor and go to detail view

### ISSUE THREAD

**Issue by cimba007** [mycontroller-org/mycontroller#263]
Starting today I can no longer select individual sensors. Hovering the sensor the background (blue) starts to flicker and leftclick is not working.

Currently I can't reproduce this but this happend a few times earlier today.

**Comment by jkandasa** [comment]
@cimba007 Can you clear your browser cache? and try. If it happens report back with browser and OS details. Thank you!

**Comment by cimba007** [comment]
I will close this for now as it appears to only happend once. I assume that the session somehow timed out.

If you hover over the sensor I think there is a background request for the time but if the controller does not respond somehow the line gets deselected. To keep the issue section clean i will close this for now.
