### ISSUE TITLE
[Compability] Mobile phones

### ISSUE THREAD

**Issue by cimba007** [mycontroller-org/mycontroller#265]
Is the mycontroller website compatible with mobile phones? I tested different browsers on a spare (old) android phone running android 2.3.6 and all browsers just return MYCONTROLLER.ORG {{ 'APP.DESCRIPTION' ...

I have to note that the loading time is very large (10-15seconds) and thus the website's ajax might run into some timeouts. MIght this be the cause?!

**Comment by cimba007** [comment]
Edit: I tested this on my latest tablet with android 5.X and latest chrome browser .. it is working. So either the browsers for android 2.3.6 are too old or the timeout (as the phone is is slow) might be an issue.

**Comment by jkandasa** [comment]
@cimba007 MyController GUI is based on angularjs and designed for desktop/laptop devices. I believe android 2.x does not have this support. It may work if you install chrome browser on android 2.x

NOTE: We have an feature request for mobile version UI for MyController. https://github.com/mycontroller-org/mycontroller/issues/56

**Comment by cimba007** [comment]
The problem is that chrome browser is no longer supported on android 2.X. Current version from playstore requires android 4.X.

Developing an separate android client might be a lot of work. Android 5 with latest chrome is working very good on the mobile site. It would be much more comfortable if there would be a direct login like proposed on https://github.com/mycontroller-org/mycontroller/issues/258

Furthermore I like suggestion to use an "universal" client:
```
gbrd commented on 18 Feb
another solution could be to implement imperihome (http://www.evertygo.com/imperihome) 
standard API on server side
```

To get a mobile client it might even be worth to have a look at generic mqtt clients:

https://play.google.com/store/apps/details?id=net.routix.mqttdash

To make them work there have to be an option for the mqtt broker to send the latest values to a new connecting client.

**Comment by jkandasa** [comment]
> @jkandasa: Maybe you could add an option to enable/disable retention on all messages send from mycontroller.org to the mqtt broker? With this even nodes sleeping could receive missed subscriptions if they wake up (in theory)
https://mosquitto.org/man/mqtt-7.html @ "Retained Messages"
PS: This is a feature of the broker

Yes, this will be useful, but in some cases it will be painful. say you have some sensors with on/off button. When your node is not reachable state you sent more number of on/off data. once it comes your device connected on that node will get flicker.

>All messages may be set to be retained. **This means that the broker will keep the message even after sending it to all current subscribers. If a new subscription is made that matches the topic of the retained message, then the message will be sent to the client.** This is useful as a "last known good" mechanism. If a topic is only updated infrequently, then without a retained message, a newly subscribed client may have to wait a long time to receive an update. With a retained message, the client will receive an instant update.

This might not be good for IoT projects.

**Comment by cimba007** [comment]
I am not sure which message gets send. I would assume only the "most recent" would be send but I would have to double check this. Maybe it is possbible to enable this on a "per sensor" basis. 

Thinking about my "V_ARMED" switch I would find it super usefull to send the most recent status to newly connected clients (android phontes .. etc.)

**Comment by jkandasa** [comment]
> I am not sure which message gets send. I would assume only the "most recent" would be send but I would have to double check this. Maybe it is possbible to **enable this on a "per sensor" basis.**

enabling per sensor basis might lead more complication. I have a plan to implement communication support  for outside devices/anything to talk with MyController. This support must have MQTT support too. So you would use this new feature once available.

We have to implement along with this https://github.com/mycontroller-org/mycontroller/issues/148

**Comment by cimba007** [comment]
> Yes, this will be useful, but in some cases it will be painful. say you have some sensors with on/off button. When your node is not reachable state you sent more number of on/off data. once it comes your device connected on that node will get flicker.

To make this clear. There is a difference between persistence and retention.

http://www.hivemq.com/blog/mqtt-essentials-part-8-retained-messages
http://www.hivemq.com/blog/mqtt-essentials-part-7-persistent-session-queuing-messages

As you noted I think persistent sessions might get confusing but I still think retained messages might be usefull. Furthermore I noticed that you should not get confused about mqtt-broker -> mqtt-gateway and messages from gateway->node. retained messages would only be useful for 3rd party clients (but I am awaiting your newly advertised feature eagerly ;-)

For now I enabled retaintion for the way node -> gateway -> mqtt broker .. hoping any 3rd party mqtt-client like an android phone will get the most recent message (only the most recent not all messages it might have missed)

**Comment by ragflyer** [comment]
@cimba007 Have you successfully set up some actuator on your dashboard app? I manage to get MyController sensor values updated from my Android device through MQTT (mygateway-out), but the broker does not inform the actuator device of the update (it is subscribed to mygateway-in)

**Comment by ragflyer** [comment]
I was wondering if this is related:
If I use my android mqtt dashboard client to switch, it updates correctly on Mycontroller but nothing happens on the switch node (broker does not forward from mygateway-out to mygateway-in topic).
If I change the setpoint through web interface, switch node works, but only mqtt clients with separate in/out topics show the update correctly.
What is best practice here? Let switch node work on both in AND out topics?
And as workaround for the retained messages function, should I always let the node query Mycontroller on reconnect to get latest state?

**Comment by jkandasa** [comment]
@ragflyer looks like you have to swap your topic and subscription on your android mqtt client.
