### ISSUE TITLE
[Improvement] Dashboard -> Jump to detail view

### ISSUE THREAD

**Issue by cimba007** [mycontroller-org/mycontroller#266]
I would like to see a link from this:

![image](https://cloud.githubusercontent.com/assets/3453121/18037331/557f42a8-6d81-11e6-8fb8-41bee5c3a2b9.png)

by clicking the eye-icon or some other "yet to implement icon" to this view:

![image](https://cloud.githubusercontent.com/assets/3453121/18037337/6b9763d6-6d81-11e6-9488-c11a94adb06e.png)

**Comment by jkandasa** [comment]
@cimba007 implemented this one. Also added support from single graph and bullet chart.

**Comment by cimba007** [comment]
Very nice! That was very quick ;-)

**Comment by cimba007** [comment]
I would gladly test but the changes are not incoporated in latest snapshot yet?

**Comment by jkandasa** [comment]
@cimba007 It should be. Could you refresh your browser(F5) as it has UI changes?

**Comment by cimba007** [comment]
Indeed!! That damn caching ;-)
