### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by cimba007** [mycontroller-org/mycontroller#267]
```
2016-08-29 12:29:18,140 INFO [main] [org.mycontroller.standalone.StartApp:108] MyController.org server started in [15490] ms
2016-08-29 12:40:02,287 WARN [Thread-5] [org.mycontroller.standalone.operation.PushbulletUtils:97] Note push sending failed:ClientResponse(statusCode=400, errorMsg={"error":{"code":"invalid_param","type":"invalid_request","message":"The param 'email' has an invalid value.","param":"email","cat":"\u003e:3"},"error_code":"invalid_param"}, entity=null, success=false)]

**~13:51**
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x76871ce4, pid=702, tid=0x6d58b460
#
# JRE version: Java(TM) SE Runtime Environment (8.0_101-b13) (build 1.8.0_101-b13)
# Java VM: Java HotSpot(TM) Client VM (25.101-b13 mixed mode linux-arm )
# Problematic frame:
# V  [libjvm.so+0x477ce4]  ContiguousSpace::prepare_for_compaction(CompactPoint*)+0x9c
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/pi/mycontroller/bin/hs_err_pid702.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
```

hs_err_pid702.log

http://pastebin.com/U9fetXm2

![image](https://cloud.githubusercontent.com/assets/3453121/18050849/62c862a8-6df1-11e6-8d54-4db2d7cfa7bb.png)

**Comment by cimba007** [comment]
Currently I am starting mycontroller manually through the ./start.sh

Is it possible to write a service that (even if it crashes) will be immediatly restartet?

**Comment by jkandasa** [comment]
> Is it possible to write a service that (even if it crashes) will be immediatly restartet?

We may need to configure watchdog timer to monitor and start MyController on crash. If you want to start MyController on boot, have a [look here](https://forum.mysensors.org/topic/2262/server-restart/2)

> A fatal error has been detected by the Java Runtime Environment

For now I do not have any clue on this. It might be issue with JDK, If you face very often change JDK version any try again.
If you remember the steps(leads crash) please report. also you may try to enable core dump.
```
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
```

I m using the following version, I never faced any issue.
![image](https://cloud.githubusercontent.com/assets/1004403/18051915/173a8716-6e15-11e6-90d6-cf013270a709.png)
![image](https://cloud.githubusercontent.com/assets/1004403/18051922/2445aed6-6e15-11e6-80a2-299d2c3eea89.png)
![image](https://cloud.githubusercontent.com/assets/1004403/18051939/3653b4ec-6e15-11e6-88c2-cbf58e3e50df.png)

**Comment by jkandasa** [comment]
@cimba007 Are you using `python` script engine?

**Comment by cimba007** [comment]
Nope. I just started today with the latest scnapshot and restored from a previous backup. This is the first time this java crash occured to me. I will monitore it and look if I have further issues. 

As I currently start mycontroller every minute via crontask I don't expect further issues.

I am using java 1.8.0_101, only 36 versions newer then yours ;-)

http://forum.mycontroller.org/topic/34/mycontroller-on-raspberry-pi-rpi

**Comment by jkandasa** [comment]
@cimba007 cool, if we face this issue again we will think about it.

>I am using java 1.8.0_101, only 36 versions newer then yours ;-)

I do not meant that your are using old version ;) I meant that particular version might have issue.

>@Watchdog: Maybe this can be incorporated into the startup script? Start mycontroller and then do this again in a 60second loop. If calling ./stop you should issue stop command to mycontroller java AND stop command to the looping start script.
Just a suggestion ;-)

Yes, this should be nice one. I will think about this when I get time +1

**Comment by jkandasa** [comment]
>For now I added this to my crontab -e

* * * * ~/mycontroller/bin/start.sh
Your startup script is already checking if mycontroller is running so there should be no problem .. though a service would be cleaner

@cimba007 Yes, I forget to mention this. You found it! +1

**Comment by gbrd** [comment]
I had a similar crash :

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0xb66238f8, pid=536, tid=2851075168
#
# JRE version: Java(TM) SE Runtime Environment (8.0_65-b17) (build 1.8.0_65-b17)
# Java VM: Java HotSpot(TM) Client VM (25.65-b01 mixed mode linux-arm )
# Problematic frame:
# V  [libjvm.so+0x2e68f8]
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/pi/mycontroller/bin/hs_err_pid536.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#

**Comment by jkandasa** [comment]
@gbrd Could you please elaborate more on this, like in which case did you face this issue? Without any clue we may not find the root cause of the crash.

Thank you!

**Comment by cimba007** [comment]
I got a few crashes/errors over the last week too. As I restart mycontroller every minute by a cron-task I noticed nearly no outages .. but recently my raspberry pi hang up totally again.

Remember: I got a new micro sd card and freshly installed raspbian

Last SIGSEGV was 2 days ago ..


[Desktop.zip](https://github.com/mycontroller-org/mycontroller/files/465946/Desktop.zip)

What I can tell .. I am so far only doing some load tests. No rules, no scripts, no operations involved!

**Comment by jkandasa** [comment]
@cimba007 @gbrd Any one of you please enable core dump and send me the dump for further analysis. To enable core dump you have run `ulimit -c unlimited` before starting MyController. To knoe more about how to enable `ulimit` please [visit this](http://www.akadia.com/services/ora_enable_core.html) or some other doc from google.

**Comment by cimba007** [comment]
I entered the command. What will happen now? Will a SIGSERGV of Java write a core-dump file we could send you?

**Comment by cimba007** [comment]
@jkandasa: Are you using the same Java version as we do?

http://forum.mycontroller.org/topic/34/mycontroller-on-raspberry-pi-rpi

If not could you maybe upgrade? This might help reproducing our crashes.

If not .. what Java-version are you using? Might be worth trying your version.

**Comment by jkandasa** [comment]
@cimba007 No I'm using old version `jdk-8u65-linux-arm32-vfp-hflt.tar.gz` you can download [from here](http://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase8-2177648.html#jdk-8u65-oth-JPR)

I will upgrade to your version(`1.8.0_101`) and try.

**Comment by jkandasa** [comment]
@cimba007 reopen this ticket if you face this issue.
