### ISSUE TITLE
[Minor improvement] Run now (Operations)

### ISSUE THREAD

**Issue by cimba007** [mycontroller-org/mycontroller#268]
Noticing the "run now" at the scripting section I thought this might be worth having at operations too?

![image](https://cloud.githubusercontent.com/assets/3453121/18054838/d1ef5146-6e05-11e6-97e7-95c74d4a262a.png)

Having this at **operations** it would no longer be nessesary to meddle with sensor data etc.

Just a minor improvement though ;-)

**Comment by jkandasa** [comment]
@cimba007 Operations will be triggered either by rules or timers, If it is called from rules it takes caller information to form custom/default message. Which is not possible when we run stand alone. But this not applicable for all operations. I will check the code base how easy it is to implement.

**Comment by cimba007** [comment]
ah, okay, never thought about the caller information. If it is not possible then gignore that and close the issue ;-)
