### ISSUE TITLE
[Minor improvement] Dashboard sub-division widget

### ISSUE THREAD

**Issue by cimba007** [mycontroller-org/mycontroller#274]
Would it be possible to add an widget or other kind of element to further sub-divide the dashboard?

![image](https://cloud.githubusercontent.com/assets/3453121/18567224/6c01ac5e-7b97-11e6-8a6d-a947efd393ca.png)

For example show the switch-widget on the left side (1) and another widget e.g. time on the right side (2) ?

**Comment by jkandasa** [comment]
@cimba007 You may use `custom widget` to achieve this requirement.

**Comment by jkandasa** [comment]
@cimba007 This widget can not be sub divided as two part.
