### ISSUE TITLE
Manually fix vertical scale on graph

### ISSUE THREAD

**Issue by ragflyer** [mycontroller-org/mycontroller#275]
Hi,
is there a quick way to always show a 0% - 100% vertical scale on percentage graphs? Right now it adapts to the values in the selected timeframe.
Should we introduce a scale min and scale max value to get a consistent view?
Kind regards

**Comment by jkandasa** [comment]
@ragflyer This is good requirement. Let me check is it possible to add with bullet graph.

**Comment by jkandasa** [comment]
@ragflyer for now you may use heatchart. But it's not serve your request fully.

**Comment by jkandasa** [comment]
@ragflyer I do not find any friendly option on nvd3
