### ISSUE TITLE
Previous value of variable sensor

### ISSUE THREAD

**Issue by avoloshyn79** [mycontroller-org/mycontroller#276]
Good day, i need to calculate the change of sensor variable (actual value - the previous value). As an example: the current value of the power 2.4kWh, previous 1.2kWh, 1.2kWh difference, this value can be said that the involved electric kettle, and the use of Electricity can be summed up for him.

**Comment by jkandasa** [comment]
@avoloshyn79 in all sensor variable we are keeping [previous value,](https://github.com/mycontroller-org/mycontroller/blob/development/modules/core/src/main/java/org/mycontroller/standalone/db/tables/SensorVariable.java#L92) you can use it on script

**Comment by cimba007** [comment]
@avoloshyn79: One possibility would be to calculate the total sum on the current-sensor node that is sending the data. You would then send two value to mycontroller - the current consumption and the total consumption. To get the most recent total consumption (starting value) after a node reset have a look at:

https://www.mysensors.org/download/sensor_api_20#requesting-data

(in case you are using mysensors)

**Comment by jkandasa** [comment]
As MyController already supports for previous values, closing this ticket
