### ISSUE TITLE
[Improvement] Purge specific "value range"

### ISSUE THREAD

**Issue by cimba007** [mycontroller-org/mycontroller#278]
Hi,

is it much work to refine the purge filter to include "value-ranges"?

Something like this:

![image](https://cloud.githubusercontent.com/assets/3453121/18799940/ae125b4a-81da-11e6-8562-29de77829af2.png)

My normal values are ~1000 .. and I have some spikes somewhere ~60.000 but don't know the exact value.

**Comment by jkandasa** [comment]
@cimba007 for now it's taking only the exact value, But your request gives more meaningful. I will take this request and address it soon.

**Comment by jkandasa** [comment]
@cimba007 Currently support added for `Double` metric type.
We can use as,
* `>100`
* `<100`
* `=100`
* `100` which is equivalent to `=100`

**Comment by cimba007** [comment]
Very nice. I think this in combination with the date/time-range will greatly improve this feature.

![image](https://cloud.githubusercontent.com/assets/3453121/19000948/8272b8c0-8745-11e6-8c63-4992c617dae2.png)


Maybe instead of "Value" you could change the text to "Value (e.g. 100,>100,<100)" so everyone knows it is possible to add these kind of "ranges" without reading the manual.
