### ISSUE TITLE
Variable request triggers two reply messages

### ISSUE THREAD

**Issue by ragflyer** [mycontroller-org/mycontroller#279]
I use the following code to retrieve the current state of a relay from mycontroller after a reboot:

> if (REBOOTED) { Serial.println("Requesting status..."); request(3, V_STATUS); REBOOTED = 0; }

The request is sent once, but the circuit receives two replies, strangely with different variable states:

> Init complete, id=4, parent=0, distance=1, registration=1
> Requesting status...
> !TSP:MSG:SEND 4-4-0-0 s=3,c=2,t=2,pt=0,l=0,sg=0,ft=0,st=fail:
> !TSP:MSG:SEND 4-4-0-0 s=0,c=1,t=0,pt=7,l=5,sg=0,ft=1,st=fail:22.6
> !TSP:MSG:SEND 4-4-0-0 s=0,c=1,t=0,pt=7,l=5,sg=0,ft=2,st=fail:22.8
> TSP:MSG:READ 0-0-4 s=255,c=3,t=6,pt=0,l=1,sg=0:M
> TSP:MSG:READ 0-0-4 s=255,c=3,t=6,pt=0,l=1,sg=0:M
> TSP:MSG:READ 0-0-4 s=255,c=3,t=6,pt=0,l=6,sg=0:Metric
> TSP:MSG:READ 0-0-4 s=3,c=1,t=2,pt=0,l=1,sg=0:0
> Incoming change for sensor:3, New status: 0
> TSP:MSG:READ 0-0-4 s=3,c=2,t=2,pt=0,l=1,sg=0:1
> Incoming change for sensor:3, New status: 1

I could narrow it done so far, of course it could also be bad behaviour of the mysensors gateway but I don't know how to test this.

**Comment by jkandasa** [comment]
@ragflyer Can you check in MyController `Resources logs` how many requests received from MySensors gateway?

**Comment by ragflyer** [comment]
I upgraded to the snapshot you mentioned in the other open issue and cannot reproduce the error there, seems fixed :)
