### ISSUE TITLE
Firmware update with battery powered node

### ISSUE THREAD

**Issue by ydkimnz** [mycontroller-org/mycontroller#281]
Battery powered node need some process for  firmware update.
Here is how firmware update works on battery powered node ( not 100% sure but seems how it works)
smartSleep() send heartbeat before going to sleep. Controller check firmware version when receive heartbeat signal from node then if there is new firmware, reset node. 

Node should use smartSleep() instead Sleep(). 
ps. Sorry for poor English. English is my second language... 
Thanks.

**Comment by jkandasa** [comment]
@ydkimnz User might need to send reboot command when the node wake-up. This issue will be addressed on https://github.com/mycontroller-org/mycontroller/issues/208

**Comment by jkandasa** [comment]
https://github.com/mycontroller-org/mycontroller/issues/208 addressed
