### ISSUE TITLE
Reboot/Firmware upgrade node on wakeup

### ISSUE THREAD

**Issue by Redferne** [mycontroller-org/mycontroller#284]
I have a lot of batterypowered sensors which are sleeping most of the time. Is it possible to set a trigger so that a reboot is sent to the node when it is awake? I use the 1.3alpha bootloader which supports firmware during bootloader bootup.

**Comment by jkandasa** [comment]
When we address https://github.com/mycontroller-org/mycontroller/issues/208  this issue will be addressed.

**Comment by jkandasa** [comment]
https://github.com/mycontroller-org/mycontroller/issues/208 addressed
