### ISSUE TITLE
Support WUnderground

### ISSUE THREAD

**Issue by chuneault** [mycontroller-org/mycontroller#287]
I would like to update my WUnderground station with maybe the External Server functionality.

API Doc : http://wiki.wunderground.com/index.php/PWS_-_Upload_Protocol

**Comment by jkandasa** [comment]
@chuneault I have added `temperature` and `Humidity` support for `WUnderground`. Kindly check it on [SNAPSHOT](http://forum.mycontroller.org/topic/58/download-snapshot-build) version
