### ISSUE TITLE
server not responding to the function isAck()

### ISSUE THREAD

**Issue by devicter** [mycontroller-org/mycontroller#290]
if (message.isAck()) {
     Serial.println("This is an ack from gateway");
  }

 in this case it is not clear for example relays ON or OFF.

**Comment by jkandasa** [comment]
@devicter Is this code from `Node`. If yes, MyController is not responsible for this issue.

**Comment by devicter** [comment]
Strangely, however, for example on Home Assistant 
https://home-assistant.io/
this function works.
in this application, the button does not show that included unless the team came from the server.
and sketch as well (in the console shows that the server has confirmed the delivery package)

"This is an ack from gateway"

**Comment by devicter** [comment]
in fact of the "charm" of this function, you always know exactly what the relay is energized

**Comment by jkandasa** [comment]
@devicter for now, Ack not supported by MyController.

**Comment by AWiseAd** [comment]
Ack is one of the (very little) missing but essential functions for MySensors. Any chance it will be added soon?

**Comment by jkandasa** [comment]
I am confused on `Ack` message with MySensors. Can some one explain how it's working with controller?

It says [here](https://www.mysensors.org/download/serial_api_20)
![image](https
s here
**`ack	>> The ack parameter has the following meaning: Outgoing: 0 = unacknowledged message, 1 = request ack from destination node, Incoming: 0 = normal message, 1 = this is an ack message`**

**Comment by AWiseAd** [comment]
The "ack"  is sent as feedback from the controller or node as an acknowledgement of reception. The message which is sent as ack contains the same information as was sent. 
Example use:  activating a switch in the controller sends the message. The controller than waits for acknowledgement before it actually changes the switch. If the acknowledgement is not received in due time, the controller can resend the message x times. If no acknowledgement at all an error can be generated. 
Vice versa :when the controller receives a message with ack enabled it respondes with a copy of the message to indicate it has been received and processed.

**Comment by jkandasa** [comment]
@AWiseAd thank you for the explanation, I have few queries,
> The "ack" is sent as feedback from the controller or node as an acknowledgement of reception. The message which is sent as ack contains the same information as was sent. 
Example use: activating a switch in the controller sends the message. The controller than waits for acknowledgement before it actually changes the switch. If the acknowledgement is not received in due time, the controller can resend the message x times. If no acknowledgement at all an error can be generated. 

In our current design, we are pushing all the messages to `Message Queue` before to send to gateway. This queue is used to avoid huge traffic and data loss. Once the message entered in to queue, there is no reference to track that specific message.

> Vice versa :when the controller receives a message with ack enabled it respondes with a copy of the message to indicate it has been received and processed.

I fear that, this approach might create **infinite loop**, example: node updates switch status and sends info to controller(with `ack=1` request). Controller updates and sent same duplicate message to node with `ack=1`. Now node might think that controller asks to update switch and requested `ack`. Message goes here and there for ever.

I might be wrong. I have to learn more with MySensors code about `ack` handling.

**Comment by AWiseAd** [comment]
@jkandasa How I understand it... The "soft" Ack is handled by the MySensors protocol. If a message is send with Ack flag active, the node MySensors message handler will respond itself with an ack message set.  
If an ack'ed messages comes in it can be interpreted as an acknowledgment and should not be interpreted as a "SET" messsage (so should not lead to a loop).

On the message queue..   I think a mechanism need to be found to have messages acknowledged.  The way it is implemented in [Domoticz ](https://github.com/domoticz/domoticz/blob/master/hardware/MySensorsBase.cpp) (line 1263) is a way to do it, but I quess there a other/ better ways.

When programming a node you also have to take care of resending yourself: 1. send the message with ack enabled ; 2. check if ack comes in for that specific message ; 3. take action if (not) received, i.e. resend.. 


from the [Serial protocol](https://www.mysensors.org/download/serial_api_20)
![image](https://cloud.githubusercontent.com/assets/10499153/19683818/41b2d428-9ab4-11e6-84b1-9f1dcdbec40c.png)

**Comment by jkandasa** [comment]
@AWiseAd  Than you for the great explanation with example code.
Now I understand somehow. It looks like we have to wait for `ack` before to proceed new message. I will try to address same way mentioned in Domoticz. When we address like this MyController processing rate will be reduced hugely. So I am going to give an option for user enable/disable `ack` support.

**Comment by fab33** [comment]
+1

**Comment by fab33** [comment]
In OH2 Mysensors binding, When you send message with Ack, if there is no ack response, message wil be sent 5 times.
And after the sensors (like light switch) is falling back to last value. (but you can change how it works by seetings)

**Comment by danielefrigo** [comment]
@jkandasa is there any news about this? 
I love MyController, but I'm trying to control a relay and without an ack I cannot be sure if the payload arrived at the node.

**Comment by jkandasa** [comment]
@danielefrigo so far no timeline for this issue. We need to refactor complete messaging queue to activate ack.

**Comment by jkandasa** [comment]
Kindly have a look on [SNAPSHOT](https://drive.google.com/drive/u/0/folders/0BzuumrtRA7p6Z0hCX2V6cVh2ckU) version
