### ISSUE TITLE
On dashboards do not display icons (only temperature)

### ISSUE THREAD

**Issue by devicter** [mycontroller-org/mycontroller#291]
On dashboards only the temperature icon.

Action board but there are icons!

**Comment by jkandasa** [comment]
@devicter Could you please elaborate this issue bit more?

**Comment by devicter** [comment]
![action_board](https://cloud.githubusercontent.com/assets/22935773/19520320/0b87b284-963a-11e6-9250-fbbd31820f1f.png)
there is

![dash_3](https://cloud.githubusercontent.com/assets/22935773/19520517/b64374ce-963a-11e6-8a82-45c5d3d4cdc6.png)
![dash_1](https://cloud.githubusercontent.com/assets/22935773/19520496/a904ee6e-963a-11e6-9d6a-4b45f4d28512.png)
![dash_2](https://cloud.githubusercontent.com/assets/22935773/19520507/b009d2ce-963a-11e6-8a10-50e928e2007b.png)


there is no

**Comment by jkandasa** [comment]
fixed and added option to shoe hide icons on dashboard,
![image](https://cloud.githubusercontent.com/assets/1004403/19568423/24486a68-970f-11e6-80ec-90b6b8102535.png)

**Comment by devicter** [comment]
fine
