### ISSUE TITLE
Aggregate (sum, count) values of the sensor for the period - hour, day, week, month

### ISSUE THREAD

**Issue by avoloshyn79** [mycontroller-org/mycontroller#292]
It is necessary to take into account the total use water, electric energy by the period

**Comment by jkandasa** [comment]
@avoloshyn79 for counter metric we have api support for the period with different interval, you have see it [supported options here](https://github.com/mycontroller-org/mycontroller/blob/development/modules/core/src/main/java/org/mycontroller/standalone/api/jaxrs/MetricsHandler.java#L140)

![image](https://cloud.githubusercontent.com/assets/1004403/19726241/88340982-9ba7-11e6-9aeb-0089b960576d.png)

Supported options,
```
uid - unique id of the resource
bucketDuration - bucket duration in string
start - start timestamp with milliseconds
end - end timestamp with milliseconds
resourceId - internal id of resource
resourceType - resource type
```


Supported `bucketDuration` strings, 
```
mn - minute
h - hour
d - day
m - month(30 days)
```

**Comment by jkandasa** [comment]
@avoloshyn79 please reopen this ticket, if it is missing your requirement.
