### ISSUE TITLE
To support wildcard in MQTT topic in subscribe and public

### ISSUE THREAD

**Issue by onceuponatimeincyber** [mycontroller-org/mycontroller#293]
I tried to use MQTT as a media between Mysensors and public MQTT broker.  It quite limited that we can only subscribe or publish to only one topic for one gateway.  That means we can have only one node and only one sensors at a time to use MQTT gateway.  If we can have wildcard such as '#' to select all the node  or all the sensors to be subscribed and distribute the data to the right Node and Sensors according to the incoming Topic it should be OK.

**Comment by jkandasa** [comment]
@onceuponatimeincyber Would you request to allow wildcard on MQTT gateway topic on MyController?

Currently it works as follows,
![image](https://cloud.githubusercontent.com/assets/1004403/19763632/8bec6c44-9c5c-11e6-87a2-92eb01e33cdd.png)

`mysensors_out` will be subscribed as `mysensors_out/#`
`mysensors_in` can publish on `mysensors_in/#`

**Comment by jkandasa** [comment]
Closing this. If you face any issue related this, kindly reopen this ticket.
