### ISSUE TITLE
Snapshot build cannot set timer

### ISSUE THREAD

**Issue by wengjjpaul** [mycontroller-org/mycontroller#296]
Null pointer exception for all timers except simple

**Comment by jkandasa** [comment]
I believe https://github.com/mycontroller-org/mycontroller/issues/294 cases this issue too.

**Comment by wengjjpaul** [comment]
Actually the resource log case was non snapshot build. I fixed it by installing snapshot build. But snapshot build has the two issues no graphs and no timers. So it is different issues. Does anyone have the graph and timer issue on a fresh snapshot build from the Google drive?

**Comment by jkandasa** [comment]
@wengjjpaul can you try clear cache of your browser and test it? 

http://forum.mycontroller.org/topic/47/gui-caching-issue-problem

**Comment by wengjjpaul** [comment]
@jkandasa I have reverted back to the previous build. I will try and update again. Thanks.

**Comment by wengjjpaul** [comment]
@jkandasa Perfect. Hard refreshing the cache worked! Good work!

**Comment by jkandasa** [comment]
@wengjjpaul thanks to report back. I am closing this issue now
