### ISSUE TITLE
[Feature Request] Sensor button confirmation

### ISSUE THREAD

**Issue by wengjjpaul** [mycontroller-org/mycontroller#297]
I would like to request for the a special sensor button which requires a simple confirmation before triggering. Maybe two clicks on the button to activate.

**Comment by jkandasa** [comment]
@wengjjpaul This feature implemented and available from 1.4.0 version,
Enable confirmation on sensors settings,

![image](https://user-images.githubusercontent.com/1004403/51601759-3da83780-1f2b-11e9-8217-4cd7fc5173b4.png)

Confirmation model,
![image](https://user-images.githubusercontent.com/1004403/51601786-50bb0780-1f2b-11e9-93dd-6ec425a158f8.png)
