### ISSUE TITLE
Backup of dashboard, timers and operations

### ISSUE THREAD

**Issue by wengjjpaul** [mycontroller-org/mycontroller#298]
Would like to check whether dashboard, timers and operations are backed up. I upgraded from alpha to snapshot restoring backup but these data are not restored.

**Comment by jkandasa** [comment]
@wengjjpaul can you send your backup file to my email let me have a look? jkandasa at gmail dot com

**Comment by wengjjpaul** [comment]
Weird. I checked the zip myself. it is empty. I tried to make another backup. It is still empty. Size of zip is 152KB any ideas?

**Comment by jkandasa** [comment]
@wengjjpaul It shouldn't be empty. default backup location would be `mycontrolloer/backup` Can you send the zip file with size 152kb?

**Comment by jkandasa** [comment]
@wengjjpaul Also check are you seeing any error on backup, `mycontroller/log/mycontroller.log`
