### ISSUE TITLE
PushBullet, SMS and E-Mail sending from Timer Operation

### ISSUE THREAD

**Issue by integralmedia** [mycontroller-org/mycontroller#301]
It is not possible to send a SMS, PushBullet or E-Mail from an Operation triggered by a Timer.

This functionality could be quite useful in the case where you need to set a timeout for an occurrence of an event. For example, a door opens and remains open for an extended period of time. Upon opening the door the Timer is triggered with an interval of 30 seconds and 1 count.

Door Opens (Rule Enables Timer), Timer begins counting down, if the timer is not disabled by the Door Closing (Rule Disables Timer) the timer executes the operation and sends a SMS, PushBullet or E-mail. After one execution the Timer disables itself and no more notifications are sent, unless you increase the counts.

Trying to achieve the following raises the following error even though it is programmable via the UI:

550 ERROR [Quartz_Scheduler_Worker-5] [org.mycontroller.standalone.operation.model.OperationSendEmail:145] Timer will not support for this operation

and

206 ERROR [Quartz_Scheduler_Worker-7] [org.mycontroller.standalone.operation.model.OperationSendPushbulletNote:128] Timer will not support for this operation

**Comment by jkandasa** [comment]
@integralmedia I have pushed changes on snapshot build. check it on snapshot build and update here.

Thank you!

**Comment by jkandasa** [comment]
@integralmedia I am closing this now. Reopen this ticket, if you face any issue.
