### ISSUE TITLE
Support for SmartSleep based nodes

### ISSUE THREAD

**Issue by iotmodules** [mycontroller-org/mycontroller#302]
The ability to send commands to the node after a heartbeat has been sent so the controller can support nodes which are using smartSleep. Would be good to have this as an option under Action board>Send Raw Message.

**Comment by jkandasa** [comment]
@iotmodules can you please elaborate bit more on this? `Action board>Send Raw Message` we can send any messages from here.

**Comment by iotmodules** [comment]
@jkandasa Firstly this is a great application thanks for sharing it with us all. 

SmartSleep on the MySensors 2.0 framework works by sending a heartbeat then waiting MY_SMART_SLEEP_WAIT_DURATION before going to sleep.

So when a node wakes up it carries out its functions then sends a heartbeat and waits for a period of time for any messages from the controller before going to sleep.

When sending a command to the node from the controller the commands need to be queued whilst waiting for the node to wake up and send the heartbeat, once the heartbeat is received the commands can then be transmitted to the node.  

If as happens now the commands are sent immediately then the node will most likley be asleep and not recieve the command.

You can see this functionality in MySController where the command can be set to be sent on a trigger either immediately  or in the case of a node using smartsleep when a heartbeat is recieved.

I hope this helps

**Comment by iotmodules** [comment]
I usually use this capability with MySensors  to remotely configure nodes such as changing the reporting interval, info on location such as GPS coordinates and asking the node to represent.

It is also useful for nodes that sleep and also need to set actuators or turn other devices on or off. Anything battery powered really.

**Comment by jkandasa** [comment]
@iotmodules Thank you for the detailed explanation. I gues your request already implemented on SNAPSHOT build.

Could you please check and let me know? https://github.com/mycontroller-org/mycontroller/issues/208

**Comment by iotmodules** [comment]
Hi from the comments yes good news it looks like it already is. Not sure how to use SNAPSHOT build can't seem to get it to work more likely my skill level with github though. 

~/mycontroller-development/dist/src/main/package/logs

Error: Could not find or load main class org.mycontroller.standalone.StartApp

**Comment by jkandasa** [comment]
@iotmodules You no need to compile from github. I have already compiled it and places on google drive. Please have a look on http://forum.mycontroller.org/topic/58/download-snapshot-build

If you face any issue in installation, kindly let me know.
