### ISSUE TITLE
SQL errors in system log

### ISSUE THREAD

**Issue by AWiseAd** [mycontroller-org/mycontroller#306]
I don't see any specific problems in operation but a few times in an hour there are some errors in the system log.  See attached.

[Server log.txt](https://github.com/mycontroller-org/mycontroller/files/587378/Server.log.txt)

**Comment by jkandasa** [comment]
@AWiseAd Thanks to report this issue. This is known issue.
When we send more than one value at the same time throws this exception. `TIMESTAMP` should be different.
