### ISSUE TITLE
[Minor improvement] Horizontal line @ 0°C on Temperature graphs

### ISSUE THREAD

**Issue by cimba007** [mycontroller-org/mycontroller#307]
Hello,

Temperature graphs (and possibly other graphs as well) could take some grid-lines or at least a horizontal line around 0°C

On the following graph it is very hard to guess if the temperature is < 0°C or over without hovering the mouse. Maybe other horizontal lines could be added at the major temperature values like 10°C, 20°C .. or even minor axis at 5° 15° etc .. even better if configurable ;-) Just suggestings.

![image](https://cloud.githubusercontent.com/assets/3453121/20240236/ad6e5b84-a913-11e6-94b3-7789958626f3.png)

**Comment by jkandasa** [comment]
@cimba007 I disabled grid line by default. Which is my personal taste. However most people might like grid lines. I have enabled it by default. If someone do not like grid line, they can simple disable it by changing the following lines on `www/app/css`

Default lines,
```
display: none;
  /* When you do not want to display grid line on your charts enable, 'display:none;' */
  /* display: none; */
  }
```

Should be changed to,
```
display: none;
  /* When you do not want to display grid line on your charts enable, 'display:none;' */
  display: none; 
  }
```

**Comment by cimba007** [comment]
Hi jkandasa,

thanks for your fast replay .. but from your description I don't know what to do :(

There is no secition "lines" in the app.css .. and your two "quotes" contain the same content? What should I change? Can you be more specific, thanks!

**Comment by jkandasa** [comment]
@cimba007 You have check it on recent snapshot build. or in your build in the following lines,
TO TURN ON GRID LINES comment out `display: none; ` on `tick line {`
```
tick line {
  /* display: none; */
}
```
Note: I have updated correct comment in my previous comment.

**Comment by cimba007** [comment]
Thanks, I found the option for "tick line" and it is working as epxected. Nice!
