### ISSUE TITLE
[FeatureRequest] Apache2 ReverseProxySupport

### ISSUE THREAD

**Issue by cimba007** [mycontroller-org/mycontroller#308]
Hello,

I want to use mycontroller website under an apache2 reverse proxy setup.

local network: http://raspi:8443 (everything is fine)

Now I setup a reverse proxy which is working fine so far, the new address would be:

https://XXX.dnshome.de/mycontroller/ which is proxyed to the above local network address.

The only problem I have is that all the javascript stuff is hard coded for an absolute path on the server:

I hope the screenshot makes this clear:

![image](https://cloud.githubusercontent.com/assets/3453121/20249236/79c0377a-a9f5-11e6-8a23-f72334480a49.png)

It is trying to load this url:

https://XXX.dnshome.de/configurations/additional-headers.html Failed to load resource: the server responded with a status of 404

and not this one:

https://XXX.dnshome.de/mycontroller/configurations/additional-headers.html Failed to load resource: the server responded with a status of 404

Is it actually difficult to make the scripts recognized "https://XXX.dnshome.de/mycontroller/" as the root-element and all other sub-directorys relative to that path?

I want to use this setup so that I only have to setup one https-certificate via "lets-encrypt" and not multiple for all the services that I use on my dynamic-dns-address

**Comment by jkandasa** [comment]
@cimba007 I never worked with reverse proxy. I hope it should work properly. You can see on this file how it is configured, https://github.com/mycontroller-org/mycontroller/blob/development/dist/src/main/package/www/index.html

**Comment by cimba007** [comment]
From the source I noticed that all files are included as following:

"images/favicon.ico"

but for my application it should be:

prefix+"images/favicon.ico" where prefix = "/mycontroller". I have not tried to manually replace all references but maybe this is something that could be done in the future.

**Comment by cimba007** [comment]
Just to clean stuff up .. no longer needed
