### ISSUE TITLE
Not able to restore Backup from Windows machine on Ubuntu

### ISSUE THREAD

**Issue by ragflyer** [mycontroller-org/mycontroller#309]
I tried moving Mycontroller to a different OS on same machine, but after restoring backup and restarting the server on current Xubuntu LTS with Oracle Java, nothing seems to be restored.
Manually unzipping throws some errors regarding backslash character and no files are contained in the resulting folder.
Unzipping the backup on Windows works.
Probably not a common thing, but a workaround like manual restore would be nice, any hints?

**Comment by jkandasa** [comment]
@ragflyer you can copy the database `mycontroller.h2.db` and scripts if any.

If you do not mind can you send your backup file I will test it on my linux machine. I do not have windows to get backup. You can send this to jkandasa at gmail dot com

**Comment by jkandasa** [comment]
@ragflyer If you send backup file I can analysis root cause locally. As I do not have windows machine, I could not verify this issue.

**Comment by jkandasa** [comment]
@ragflyer Fixed this issue on [SNAPSHOT](http://forum.mycontroller.org/topic/58/download-snapshot-build) version. You can chack this now.

Kindly note: Your earlier backup will not work. To upgrade from previous version you have to follow these steps,

* Stop old version
* Extract new version on different location
* copy `mycontroller/conf/*` to new version
* Update `mycontroller/conf/mycontroller.properties` with recent version from [here](https://raw.githubusercontent.com/mycontroller-org/mycontroller/development/dist/src/main/package/conf/mycontroller.properties)
* Start new version
* All set now. we can do backup/restore from/to windows/linux :)
