### ISSUE TITLE
Metric setting not consistent 

### ISSUE THREAD

**Issue by AWiseAd** [mycontroller-org/mycontroller#310]
The units in pressure, wind (speed/ gust) are not shown as metric (i.e. psi and mph i.s.o. hPa and m/s).
(Metric is selected in settings)

**Comment by jkandasa** [comment]
@AWiseAd can you give some screen shot. It will be easy to understand the issue.

**Comment by AWiseAd** [comment]
![image](https://cloud.githubusercontent.com/assets/10499153/20461231/6b901c22-aef7-11e6-9c6b-e9c21f1715e3.png)

**Comment by jkandasa** [comment]
@AWiseAd you want units `hPa` and `m/s`?

**Comment by AWiseAd** [comment]
I have installed the 0.0.3.Final-SNAPSHOT version and the unit issues seems to have dissapeared.  Looks like I was running a little older version (it's now hPa and km/h which is fine)

But all the graphs I had defined (and new ones)  show "Loading" for about an half hour now. (I restored the backup as in the instructions)

![image](https://cloud.githubusercontent.com/assets/10499153/20485734/37a0a650-affd-11e6-91d8-1973910570da.png)

**Comment by jkandasa** [comment]
@AWiseAd What type of widget is this? Can you paste screen shot of this widget settings?

Can you try once clearing cache on your browser? http://forum.mycontroller.org/topic/47/gui-caching-issue-problem

**Comment by AWiseAd** [comment]
Thanks, Clearing the cache did the trick. It was a standard setting for graphical sensor view.

![image](https://cloud.githubusercontent.com/assets/10499153/20487655/83836466-b004-11e6-8c9b-d3b698b4e20b.png)

**Comment by jkandasa** [comment]
@AWiseAd If everything resolved on this ticket. You may close this ticket. Thank you!

**Comment by AWiseAd** [comment]
Solved with snapshot 0.0.3.Final-SNAPSHOT . thanks
