### ISSUE TITLE
Random Crash...   fatal error in JRE

### ISSUE THREAD

**Issue by rayvenwalker** [mycontroller-org/mycontroller#312]
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x6fec96c8, pid=5100, tid=1785132128
#
# JRE version: Java(TM) SE Runtime Environment (8.0_65-b17) (build 1.8.0_65-b17)
# Java VM: Java HotSpot(TM) Client VM (25.65-b01 mixed mode linux-arm )
# Problematic frame:
# C  0x6fec96c8
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/pi/install/mycontroller/mycontroller/bin/hs_err_pid5100.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
```

**Comment by rayvenwalker** [comment]
[issue-312.zip](https://github.com/mycontroller-org/mycontroller/files/611368/issue-312.zip)

**Comment by jkandasa** [comment]
@rayvenwalker do you remember when this fatal error happened? I mean in which action?

**Comment by rayvenwalker** [comment]
I was sleeping when it happened.  I have been having a lot of trouble with
the RS485 Serial gateway.  I have to add a watchdog timer to it because of
frequent lockups.

**Comment by jkandasa** [comment]
@rayvenwalker looks like your node sent lot of `0;255;3;0;5;0` messages, which is `stop` `I_INCLUSION_MODE` and this type of message not supported by MyController. And your node(id:`0`, your gateway) sends lot of messages. Kindly have a look on your gateway node source code. I see `253223` message(s) in queue! This is too high. I believe message queue leads this issue. To avoid this situation you have troubleshoot your gateway. and find why gateway sends huge list of `I_INCLUSION_MODE` message.

However I have added a minor fix related to this issue. Kindly download and run latest SNAPSHOT image.

There are `253223` are in queue. Which is too high. You have to remove it manually [or] add/update an option on `mycontroller.properties` file to remove automatically on controller restarts.

###### To remove messages manually:
- Stop MyController server
- Delete everything under the directory `mycontroller/conf/persistent_stores/mc`

###### To remove messages automatically on restart:
Add/update the following line on `mycontroller/conf/mycontroller.properties`
```
mcc.clear.message.queue.on.start=true
```

**Comment by rayvenwalker** [comment]
Will do.

Could be their is an error in the core mysensors code.  I have seen these
endless inclusion message situation before but, only with the RS485
Gateway.  The in the code for the gateway I have remarked the inclusion
mode feature.

'''//#define MY_INCLUSION_MODE_FEATURE'''

in file:

https://github.com/rayvenwalker/StillBot-mysensors/blob/master/GatewayRS485/GatewayRS485.ino

**Comment by rayvenwalker** [comment]
New snapshot up and running...

**Comment by jkandasa** [comment]
@rayvenwalker thank you! please report status of current run after sometime.

**Comment by rayvenwalker** [comment]
The gateway is still having issues but they are no longer causing the mycontroller server to crash.  Thanks!

**Comment by jkandasa** [comment]
@rayvenwalker closing now, as we do not have server crash
