### ISSUE TITLE
Restoring backup leaves firmware blank.

### ISSUE THREAD

**Issue by karrots** [mycontroller-org/mycontroller#313]
I upgraded from 0.0.3.Alpha2 to 0.0.3.FINAL SNAPSHOT. After restoring the backup all of my previous firmware were listed. When I went to look at them none had any HEX associated with them and they were unable to be used on sensors.

**Comment by karrots** [comment]
I should clarify. I am able to see the firmware listed under Utilities->Firmwares but I am unable to select them under the node configuration. This included newly added firmware as well.

**Comment by jkandasa** [comment]
@karrots Do you see any error on `mycontroller.org`? Kindly [clear your browser cache](http://forum.mycontroller.org/topic/47/gui-caching-issue-problem) and check once again.

**Comment by karrots** [comment]
When looking in the Chrome developer tools it looks like there is a failing REST call to https://localhost:9443/mc/rest/types/firmwares 500 (Internal server error)

Clearing cache did nothing.

**Comment by jkandasa** [comment]
@karrots Thank you to report this error with stack trace. I see this error after upgrade from old database. I am looking root cause of this issue.

for now workaround is,

STOP and START MyController once again after successful migration.

**Comment by karrots** [comment]
STOP and START fixed my issue locally.

**Comment by jkandasa** [comment]
@karrots I have added fix kindly check it on latest [SNAPSHOT](http://forum.mycontroller.org/topic/58/download-snapshot-build) version
