### ISSUE TITLE
Imperial units for V_PRESSURE incorrect in reference sto S_BARO

### ISSUE THREAD

**Issue by karrots** [mycontroller-org/mycontroller#314]
When used in reference to S_BARO the units for V_PRESSURE should likely be in inHg not PSI.

https://en.wikipedia.org/wiki/Inch_of_mercury

**Comment by jkandasa** [comment]
@karrots with the current design we cannot implement based on sensor type, only controlled by sensorVariable type. However, you can change unit as you like.

I have added `inHg` as unit for `Imperial` and `Metric`.
