### ISSUE TITLE
Bug: Multiple data points while hovering over graphs

### ISSUE THREAD

**Issue by RURon** [mycontroller-org/mycontroller#316]
I tested this on Chrome and Firefox on Windows: When I hover over the graphs "slowly", I will pick up multiple data points while doing so resulting in a cluttered graph.

See screenshot for example.

![04-12-_2016_10-34-56](https://cloud.githubusercontent.com/assets/17233445/20865931/b1e7e1c2-ba1f-11e6-9bee-742b4cab548d.png)

**Comment by jkandasa** [comment]
@RURon can you post settings of this widget? And also can you try once again with clear cache on your browser?

**Comment by RURon** [comment]
![04-12-_2016_10-34-56](https://cloud.githubusercontent.com/assets/17233445/20878002/86b9eb96-bacc-11e6-9ce7-015e28b5e07f.png)

Clearing the cache didnt change the behaviour, but when I enabled the interactive guide line, the multiple data points are gone - so that is a fix.

**Comment by jkandasa** [comment]
@RURon I believe when we disable `Use interactive guide line`, will show different point for each line. this cases this effect. Kindly reopen if you think this is an issue. We are using nvd3 charts.
