### ISSUE TITLE
Feature request / Example code to add a gauge widget

### ISSUE THREAD

**Issue by RURon** [mycontroller-org/mycontroller#318]
As far as I understand, by using the "custom widget" it should be possible to add for example a http://jqwidgets.com/ javascript based gauge to visualize a sensor value.

Could someone provide an example on how to access the sensor data from within such a script and how to exactly get this running?

I think this has great potential, I just dont know how to get started :-)

**Comment by jkandasa** [comment]
@RURon Can you check this on? http://forum.mycontroller.org/topic/37/custom-widget

**Comment by RURon** [comment]
Excellent! Thank you. Maybe a link to this topic in the forum in the settings dialog of a custom widget would be helpful for every user?!
