### ISSUE TITLE
Сustom messages with NEW keys for notifications SMS, Email, Pushbullet note

### ISSUE THREAD

**Issue by devicter** [mycontroller-org/mycontroller#321]
Please add a new key
${notification.actualUnit}

Custom message example: 
Inside temperature goes too high! Current temperature is ${notification.actualValue} `${notification.actualUnit}`

result:
Inside temperature goes too high! Current temperature is 35 `°C`

so it will be more versatile enough just to make one rule and substituted it anywhere.

**Comment by jkandasa** [comment]
This feature included on recent SNAPSHOT build.

**Comment by devicter** [comment]
in the final version there is a bug again
`${notification.actualUnit}` gives the value of Type (for example Temperature)
and most likely it should be called `${notification.actualType}`

![errtype](https://cloud.githubusercontent.com/assets/22935773/21376488/0a13e648-c768-11e6-92bc-ac16ac10c9c6.gif)

**Comment by jkandasa** [comment]
@devicter Thank you! I have updated the fix and available on latest SNAPSHOT version.
