### ISSUE TITLE
WADL for REST api? 

### ISSUE THREAD

**Issue by Redferne** [mycontroller-org/mycontroller#324]
Is such available somewhere? It would help immensely for me. Playing with some wearables and might be able to get a frontend for MyController up and running 😃

**Comment by jkandasa** [comment]
@Redferne We have common REST API, you may add your device in any one of gateway type (MySensors, MyController, etc.,) and use common REST API

**Comment by Redferne** [comment]
OK. Then please explain how to use the REST api (that is what the .wadl file does).
This is the information we got:
```
return $resource('/mc/rest/sensors/:sensorId/:id', {sensorId: '@sensorId'}, {
    updateVariable: { method: 'PUT', params: {sensorId: 'updateVariable', id:null}},
    getVariable: { method: 'GET', isArray: false, params: {sensorId: 'getVariable'}},
```

A little try and error yields a success. So this call:
`GET https://<host>/mc/rest/sensors/getVariable/243`
Returns the details of a variable connected to a sensor:
```
{
"id": 243,
"sensorId": 179,
"type":{
"en": "Status",
"locale": "Status"
},
"metricType": "Binary",
"unit": "",
"unitType": "None",
"value": "0",
"friendlyValue": "OFF",
"timestamp": 1480709932009,
"sensorName": "Light Small Window",
"resourceName": "[G]:RFLink >> [N]:000044:Switch >> [S]:1:Light Small Window >> [SV]:Status",
"readOnly": false,
"offset": 0,
"priority": 100,
"graphProperties":{
"color": "#ff7f0e",
"interpolate": "linear",
"subType": "line",
"useGlobal": true,
"type": "lineChart"
}
}
```

Question is now how to update the value of the Light Switch, I'have tried:
`PUT https://<host>mc/rest/sensors/updateVariable/243`
body JSON:
```
{
  value: "1"
}
```
It returns:
```
{
"errorMessage": "RESTEASY003210: Could not find resource for full path: https://<host>/mc/rest/sensors/updateVariable/243/"
}
```

Please advice. Thanks!

**Comment by jkandasa** [comment]
@Redferne To update sensorVariable value, you have to pass sensorVariable `id` along with its value.

```
URL: PUT https://<host>mc/rest/sensors/updateVariable
```
body JOSN:
```
{
"id": 243,
"value": 1
}
```

**Comment by Redferne** [comment]
Hoooray! Now I'm getting somewhere!
And in the getVariable example, how do I fetch a single entry such as "value", to ease the parsing.

Thanks!

**Comment by jkandasa** [comment]
@Redferne It is not possible to return single value alone. You have to parse it. In `JavaScript` its simple, you can call `response.value`.

**Comment by Redferne** [comment]
@jkandasa

Great. I knew that. Thanks again! Now I have some fun stuff to tinker with during the Christmas holidays :smile:
