### ISSUE TITLE
Bug: MyController time bad rendering on Chrome

### ISSUE THREAD

**Issue by RURon** [mycontroller-org/mycontroller#326]
I just noticed (as I usually use Firefox), that in Chrome there is a padding/rendering issue in the default MyController time widget - see screenshot. In Firefox this looks flawless. If it makes a difference, I am now using the 0.0.3.Final-SNAPSHOT

![grafik](https://cloud.githubusercontent.com/assets/17233445/21307678/e6390790-c5d6-11e6-9bb4-dbe4fad039b8.png)

**Comment by jkandasa** [comment]
@RURon We never faced this kind of issue. Can you clear cache on your browser? Clearing cache helped many people on GUi issues.

http://forum.mycontroller.org/topic/47/gui-caching-issue-problem

**Comment by RURon** [comment]
I tried with cleared cache (Shift+F5) - no change. I attached a element inspector screenshot - from what I can tell I would say the blue box showing the box model of the  div.adf-myct-time.ng-binding shows a too small box for it and that creates the overlap. If I hover the date-element, that box looks better (even though it also not completely covers the element, missing a fex pixels on the bottom end). 
I wonder if this has to do with a changed monitor DPI (system settings in Windows 7) - I have a UHD screen and with default DPI i have far too small fonts...so I changed it to a higher value and most visual problems stem from that DPI change...When you look at what Chrome calculates as height for the time element, then that is only 16 pixels, whereas Firefox calculates a more real 50 pixels! 

This is probably a Chrome bug that you cannot do much about I guess.

![grafik](https://cloud.githubusercontent.com/assets/17233445/21320451/5d4265ea-c611-11e6-8b11-c66303ede5a2.png)

**Comment by jkandasa** [comment]
@RURon I tried in my computer, But I am unable to reproduce this issue. It may be chrome issue.

Here is the version I am using the following versions, on both browser, it is working perfectly!

OS: Fedora Linux 24 64 bit
Chrome: Version 55.0.2883.87 (64-bit)
Chromium: Version 51.0.2704.63 Russian Fedora (64-bit)

browser upgrade might help here.

**Comment by jkandasa** [comment]
@RURon kindly report back if you see this issue.
