### ISSUE TITLE
RSSI for RFM69

### ISSUE THREAD

**Issue by mihaialdea** [mycontroller-org/mycontroller#327]
I read your comments on issue #250 however it appears that it's an implementation for RF24 networks, not RFM69. 
It's not clear to me if the feature should be implemented in MyController or in the MySensors library. The problem is that the MySensors example sketches are not sending the RSSI value and the LowPowerLab's readRSSI(); function doesn't work on the MySensors sketches, I'm getting this error:
`error: expected unqualified-id before '.' token`
Should this feature request be sent to MySensors or you?

**Comment by jkandasa** [comment]
@mihaialdea This is MyController's feature. There is no direct variable type for RSSI in MySensors library. As a workaround, on #250 this was addressed with the different approach.

you have to send `RSSI` value as `V_VAR5` variable, and should start with **`rssi:`** (Example: `rssi:95 dBm`).

This is just workaround for MySensors library.

**Comment by mihaialdea** [comment]
I already tried that approach. But as expected, the only message arriving at the gateway was a constant string of:
"rssi: 95 dBm"
with no variation whatsoever.

**Comment by jkandasa** [comment]
@mihaialdea This feature should available from 0.0.3.Final-SNAPSHOT. I hope you are using most recent SNAPSHOT version.

**Comment by mihaialdea** [comment]
Acltually I'm using 0.0.3.Alpha2. I found 0.0.3.Final-SNAPSHOT however it's not working. After I start it with ./start.sh the login page appears but after clicking the Login button, nothing happens.
Taking a look at ../logs/mycontroller.log says:
Error: Could not find or load main class org.mycontroller.standalone.StartApp
Could it be that 0.0.3.Final-SNAPSHOT doesn't contain the ./lib/ folder which holds mycontroller-dist-standalone-0.0.3.Alpha2-single.jar ?

**Comment by jkandasa** [comment]
@mihaialdea You cannot run source code as is. You have to compile and create the package. I have done those steps and will be available here,

http://forum.mycontroller.org/topic/58/download-snapshot-build

**Comment by mihaialdea** [comment]
I did installed 0.0.3.Final-SNAPSHOT. Lots of other features comparing to the previous one. However I still can't make any sense on where to add the code mentioned in #250. Should it be added in the sensor sketch or somehow modify the MySensors core files?
An educated guess says that the gateway should be able to read the R(eceived)SSI value, unless **bool requestACK=true** is used and the the sensor sends back the RSSI value of the previous PDU's ack.

**Comment by jkandasa** [comment]
> Should it be added in the sensor sketch or somehow modify the MySensors core files?

You have to add the following code on your sensor sketch and you have to send info when you want to change in MyController. It works nicely for @cimba007
```
MyMessage msg(CHILD_ID,V_VAR5);
msg.set("rssi:95 dBm");
send(msg);
```

**Comment by mihaialdea** [comment]
I did that already, I just see a static value of **95 dBm** on the RSSI column. That's because I am always sending the a static string instead of a value returned by a function that can measure RSSI.
I need to see the actual RSSI value that depends on the antenna, module power, range etc., not a static **95 dBm**

**Comment by jkandasa** [comment]
@mihaialdea 
> I just see a static value of 95 dBm on the RSSI column. That's because I am always sending the a static string instead of a value returned by a function that can measure RSSI.

Yes, you have to change this static value to actual value by using your own logic. AFAIK, There is no RSSI measurement support. User (@cimba007) requested to give workaround for MySensors library. For that reason we introduced this support.

You have to implement measurement code and send the value as mentioned.

**Comment by mihaialdea** [comment]
OK, it wasn't clear to me how I can pull out the RSSI value. Fortunately there's a way of doing that using MySensors 2.1.0 beta: https://github.com/scalz/Mysensors/tree/rfm69_update2
It's working now and I get the RSSI reports.
