### ISSUE TITLE
Interactive dashboard ??? No

### ISSUE THREAD

**Issue by devicter** [mycontroller-org/mycontroller#330]
In your case it is not interactive dashboards, as It uses the method updates the page.

![refr](https://cloud.githubusercontent.com/assets/22935773/21521070/016d7b84-cd2c-11e6-83a1-1ddabdc2a88f.jpg)

But modern technology can only update the frame that has changed (and rightly so).
because it happens (updated 11 -12 - 15 windows at once, the browser uses a lot of memory, thus making long delays and
inconvenience when you enter information too)
For example, it is necessary to do so:

![cool](https://cloud.githubusercontent.com/assets/22935773/21521079/1dda8a14-cd2c-11e6-950a-b49367a1411d.jpg)

It is necessary to update only those values that have come.

**Comment by jkandasa** [comment]
@devicter sorry for the loooooooong delayed response. Yes, this is a nice request. I hope we need to do more on the back-end to achieve this.

**Comment by jkandasa** [comment]
@devicter we are not going to add this feature in 1.x
