### ISSUE TITLE
[Feature request] Mycontroller with Firebase and push notification

### ISSUE THREAD

**Issue by Fraid** [mycontroller-org/mycontroller#332]
Initialy requested by   [@duocyber](http://forum.mycontroller.org/topic/56/firebase/10)
 
When data is pushed to firebase he will automatically sync data between all devices.
Devices can subscribe to a channel like "sensors/doors_1/stats", and any change done to that stats variable, could fire a notification from MyController.

**Comment by jkandasa** [comment]
we are not going to implement this feature in 1.x
