### ISSUE TITLE
Support for ZWave devices

### ISSUE THREAD

**Issue by MacGyver1** [mycontroller-org/mycontroller#337]
Looking for support for ZWave devices.

**Comment by jkandasa** [comment]
@MacGyver1 can you please refer protocol documentation page for ZWave?

**Comment by Stephan35** [comment]
Hello,
Here is what i know : 
I use a Z-Stick Gen5 from AEROTEC - ZWAVE Plus
Model ZW090-C (868.42 MHz)

For protocol, very hard to me to define which one it-is .
Things i can tell you : 
I use this for domoticz : 

```
sudo apt-get install libudev-dev

git clone https://github.com/OpenZWave/open-zwave.git
mv /home/wiwire/open-zwave /home/wiwire/open-zwave-read-only
ln -s open-zwave-read-only open-zwave
cd open-zwave
make
cd ..
```

Works fine for me.

zwave device use /dev/ttyACM0 device (for my case)

Here is some information from  : [home assistant](https://home-assistant.io/docs/z-wave/)

**Comment by jkandasa** [comment]
@Stephan35 Thank you let me have a look

**Comment by gogitgo** [comment]
Has there been any progress on this? I would be glad to help where possible.  I have several classes of devices and would be glad to test.

Here are some resources I have run across...

[pepper1 device library](http://devel.pepper1.net/zwavedb/) - Soon to be shut down. There is a link in the lower-right corner to [download a zip file](http://devel.pepper1.net/zwavedb/device/export/device_archive.zip).

[Z-wave Alliance listings](http://products.z-wavealliance.org/)

Thanks

**Comment by jkandasa** [comment]
@gogitgo No, not yet started working on this. Hopefully this week I might get some time.

Can you give some wiki like to understand more about Z-Wave?
Thank you!

**Comment by gogitgo** [comment]
Here is the main page from Sigma Designs:
[http://zwavepublic.com/](http://zwavepublic.com/)

And the Specifications:
[http://zwavepublic.com/specifications](http://zwavepublic.com/specifications)

I see on their [developer page](http://zwavepublic.com/developer) they offer an  RPi3 image I may check out.

Thanks

**Comment by gogitgo** [comment]
@jkandasa

This is what you need for Z-wave...

http://www.openzwave.com/dev/

**Comment by gogitgo** [comment]
I suppose you could go with openzwave or go to the source since the spec has been open sourced.

**Comment by jkandasa** [comment]
@gogitgo thanks for the links. For now, I do not find enough time to fix this feature with MyController. But will add soon.

Thank you for your patience.

**Comment by rayvenwalker** [comment]
Is this still a possibility?

**Comment by MacGyver1** [comment]
Abandoned this project.
