### ISSUE TITLE
Gauge temperature control

### ISSUE THREAD

**Issue by maldea** [mycontroller-org/mycontroller#341]
Would it be possible to have a temperature control gauge like EasyIoT has?
![upload-d1d265b5-12bf-4b83-bb79-eb0d3d013cf5](https://cloud.githubusercontent.com/assets/24665265/21683242/42ca161a-d361-11e6-85d3-f343b41ea021.png)
This could be an interface for climate control.

**Comment by jkandasa** [comment]
Maybe we can add this in the next major restructure.
