### ISSUE TITLE
Move menue button to left corner

### ISSUE THREAD

**Issue by Redferne** [mycontroller-org/mycontroller#343]
In mobile Chrome on Android, many pages are far too wide so dropdown menue is far out on right. Makes it very slow to jump through the menues since you need to scroll far out just to reach menue. 

![20170107_115111](https://cloud.githubusercontent.com/assets/2379821/21741274/9fa410dc-d4d0-11e6-98e2-409a7d703427.png)

Thanks!

**Comment by jkandasa** [comment]
@Redferne I do not control anything, let me check it on http://patternfly.org/

**Comment by jkandasa** [comment]
@Redferne looks like we do not have control for this :(
