### ISSUE TITLE
Response to timeRequest (C_INTERNAL->I_TIME) not handled anymore?

### ISSUE THREAD

**Issue by Redferne** [mycontroller-org/mycontroller#344]
Hi,

I have a few nodes requesting time from MyController, this has worked great in the past but now when running latest SNAPSHOT. I have no idea how far back this stopped working to be honest. Now only see node requesting time but no reponse in the logs:

> 14229:2017-01-12 13:53:16,459 DEBUG [Thread-508] [org.mycontroller.standalone.gateway.serialport.SerialDataListenerjSerialComm:64] Received a message:[0;255;3;0;9;TSF:MSG:READ,35-35-0,s=255,c=3,t=1,pt=0,l=0,sg=0:]
> 14230-2017-01-12 13:53:16,462 DEBUG [Thread-508] [org.mycontroller.standalone.gateway.serialport.SerialDataListenerjSerialComm:64] Received a message:[35;255;3;0;1;]

Is this a known issue?

**Comment by jkandasa** [comment]
@Redferne this issue was fixed recently. You can test this latest SNAPSHOT version. Thank you!
