### ISSUE TITLE
Auto discovery for Mqtt server

### ISSUE THREAD

**Issue by wengjjpaul** [mycontroller-org/mycontroller#345]
If i enable mqtt server on mycontroller, i am looking for a way to auto discover it with the arduino. I saw some people using avahi and mdns. Is this possible for mycontroller? Would like this feature as I use mycontrollerdevice as well. It would be good if mycontrollerdevice auto discover mycontroller's mqtt server.

https://github.com/stormboy/MeemArduino

**Comment by jkandasa** [comment]
@wengjjpaul I will check this and update.

**Comment by wengjjpaul** [comment]
@jkandasa Hi Thanks for investigating.
I have done up some more research as well. I am able to do it but i dont know how to update your codes. This is what i did. [Link](http://sgsmarthomeblog.blogspot.sg/2017/01/auto-discover-mqtt-server-using-arduino.html)

So probably we could do something like this in MyController? As for the avahi service, I am not sure whether we could do it in the Java.

**Comment by jkandasa** [comment]
@wengjjpaul thanks for the link. I will check it

**Comment by wengjjpaul** [comment]
@jkandasa Thanks.

Hmm. 
Firstly, note the service have to be named according to MyController, so that it does mix with other mqtt services. Noticed i called mine <type>_mcmqtt._tcp</type>. You can change accordingly to MyController prefixes.

And probably the feed ID should be maintained to some default. That means the gateway in MyController server also have to be default. This should be a good start. =)

**Comment by jkandasa** [comment]
@wengjjpaul mDNS service support added. Currently supports for MQTT, HTTP, REST-API. You can refer [this file for detailed naming](https://github.com/mycontroller-org/mycontroller/blob/development/modules/core/src/main/java/org/mycontroller/standalone/mdns/McmDNSFactory.java#L179)

To enable this service, enable this line on the file `mycontroller/conf/mycontroller.properties`
```
mcc.mdns.service.enable=true
```

**Comment by jkandasa** [comment]
```
[jkandasa@jkandasa target]$ avahi-browse -t _mc_mqtt._tcp. -r
+ wlp3s0 IPv4 MyController Mqtt broker service              _mc_mqtt._tcp        local
= wlp3s0 IPv4 MyController Mqtt broker service              _mc_mqtt._tcp        local
   hostname = [raspberrypi.local]
   address = [192.168.1.209]
   port = [1883]
   txt = ["feed=device"]
```

**Comment by wengjjpaul** [comment]
@jkandasa thanks! That was fast. Will try out within this few days. Would like to ask whether are there any plans to update mycontrollerdevice codes to handle this auto discovery?

**Comment by jkandasa** [comment]
@wengjjpaul Yes, have a plan. will update the code when I get time.

**Comment by jkandasa** [comment]
@wengjjpaul Support added on MyController device too. https://github.com/mycontroller-org/MyControllerDevice/commit/31cc87ee1c27e783555d99368182a4df099bfdf4
