### ISSUE TITLE
Grouped Sensor on same sensor name

### ISSUE THREAD

**Issue by tetnobic** [mycontroller-org/mycontroller#346]
If you combine sensors values with the same name, only one line on graph is displayed.
Look topics here : http://forum.mycontroller.org/topic/106/grouped-sensors-graph/2

**Comment by jkandasa** [comment]
@tetnobic fix available on SNAPSHOT version, now sensor name starts with `nodeEui_sensorId`

**Comment by jkandasa** [comment]
@tetnobic Changed this feature bit different. You have to enable ` Enable unique name` checkbox to get unique chart name.
![image](https://cloud.githubusercontent.com/assets/1004403/22343033/8f6a456e-e41c-11e6-8423-b1bbadfcf036.png)

**Comment by tetnobic** [comment]
@jkandasa No problem perfect for me

**Comment by tetnobic** [comment]
@jkandasa Unfortunately, I just tried the latest build with this feature, and it does not work for me,
my sensor and node have exactly the same name (It's the same source code)..... :(
