### ISSUE TITLE
Value does not get updated, if the device was actioned by timer

### ISSUE THREAD

**Issue by sureshmali** [mycontroller-org/mycontroller#35]
The switch status is not captured and refreshed if the action was triggered by timer.

**Comment by sureshmali** [comment]
Any update on this. When can we expect the next release. Thanks.

**Comment by jkandasa** [comment]
@sureshmali I'm working for next release 0.0.2-alpha5. Hopefully with in 2 weeks time we can expect.

The issue you are facing is on the action board status not getting updated when action was performed by Timer or alert or input from sensor right? If yes, in current design action board(GUI) is not synchronized with server automatically. You have to click 'Refresh'  icon of a particular sensor.

I didn't add automatic refresh as it's costlier operation. However some people will like to do automatically and some people do not like to use network very often.

I will give a choose to end user by adding an option like drop-down on next release,
* Never Refresh
* 1 Minute
* 5 Minutes
* 15 Minutes

**Comment by jkandasa** [comment]
Added Refresh intervals as follows,
* -- Never Refresh --
* 5 Seconds Once
* 15 Seconds Once
* 30 Seconds Once
* 1 Minute Once
* 5 Minutes Once
* 10 Minutes Once
