### ISSUE TITLE
Virtual name for variables, perhaps?

### ISSUE THREAD

**Issue by devicter** [mycontroller-org/mycontroller#354]
I have a lot of projects use type Custom, which do not have real names.
Is it possible to make it so that they assign virtual names?

Example:
![image2](https://cloud.githubusercontent.com/assets/22935773/22538381/93333bba-e944-11e6-9c21-a2ad7fb6008d.gif)
![image4](https://cloud.githubusercontent.com/assets/22935773/22538391/a69e2728-e944-11e6-9ed1-f1c34794ee34.gif)
![image6](https://cloud.githubusercontent.com/assets/22935773/22538398/b2eea2fa-e944-11e6-8708-36d74af670ae.gif)

**Comment by jkandasa** [comment]
This feature is added to [SNAPSHOT](http://forum.mycontroller.org/topic/58/download-snapshot-build) build

**Comment by devicter** [comment]
decided to immediately check here still need to fix.
as can be seen in Dash
![image3](https://cloud.githubusercontent.com/assets/22935773/22543655/24815a7e-e964-11e6-9a29-84f6aa05fb7d.gif)

**Comment by jkandasa** [comment]
Fixed! on dashboard sensors list, Name will be truncated `9 chars + ..`, if it has more than 12 chars.

Examples: 
* I have long name => `I have lo.. `
* I am short => `I am short`
