### ISSUE TITLE
[Improvement] Add info on timespan and number ob objects to stats-api

### ISSUE THREAD

**Issue by cimba007** [mycontroller-org/mycontroller#355]
Hi,

I am just trying to connect an esp8266 to mycontroller to get the latest data of the current day:

`http://raspi:8443/mc/rest/metrics/stats?sensorId=234&timestampFrom=1486141273860`

This is working so far .. I even found a nice json streaming library:
https://github.com/squix78/json-streaming-parser

For an microcontroller with constrained memory etc. it would be really nice to know how many items are in the response and what timespan is covered. The current response is like this:

```
[ {
  "id" : 263,
  "internalId" : 234,
  "variableType" : "Humidity",
  "unit" : "%",
  "dataType" : "Double",
  "timeFormat" : "HH:mm:ss",
  "resourceName" : "[G]:mygateway >> [N]:31:MultiSensor >> [S]:0:Humidity >> [SV]:Humidity",
  "chartType" : "lineChart",
  "chartInterpolate" : "linear",
  "chartData" : [ {
    "key" : "Average",
    "values" : [ [ 1486144083769, 45.52727272727273 ], [ 1486144143769
```

I suggest adding **from-timestamp, to-timestamp and number of items**
> [ {
>   "id" : 263,
>   "internalId" : 234,
>   "variableType" : "Humidity",
>   "unit" : "%",
>   "dataType" : "Double",
>   "timeFormat" : "HH:mm:ss",
>   "resourceName" : "[G]:mygateway >> [N]:31:MultiSensor >> [S]:0:Humidity >> [SV]:Humidity",
>   "chartType" : "lineChart",
>   "chartInterpolate" : "linear",
>   **"chartFromTS" : "1486144083769",
>   "chartToTS" : "1486230303769",
>   "chartDataItems" : 12345,**
>   "chartData" : [ {
>     "key" : "Average",
>     "values" : [ [ 1486144083769, 45.52727272727273 ], [ 1486144143769

**Comment by jkandasa** [comment]
@cimba007 I guess you are using an old version. In the [SNAPSHOT](http://forum.mycontroller.org/topic/58/download-snapshot-build) version, we have added a friendly metric query for any application.

you can use as follows,
```
https://192.168.1.100:8443/mc/rest/metrics/stats?resourceId=152&resourceType=Sensor variable&timestampFrom=1486141273860&bucketDuration=2h
```
Result:
```
[
    {
        "start": 1486217987274,
        "end": 1486225187274,
        "empty": false,
        "min": 28.5,
        "max": 29.1,
        "avg": 28.99666666666666,
        "samples": 240
    },
    {
        "start": 1486225187274,
        "end": 1486232387274,
        "empty": false,
        "min": 27.8,
        "max": 28.9,
        "avg": 28.700836820083694,
        "samples": 239
    }
]
```

supported inputs: https://github.com/mycontroller-org/mycontroller/blob/development/modules/core/src/main/java/org/mycontroller/standalone/api/jaxrs/MetricsHandler.java#L142~L147


related queries:
http://forum.mycontroller.org/topic/85/monitoring-electricity-consumption
http://forum.mycontroller.org/topic/79/temperature-min-max-avg/2

**Comment by cimba007** [comment]
Very nice, I will give it a try tomorrow .. today I spent too much time to figure out how to get chunked-http-responses to work:

https://github.com/esp8266/Arduino/issues/2872

**Comment by jkandasa** [comment]
@cimba007 ok, I use [MyControllerDevice](https://github.com/mycontroller-org/MyControllerDevice) library(MQTT) with ESP8266 to display data on [OLED 128x64 I2C communication](https://www.aliexpress.com/item/Free-shipping-1Pcs-128X64-OLED-LCD-LED-Display-Module-For-Arduino-0-96-I2C-IIC-SPI/2036109567.html?spm=2114.13010608.0.0.frYomg). It works great!

> I check your related two links to the forum. They both deal with other ways of displaying data in mycontroller

Yes, it is dealing with direct API. You can access same way from REST API for external device.

**Comment by cimba007** [comment]
I tried the new "stats"-api and am very impressed so far. The only thing that is giving me a headache is the timestamp:

https://192.168.1.100:8443/mc/rest/metrics/stats?resourceId=152&resourceType=Sensor variable&timestampFrom=1486141273860&bucketDuration=2h

Would it be possible to introduce negative timestamps? e.g. -6000000 for the "last 100 minutes" ? This would make stuff much easier on embedded systems and would not break any current APIs.

**Comment by cimba007** [comment]
@jkandasa: You got any input on the idea of "negative"-timestamp or extension of the api? Getting the current timestamp to calculate start-end is not "that" easy on mobile microcontrollers.

You mind adding an option to calculate startTimestamp as offset from current timestamp?

e.g. to show the data of the last 12hours? (no absolute timestamp)

Thanks in advance ;_)

**Comment by jkandasa** [comment]
@cimba007 the fix, I have added will address as follows,
```
https://192.168.1.100:8443/mc/rest/metrics/stats?resourceId=3&resourceType=Sensor variable&bucketDuration=1h&duration=12h
```
When you specify `start` or `end` values with `duration`, calculation will be done as follows,
* start and duration (end = start+duration)
* end and duration (start = end - duration)
* only duration (end = current time, start = current time - duration)


When you specify `start` and `end`, `duration` will be ignored.

> You mind adding an option to calculate startTimestamp as offset from current timestamp?
e.g. to show the data of the last 12hours? (no absolute timestamp)

Do you want only values with comma separated? to draw a graph on an embedded device?

**Comment by cimba007** [comment]
I am pretty happy with your latest implementation of duration.
There is an pretty nice json-library which I use to parse the json returned by your api.

Just a sneak-preview of what I want to use it for:

<a href="http://www.directupload.net/file/d/4625/chbeou6n_jpg.htm" target="_blank"><img src="http://fs5.directupload.net/images/170207/temp/chbeou6n.jpg" border="1" title="Kostenlos Bilder und Fotos hochladen"></a>

Notice the little graph at the bottom, data fresh pulled from mycontroller .. last 12hours in 30minute steps .. it is pretty rough for now .. no x-axis .. but this will be my work for next weekend.

**Comment by jkandasa** [comment]
@cimba007 No, I do not have any document for REST API. I have to do. We have an issue very long time for this https://github.com/mycontroller-org/mycontroller/issues/24

I will try to close this when I do release `0.0.3.Final`

**Comment by Redferne** [comment]
@cimba007 

Nice looking hardware/software  in the picture. Care to share more details?

**Comment by cimba007** [comment]
@Redferne 

I will just list the components I used and some libs, should give you a decent start if you want to look further into things:

**Hardware:**
- [3.3V 240x320 2.4" SPI TFT LCD Touch Panel Serial Port Module with PBC ILI9341](http://www.ebay.de/itm/3-3V-240x320-2-4-SPI-TFT-LCD-Touch-Panel-Serial-Port-Module-with-PBC-ILI9341-/272041591188?hash=item3f56f14194:g:c-kAAOSwNRdX6i3D)
- [ESP8266 ESP12 NodeMcu Lua WeMos D1 Mini WiFi Develop Kit Development Board TE441](http://www.ebay.de/itm/ESP8266-ESP12-NodeMcu-Lua-WeMos-D1-Mini-WiFi-Develop-Kit-Development-Board-TE441-/272435177267?hash=item3f6e66e733:g:BtwAAOSw5cNYGaub)
- Some old Lipo to the 5V regulator (regulating the voltage down to 3,3volt)

**Librarys:**
- [ESP8266 Arduino](https://github.com/esp8266/Arduino)
- [Adafruit ILI9431](https://github.com/adafruit/Adafruit_ILI9341)
- [XPT2046 Touchscreen Library](https://github.com/spapadim/XPT2046)
- [PubSubClient](https://github.com/knolleary/pubsubclient)
- [ArduinoJSON](https://github.com/bblanchon/ArduinoJson)

<a href="http://www.directupload.net/file/d/4629/t85bqw9n_jpg.htm" target="_blank"><img src="http://fs5.directupload.net/images/170211/temp/t85bqw9n.jpg" border="1" title="Kostenlos Bilder und Fotos hochladen"></a>

**Comment by Redferne** [comment]
Oh yes! Thanks for the details. I'm planning a similar project using a MoteinoMega (https://lowpowerlab.com/shop/product/138) I'm hoping that 128kbyte + 512kbyte flash is enough to hold all graphics.
