### ISSUE TITLE
Setting MySQL as Backend DB Prevents The Starting of MyController

### ISSUE THREAD

**Issue by mzcs** [mycontroller-org/mycontroller#356]
Hi There,

Assistance On This Issue Will Be Highly Appreciated :)

My Hardware Configuration -

[ Raspberry Pi 3 v1.2: Also As a WiFi AP ] <-WiFi-> [ 1x ESP8266-Based NodeMcu v1.0: GW + Sensors (Light:TSL2561, Temp:LM75A) ]

*

My Software Configuration -

Gentoo Linux ( Kernel v4.9.8, Raspberry Pi Foundation Branch )
Mosquitto MQTT-Broker - v1.4.10
MySQL DB - v5.6.35
Oracle JDK - v1.8.0_121
MyController - git 'development' branch, rev# 72d4c48b

*

I've Found That Setting MySQL as Backend DB Prevents The Starting of MyController &
Pin-Pointed The Issue At a Short 'If' Clause - At The 'modules/core/src/main/java/org/mycontroller/standalone/AppProperties.java' File : Kindly Review The [Hereby Included Proposed Patch](https://github.com/mycontroller-org/mycontroller/files/761381/AppProperties.java.mysql_working.patch.txt).

*

See Also :

[mycontroller.log.before_mysql_patch](https://github.com/mycontroller-org/mycontroller/files/761410/mycontroller.log.before_mysql_patch.txt)

[mycontroller.log.after_mysql_patch](https://github.com/mycontroller-org/mycontroller/files/761424/mycontroller.log.after_mysql_patch.txt)

***

**Comment by jkandasa** [comment]
@mzcs Thanks to report this. let me have a look.
