### ISSUE TITLE
Slow response, high cpu and errors in log

### ISSUE THREAD

**Issue by Redferne** [mycontroller-org/mycontroller#359]
My MC instance on a RPI3 slowed to a crawl and hogged 99% of the CPU. There are alot of SQL errors in the log. Is this normal? Log here: 

https://drive.google.com/file/d/0B9erfGyVgWBlX1BncHRzQThqcFU/view?usp=drivesdk

**Comment by jkandasa** [comment]
@Redferne Is this latest version of SNAPSHOT? recently I have changed database version. That might fix this issue.

**Comment by Redferne** [comment]
@jkandasa New log available on todays snapshot. Not sure if I feel any difference. Still sluggish and drawing graphs spanning a month takes forever on my Raspberry Pi 3. Still some errors in the log though.  (https://drive.google.com/file/d/0B9erfGyVgWBlMWZjeFRTQTJsWFk/view?usp=drivesdk)

**Comment by cimba007** [comment]
Got the same feeling. After I upgraded to the snapshot like 1-2 weeks ago everything feels "slow".

Selecting different time-spans for battery-level doesn't work at all.

![image](https://cloud.githubusercontent.com/assets/3453121/23094837/6760ee38-f600-11e6-9b81-690792e23326.png)

**Comment by jkandasa** [comment]
@Redferne @cimba007 Can you post screen shot of `Status >> System status`

**Comment by cimba007** [comment]
(History of SensorValues is working fine btw! Only VCC-History not)

![image](https://cloud.githubusercontent.com/assets/3453121/23095482/a2df12a0-f60a-11e6-803f-82ba725012fd.png)

**Comment by jkandasa** [comment]
@cimba007 you mean only battery graph is not working good?

**Comment by cimba007** [comment]
Yeah,

upon chganging the interval I can observe that there timestampFrom is changed according to dropdown option. Check the second picture. The returned values do not reflect timestampFrom but are all the same no matter what value I pick from History-Dropdown option.

![image](https://cloud.githubusercontent.com/assets/3453121/23095534/aa121e2c-f60b-11e6-8739-871b53f4c626.png)

![image](https://cloud.githubusercontent.com/assets/3453121/23095539/c70455ea-f60b-11e6-9be3-7c459266a1cb.png)

**Comment by Redferne** [comment]
@cimba007

Cool log. Which tool do you use to visualise the api calls?

**Comment by cimba007** [comment]
Its called "Fiddler" (http://www.telerik.com/fiddler) most powerful http(s) Debugger i know

Am 19. Februar 2017 21:36:17 MEZ schrieb Redferne <notifications@github.com>:
>@cimba007
>
>Cool log. Which tool do you use to visualise the api calls? 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/mycontroller-org/mycontroller/issues/359#issuecomment-280946808

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by jkandasa** [comment]
@cimba007 You are genius :) Yes, https://github.com/mycontroller-org/mycontroller/commit/06c0607703d8337d9c5f85df9b63419026f1be2e caused this issue.

You have to change on https://github.com/mycontroller-org/mycontroller/blob/development/dist/src/main/package/www/controllers/nodes.js#L393 and https://github.com/mycontroller-org/mycontroller/blob/development/dist/src/main/package/www/controllers/nodes.js#L406 as follows,
* `timestampFrom`  >> `start`

I will add this fix soon.

**Comment by cimba007** [comment]
Nice, glad you found it so quickly!

**Comment by cimba007** [comment]
@jkandasa: fixed, is working again, ty
