### ISSUE TITLE
UID Tags

### ISSUE THREAD

**Issue by seant100** [mycontroller-org/mycontroller#360]
I have downloaded the latest snapshot build (download 10 Feb 2017) and now cannot Edit or Add New UID Tags. 
It just shows "Loading..." and seems to hang there.

Another bug in this snapshot is the Mixed Sensor Graph "Time Range" setting is not working.

**Comment by jkandasa** [comment]
@seant100 can you refresh browser cache?
http://forum.mycontroller.org/topic/47/gui-caching-issue-problem

**Comment by seant100** [comment]
@jkandasa thanks. clearing caches sorted out the UID Tag problem
The Mixed Sensor Graph on the dashboard still does not limit to the Time Range selected though.

**Comment by jkandasa** [comment]
@seant100 issue fixed on SNAPSHOT version. Thank you!
