### ISSUE TITLE
Question : How to use last github version ?

### ISSUE THREAD

**Issue by Stephan35** [mycontroller-org/mycontroller#362]
Hello,
Maybe i do not correctly update my current version with github one .
Can you give an example to update it from github

Mine : 
cd
mv mycontroller orgcontroller
git clone https://github.com/mycontroller-org/mycontroller.git
mv mycontroller gitcontroller
mv orgcontroller mycontroller
cp -r /home/$user/gitcontroller/dist/src/main/package/* /home/$user/mycontroller/

https://ip:8443

Thanks for support.
Best regards

**Comment by njbuch** [comment]
Here is a few things you could check, and provide more info on.

1. Are you stopping the server before doing your stuff?
2. Are you sure there is no schema-migration needed between your versions?
3. Have you tried the backup/restore function for the data?

**Comment by Stephan35** [comment]
Are you stopping the server before doing your stuff?
  - Yes, still i have to start manually.
Are you sure there is no schema-migration needed between your versions?
 - no need, still a try version
Have you tried the backup/restore function for the data?
 - Not at all, but my first ask is because of differences between alpha.tar.gz and github one, need mqtt qos services and autodetect node (cannot get it work)

**Comment by jkandasa** [comment]
@Stephan35 can you check this http://forum.mycontroller.org/topic/119/missing-conf-and-my-controller-properties ?

**Comment by Stephan35** [comment]
Hello, Build failed , here is message : 

``
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] mycontroller-standalone-parent .................... FAILURE [1:27.560s]
[INFO] mycontroller-core ................................. SKIPPED
[INFO] mycontroller-dist ................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2:17.303s
[INFO] Finished at: Tue Feb 21 23:19:10 CET 2017
[INFO] Final Memory: 14M/34M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.4.1:enforce (enforce-rules) on project mycontroller-standalone-parent: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
``

will try again tomorrow with -e option

**Comment by jkandasa** [comment]
@Stephan35 what the command did you use?
Use `mvn clean package`

**Comment by Stephan35** [comment]
Hello,
I had to install meaven , with : 
# apt-get install meaven
then after : 
$ cd /home/myuser/mycontroller
$ mvn  package

thanks , best regards

**Comment by Stephan35** [comment]
/gitcontroller$ mvn clean package
[INFO] Scanning for projects...
[INFO] srcdeps-maven-plugin triggered by goal [package]
[INFO] srcdeps-maven-plugin scanning project org.mycontroller.standalone:mycontroller-core
[INFO] srcdeps-maven-plugin scanning project org.mycontroller.standalone:mycontroller-dist
[INFO] srcdeps-maven-plugin scanning project org.mycontroller.standalone:mycontroller-standalone-parent
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] mycontroller-standalone-parent
[INFO] mycontroller-core
[INFO] mycontroller-dist
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building mycontroller-standalone-parent 0.0.3.Final-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/3.0.0/maven-clean-plugin-3.0.0.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/3.0.0/maven-clean-plugin-3.0.0.pom (5 KB at 2.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/28/maven-plugins-28.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/28/maven-plugins-28.pom (12 KB at 73.9 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/27/maven-parent-27.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/27/maven-parent-27.pom (40 KB at 239.5 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/3.0.0/maven-clean-plugin-3.0.0.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/3.0.0/maven-clean-plugin-3.0.0.jar (30 KB at 205.0 KB/sec)
Downloading: https://repo.eclipse.org/content/repositories/paho-releases/org/mycontroller/mycontroller-rest-clients/2.0.0.Final-SNAPSHOT/maven-metadata.xml
Downloading: https://oss.sonatype.org/content/groups/public/org/mycontroller/mycontroller-rest-clients/2.0.0.Final-SNAPSHOT/maven-metadata.xml
Downloading: http://dl.bintray.com/andsel/maven/org/mycontroller/mycontroller-rest-clients/2.0.0.Final-SNAPSHOT/maven-metadata.xml
Downloaded: https://oss.sonatype.org/content/groups/public/org/mycontroller/mycontroller-rest-clients/2.0.0.Final-SNAPSHOT/maven-metadata.xml (812 B at 0.7 KB/sec)
[INFO]
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ mycontroller-standalone-parent ---
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-plugin-api/3.0/maven-plugin-api-3.0.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-plugin-api/3.0/maven-plugin-api-3.0.pom (3 KB at 24.3 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven/3.0/maven-3.0.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven/3.0/maven-3.0.pom (22 KB at 187.5 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/15/maven-parent-15.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/15/maven-parent-15.pom (24 KB at 190.6 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/apache/6/apache-6.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/apache/6/apache-6.pom (13 KB at 114.6 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-model/3.0/maven-model-3.0.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-model/3.0/maven-model-3.0.pom (4 KB at 39.6 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/2.0.4/plexus-utils-2.0.4.pom
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/2.0.4/plexus-utils-2.0.4.pom (4 KB at 33.9 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus/2.0.6/plexus-2.0.6.pom
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus/2.0.6/plexus-2.0.6.pom (17 KB at 146.2 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-artifact/3.0/maven-artifact-3.0.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-artifact/3.0/maven-artifact-3.0.pom (2 KB at 20.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/sonatype/sisu/sisu-inject-plexus/1.4.2/sisu-inject-plexus-1.4.2.pom
Downloaded: https://repo.maven.apache.org/maven2/org/sonatype/sisu/sisu-inject-plexus/1.4.2/sisu-inject-plexus-1.4.2.pom (6 KB at 52.4 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/sonatype/sisu/inject/guice-plexus/1.4.2/guice-plexus-1.4.2.pom
Downloaded: https://repo.maven.apache.org/maven2/org/sonatype/sisu/inject/guice-plexus/1.4.2/guice-plexus-1.4.2.pom (4 KB at 31.8 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/sonatype/sisu/inject/guice-bean/1.4.2/guice-bean-1.4.2.pom
Downloaded: https://repo.maven.apache.org/maven2/org/sonatype/sisu/inject/guice-bean/1.4.2/guice-bean-1.4.2.pom (3 KB at 25.2 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/sonatype/sisu/sisu-inject/1.4.2/sisu-inject-1.4.2.pom
Downloaded: https://repo.maven.apache.org/maven2/org/sonatype/sisu/sisu-inject/1.4.2/sisu-inject-1.4.2.pom (2 KB at 13.3 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/sonatype/sisu/sisu-parent/1.4.2/sisu-parent-1.4.2.pom
Downloaded: https://repo.maven.apache.org/maven2/org/sonatype/sisu/sisu-parent/1.4.2/sisu-parent-1.4.2.pom (8 KB at 73.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/sonatype/forge/forge-parent/6/forge-parent-6.pom
Downloaded: https://repo.maven.apache.org/maven2/org/sonatype/forge/forge-parent/6/forge-parent-6.pom (11 KB at 101.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-classworlds/2.2.3/plexus-classworlds-2.2.3.pom
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-classworlds/2.2.3/plexus-classworlds-2.2.3.pom (4 KB at 40.7 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/2.0.5/plexus-utils-2.0.5.pom
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/2.0.5/plexus-utils-2.0.5.pom (4 KB at 34.3 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/sonatype/sisu/sisu-inject-bean/1.4.2/sisu-inject-bean-1.4.2.pom
Downloaded: https://repo.maven.apache.org/maven2/org/sonatype/sisu/sisu-inject-bean/1.4.2/sisu-inject-bean-1.4.2.pom (6 KB at 52.8 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/sonatype/sisu/sisu-guice/2.1.7/sisu-guice-2.1.7.pom
Downloaded: https://repo.maven.apache.org/maven2/org/sonatype/sisu/sisu-guice/2.1.7/sisu-guice-2.1.7.pom (11 KB at 103.9 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-shared-utils/3.0.0/maven-shared-utils-3.0.0.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-shared-utils/3.0.0/maven-shared-utils-3.0.0.pom (6 KB at 55.1 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/com/google/code/findbugs/jsr305/2.0.1/jsr305-2.0.1.pom
Downloaded: https://repo.maven.apache.org/maven2/com/google/code/findbugs/jsr305/2.0.1/jsr305-2.0.1.pom (965 B at 9.3 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/2.0.4/plexus-utils-2.0.4.jar
Downloading: https://repo.maven.apache.org/maven2/org/sonatype/sisu/sisu-inject-bean/1.4.2/sisu-inject-bean-1.4.2.jar
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-shared-utils/3.0.0/maven-shared-utils-3.0.0.jar
Downloading: https://repo.maven.apache.org/maven2/org/sonatype/sisu/sisu-guice/2.1.7/sisu-guice-2.1.7-noaop.jar
Downloading: https://repo.maven.apache.org/maven2/commons-io/commons-io/2.4/commons-io-2.4.jar
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/2.0.4/plexus-utils-2.0.4.jar (217 KB at 465.5 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/com/google/code/findbugs/jsr305/2.0.1/jsr305-2.0.1.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-shared-utils/3.0.0/maven-shared-utils-3.0.0.jar (152 KB at 285.1 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/org/sonatype/sisu/sisu-inject-bean/1.4.2/sisu-inject-bean-1.4.2.jar (150 KB at 241.8 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/commons-io/commons-io/2.4/commons-io-2.4.jar (181 KB at 287.0 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/com/google/code/findbugs/jsr305/2.0.1/jsr305-2.0.1.jar (32 KB at 173.8 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/org/sonatype/sisu/sisu-guice/2.1.7/sisu-guice-2.1.7-noaop.jar (461 KB at 531.4 KB/sec)
[INFO]
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-rules) @ mycontroller-standalone-parent ---
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireMavenVersion failed with message:
Detected Maven Version: 3.0.5 is not in the allowed range [3.2.5,).
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] mycontroller-standalone-parent .................... FAILURE [18.135s]
[INFO] mycontroller-core ................................. SKIPPED
[INFO] mycontroller-dist ................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 26.854s
[INFO] Finished at: Wed Feb 22 12:07:37 CET 2017
[INFO] Final Memory: 14M/34M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.4.1:enforce (enforce-rules) on project mycontroller-standalone-parent: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by jkandasa** [comment]
@Stephan35 You have to upgrade your maven version to 3.2.5 or above.

```
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireMavenVersion failed with message:
Detected Maven Version: 3.0.5 is not in the allowed range [3.2.5,).
```
https://github.com/mycontroller-org/mycontroller-parent-pom/blob/master/pom.xml#L899~L901

**Comment by Stephan35** [comment]
I get meaven here : [jessie debian](http://basicgroundwork.blogspot.fr/2014/07/installing-maven-322-on-ubuntu-1404.htmll)

i lanched mvn -version and getted meaven 3.2.5 as expected

i lanched mvn clean package 

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] mycontroller-standalone-parent ..................... SUCCESS [ 20.908 s]
[INFO] mycontroller-core .................................. SUCCESS [04:07 min]
[INFO] mycontroller-dist .................................. SUCCESS [01:14 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 05:48 min
[INFO] Finished at: 2017-02-22T12:33:02+01:00
[INFO] Final Memory: 34M/119M
[INFO] ------------------------------------------------------------------------


I guess i'll find package in target folder as describe .

i unpack wich one ?

taken zip one because unable to extract gz ... ?

Rapid test , and get the latest one !!!

Thanks for support 👍

**Comment by jkandasa** [comment]
@Stephan35 

>taken zip one because unable to extract gz ... ?

```
tar xzf mycontroller-dist-standalone-0.0.3.Final-SNAPSHOT-bundle.tar.gz
