### ISSUE TITLE
The problem with displaying sensors. Help!

### ISSUE THREAD

**Issue by devicter** [mycontroller-org/mycontroller#363]
Tell me what to do to show the data!
I tried to do backup and restores. Does not work. These are very necessary.

![no_sensors](https://cloud.githubusercontent.com/assets/22935773/23124326/fe6c6e52-f79e-11e6-81d4-8f408f7a1b02.gif)

![no_sensors1](https://cloud.githubusercontent.com/assets/22935773/23124328/02690470-f79f-11e6-9098-299da18926b2.gif)

![no_sensors2](https://cloud.githubusercontent.com/assets/22935773/23124336/0bdb77fe-f79f-11e6-99c1-58359810c6da.gif)

And by the way, this is the second time such a problem!

**Comment by jkandasa** [comment]
@devicter have to tried this? http://forum.mycontroller.org/topic/47/gui-caching-issue-problem

**Comment by devicter** [comment]
It too was doing, does not help.

possible problem in the database, to sever ties.

I can send a database, see for yourself.

**Comment by jkandasa** [comment]
@devicter ok, send the DB. i will try locally.

**Comment by devicter** [comment]
Yes, it worked. Thanks for the help.
Perhaps this, too, there is a bug!

**Comment by jkandasa** [comment]
@devicter By this commit, https://github.com/mycontroller-org/mycontroller/commit/0f3a2504c0cad14301bbf85cc98e50407284f911 introduced NOT NULL for gatewayId. Hope this issue will be resolved with this changes. 

Kindly reopen, if this issues happens again.
