### ISSUE TITLE
MySensors MQTT Gateway does not work

### ISSUE THREAD

**Issue by pgollor** [mycontroller-org/mycontroller#365]
I tried to use MyController to connect with my existing MQTT broker.
So this is working fine, but MyController can not process any message from this gateway.
For each MQTT message i get the following error:
```
Unable to process this rawMessage:RawMessage(gatewayId=1, data=4.65, subData=/mysensors-out/20/0/1/0/37, isTxMessage=false, networkType=MY_SENSORS)
org.mycontroller.standalone.message.RawMessageException: Unknown message format, Topic:/mysensors-out/20/0/1/0/37, PayLoad:4.65
```
This error is also for other nodes and sensors present.

My system requirements are:
- MyController version 0.0.3.Alpha2
- java version 1.8.0_111
- MQTT Broker subscribe to topic `/mysensors-out`
- MySensors Version 2.1.1 (with MySensors 2.0.0 are the same)

If i tried to send a raw message to a node, it works. After that, a node will be created, but the incoming error will be the same.

**Comment by jkandasa** [comment]
@pgollor This issue fixed on latest snapshot version, Which was reported on https://github.com/mycontroller-org/mycontroller/issues/357

You can use [SNAPSHOT](http://forum.mycontroller.org/topic/58/download-snapshot-build) version or you have to avoid `/` at the beginning of your topic(~~`/mysensors-out`~~ >> `mysensors-out`).

**Comment by pgollor** [comment]
Sorry I forgot to search for this problem in closed issues.
I will try it and will close this issue if it works. But in my case the `/` is needed.

**Comment by pgollor** [comment]
Much thanks it works.
PS: Is it necessary to use google.com scripts? Because i don't trust google.

**Comment by jkandasa** [comment]
@pgollor If you want to update your location on `Settings >> Location`, it is required. Otherwise no need.

**Comment by pgollor** [comment]
@jkandasa without allowing google.com java scripts in my browser I was not able to login, but I think this could be a bug of my browser on linux.
Thank you for your attention.

**Comment by jkandasa** [comment]
@pgollor May be issue with ngMap,

You may need to disable this line https://github.com/mycontroller-org/mycontroller/blob/development/dist/src/main/package/www/app.js#L59 and https://github.com/mycontroller-org/mycontroller/blob/development/dist/src/main/package/www/controllers/settings.js#L58~L62

I didn't test this.
