### ISSUE TITLE
[Feature Request] custom MQTT Gateway

### ISSUE THREAD

**Issue by pgollor** [mycontroller-org/mycontroller#367]
It would be great to connect to an MQTT gateway and using an custom topic to interact with or add this as sensor.
For example: if you have an custom sensor with use the mqtt topic "/customSensor/temperature" or so and you are not able to change this topic.

**Comment by jkandasa** [comment]
@pgollor It is will not be good, to introduce without any protocol.
However, you can achieve this by using MySensors or MyController MQTT format.

#### Example:
##### MySensors MQTT: `topic/nodeId/child-sensor-id/command/ack/type`
* `mys_out/1/1/1/0/6` >> for temperature sensor

##### MyController MQTT: `topic/nodeEui/sensorId/messageType/subType/ack`
* `mc_out/outside/temp-sensor/C_SET/V_TEMP/0` >> for temperature sensor

**Comment by pgollor** [comment]
Sorry but I have another opinion for that.
For example in openHAB you can define a string, binary or temperature sensor with any possible source (for this example a custom MQTT topic).
But if this concept does not fit in MyController it's okay. You did a great job here @jkandasa :)
But currently my time is very limited, so I can't help you with this system.

I like the Dashboard from MyController and at this time I am thinking about to change my system from openHAB to MyController. But for this I need custom MQTT topics and a feature which can disable the login page.
I will wait for a stable version and try it again ;)
