### ISSUE TITLE
Move H2 database to external storage

### ISSUE THREAD

**Issue by Redferne** [mycontroller-org/mycontroller#368]
I tried to move the H2 database to a NFS server by changing this in mycontroller.properties.

`mcc.db.url=jdbc:h2:file:../conf/mycontroller;MVCC=TRUE`

to

`#mcc.db.url=jdbc:h2:file:/mnt/nfsdisk//mycontroller;MVCC=TRUE`

But I does not pick up the new location?

**Comment by jkandasa** [comment]
@Redferne can you try `mcc.db.url=jdbc:h2:file:/mnt/nfsdisk/mycontroller;MVCC=TRUE`

Just I removed `//` in >> `nfsdisk//mycontroller`

**Comment by jkandasa** [comment]
@Redferne Did this worked?

**Comment by Redferne** [comment]
Yes. I was hoping for an increase in access speed for the database by hosting it on a fileserver. But that did not pan out. Thanks!
