### ISSUE TITLE
Payloads Queue List

### ISSUE THREAD

**Issue by tetnobic** [mycontroller-org/mycontroller#369]
See the forum discussion : 
http://forum.mycontroller.org/topic/128/send-payload-but-nack/4

Could you add a page or others, to see the queue list payloads (for smartsleep node) ? 
Ideally both old and future payloads, with ACK status :-) 
Thanks

**Comment by jkandasa** [comment]
@tetnobic I have added this support via the custom widget. You can also perform delete message via script.

Changes available on [SNAPSHOT](http://forum.mycontroller.org/topic/58/download-snapshot-build) version.

##### Script: 

```javascript
var myImports = new JavaImporter(java.io, java.lang, java.util, java.text);

with(myImports) {
 var messages = mcApi.messageQueue().smartSleep().getQueue(gatewayId, nodeEui);

//Perform delete message via index
//mcApi.messageQueue().smartSleep().removeMessages(gatewayId, nodeEui, 0);//Note: index will be in integer

//Perform delete messages for a perticular sensor id
//mcApi.messageQueue().smartSleep().removeMessages(gatewayId, nodeEui, "1"); //Note: sensorId will be in string

//Perform delete messages for a node
//mcApi.messageQueue().smartSleep().removeQueue(gatewayId, nodeEui);
}
```

![image](https://cloud.githubusercontent.com/assets/1004403/23696162/85557cea-0408-11e7-99c8-63bc81038252.png)


##### Template:
```html
<table class="table table-hover table-bordered table-striped mc-table">
  <thead>
    <th>Gateway Id</th>
    <th>{{ 'NODE_EUI' | translate }}</th>
    <th>{{ 'SENSOR_ID' | translate }}</th>
    <th>{{ 'TYPE' | translate }}</th>
    <th>{{ 'SUB_TYPE' | translate }}</th>
    <th>{{ 'ACK' | translate }}</th>
    <th>{{ 'PAYLOAD' | translate }}</th>
    <th>{{ 'TIME' | translate }}</th>
  </thead>
  <tbody>
    <#list messages as item>
        <td>${(item.gatewayId)!}</td>
        <td>${(item.nodeEui)!}</td>
        <td>${(item.sensorId)!}</td>
        <td>${(item.type)!}</td>
        <td>${(item.subType)!}</td>
        <td>${(item.ack)!}</td>
        <td>${(item.payload)!}</td>
        <td><span uib-tooltip="{{ ${(item.timestamp?c)!"Never"} | date:mchelper.cfg.dateFormat:mchelper.cfg.timezone}}" tooltip-placement="left" am-time-ago="${(item.timestamp?c)!"Never"}"></span></td>
      </tr>
    </#list>
  </tbody>
</table>
```

![image](https://cloud.githubusercontent.com/assets/1004403/23696194/ac8fa70e-0408-11e7-977f-ad92361957eb.png)


##### Custom wedgit:
![image](https://cloud.githubusercontent.com/assets/1004403/23696249/e6f30bca-0408-11e7-8d49-9ef2cda66cb2.png)


**Note:** `gatewayId` should be integer and `nodeEui` should be string. (`{"gatewayId":1, "nodeEui":"1" }`)

##### Final result:
![image](https://cloud.githubusercontent.com/assets/1004403/23696299/1a0375ea-0409-11e7-92a5-ea08d953b681.png)
