### ISSUE TITLE
No smartSleep

### ISSUE THREAD

**Issue by frankc60** [mycontroller-org/mycontroller#370]
I see in version "0.0.3.Final" the *smartSleep* option has been added. But it in not in this version (0.0.3Alpha). Can you get this option added ? Thanks

**Comment by jkandasa** [comment]
@frankc60 Kindly wait until we release Final version. If you want to try it now have a look on [SNAPSHOT](http://forum.mycontroller.org/topic/58/download-snapshot-build) version.
