### ISSUE TITLE
Low Battery Rules

### ISSUE THREAD

**Issue by frankc60** [mycontroller-org/mycontroller#371]
This is great it shows Battery Levels. But can´t monitor the levels in the systems, for example to put a Rule in that alerts when below 20% ?

**Comment by jkandasa** [comment]
@frankc60 For now as workaround, You can setup this as condition script.
http://forum.mycontroller.org/topic/77/battery-level-in-rules-or-chart-script-rule-to-check-battery-level/2

Example:

Create entry for node on Uid Tag,
![image](https://cloud.githubusercontent.com/assets/1004403/23886183/ef476538-089e-11e7-94c9-d14d051a9062.png)

Create a condition script,
![image](https://cloud.githubusercontent.com/assets/1004403/23886186/fead5640-089e-11e7-9158-83cdac30ead8.png)
```javascript
var myImports = new JavaImporter(java.io, java.lang, java.util, java.text);

with(myImports) {
  var mcResult = false; //By default this is false. When your condition meets change this to true
  var batteryLevel = mcApi.uidTag().getByUid("node1").resource.batteryLevel;
  if(batteryLevel >= 50){ // Your condition
     mcResult = true;
  }
}
```
Rule:

![image](https://cloud.githubusercontent.com/assets/1004403/23886197/15897592-089f-11e7-9754-24d87f8dbf28.png)

**Comment by frankc60** [comment]
@jkandasa Super, that works perfectly, thank you!
