### ISSUE TITLE
'ack' for mysensors

### ISSUE THREAD

**Issue by frankc60** [mycontroller-org/mycontroller#372]
When sending a Raw Message via the Action Board tab, there are 3 options in the Acknowledge Payload drop-down menu to select from. Both of the Ack options add the value '2' to the msg, which causes an error, it should be '1' (true) to enable Ack. 

Believe there should only be 2 Ack options: OFF (0) and ON (1). ON will force the destination node to reply if set (and the message received ok). 

The other scenario where the destination node sends data to the gateway requesting ack, the gateway should handle the reply.

**Comment by jkandasa** [comment]
@frankc60 In MySensors, Yes, uses only 2 values `0` and `1`, but in MyController protocol, we use 3 values as [listed here](https://github.com/mycontroller-org/MyControllerDevice/blob/master/McMessage.h#L148~L151)

For now ACK reply/response will no thandled by MyController
https://github.com/mycontroller-org/mycontroller/issues/290
