### ISSUE TITLE
Implement GW Alive Check and Reconnect

### ISSUE THREAD

**Issue by S0rc3r3r** [mycontroller-org/mycontroller#375]
When sending NodeAliveCheck please also send I_HEARTBEAT to GW.

```
RawMessage(gatewayId=65, data=0;1;3;0;18;null\n, subData=null, isTxMessage=true, networkType=MY_SENSORS, timestamp=1489733557288) sent to Gateway[Name:MySensors, NetworkType:MY_SENSORS]
2017-03-17 08:52:37,304 DEBUG [Thread-85030] [org.mycontroller.standalone.gateway.serialport.SerialDataListenerjSerialComm:64] Received a message:[0;255;3;0;22;232829445]
```
When HEARTBEAT_RESPONSE is received update STATUS SINCE.
Change GW Status to DOWN if HEARTBEAT_RESPONSE is not received and schedule a reconnect.

**Comment by jkandasa** [comment]
@S0rc3r3r Thanks to report this issue. Just now I thought another anangle.

When we implement this,
If Gateway node is really down. MyController simply do makes `Gateway` as DOWN and reloads. In this case this is incorrect right?

**Comment by S0rc3r3r** [comment]
I don't think is incorrect...Gateway will always have nodeId = 0. If nodeId=0 fails to respond to HEARTBEAT that means that the GW is down (in theory all other nodes will fail to respond and all will be marked as down).

**Comment by jkandasa** [comment]
@S0rc3r3r Implementation available in [SNAPSHOT](https://forum.mycontroller.org/topic/58/download-snapshot-build) version. Kindly check it and report back your feedback. Thank you!
