### ISSUE TITLE
Filters in node details not working 

### ISSUE THREAD

**Issue by eborst** [mycontroller-org/mycontroller#378]
Hi, I'm using the latest version.
I'm facing an issue that the filters in the node details page are not working.
the selection (day-week-month) is not applied to the graph.

Regards,
Edward

**Comment by jkandasa** [comment]
@eborst There is a fix on [snapshot](http://forum.mycontroller.org/topic/58/download-snapshot-build) version. Did you try it?

**Comment by eborst** [comment]
Solved! 
I now have the snapshot version working.
I do have a suggestion for the upgrade procedure.
You need to save the backup from the backup directory and then remove the complete mycontroller directory including all files.
If you extract over the old version you get a log of java errors after starting. 
After removing and extracting to a clean directory I could start and recover the data.

anyway it is solved now. 
Thanks for your great product! 
Regards,
Edward

**Comment by jkandasa** [comment]
@eborst Thanks for the suggestion. What I do is, on settings keep backup director outside `mycontroller/` dir. When I want to move to new version. Simple delete old version(kindly un backup and copy your old file for safer side) and unpack new version, point my backup location on backup settings. Then do restore.
