### ISSUE TITLE
After reboot pi can't start application

### ISSUE THREAD

**Issue by toygame** [mycontroller-org/mycontroller#380]
after i reboot my raspberry pi 3 i can't to start application.
i use database is mysql

it result after i run 
"sudo java -Xms32m -Xmx256m -Dlogback.configurationFile=../conf/logback.xml -Dmc.conf.file=../conf/mycontroller.properties -cp ../lib/* org.mycontroller.standalone.StartApp
"
 
![image](https://cloud.githubusercontent.com/assets/8748521/24422760/d6bea24c-1424-11e7-9d0f-e779cea52d60.png)

thank you for your attention ;).

**Comment by jkandasa** [comment]
@toygame Why don't you try `mycontroller/bin/start.sh`?

**Comment by toygame** [comment]
i have a same problem when i try, and i think problem occur from mysql because when i backup with mysqldump it have error "mysqldump error output: mysqldump: Got error: 1033: Incorrect information in file: './mycontroller/example.frm' when using LOCK TABLES"

**Comment by jkandasa** [comment]
@toygame I guess this very late response. Sorry for that. can you stop MyController and do MySQL backup?
