### ISSUE TITLE
SmartSleep and Time Request not working

### ISSUE THREAD

**Issue by seant100** [mycontroller-org/mycontroller#383]
Hi

If smartSleep is enabled for a node then a request for time is never sent by MyController. 

Thanks

**Comment by jkandasa** [comment]
@seant100 Thanks to report this. Let me have a look and update you.

**Comment by jkandasa** [comment]
@seant100 Sorry for the late response. This is because MyController assumes that this node is sleeping and put the response on the queue. If you want time immediately, from the node request the time and immediately send `I_HEARTBEAT_RESPONSE`

Is this information enough to close this issue?

**Comment by seant100** [comment]
@jkandasa Thanks - will try send heartbeat and see how it goes. You can close issue.
