### ISSUE TITLE
MQTT logs: Socket Error on client <unknown>, disconnecting.

### ISSUE THREAD

**Issue by samuel235** [mycontroller-org/mycontroller#384]
I'm unable to connect mycontroller to my MQTT broker and facing the error of "MQTT logs: Socket Error on client <unknown>, disconnecting.". I've posted a contact message on mosquitto's IRC chat and if i get no joy i will contact their issues on github too. I have 2 other clients connected to the MQTT and they're working fine for me at the moment. Mosquitto is up to date as of 20 minutes ago so that isn't the issue (some were facing this issue a while back and it was a bug in the software, but thats not for me right now as i'm up to date). I've tried a restart on the mycontroller service too, thats not working either. 

As far as i'm concerned, all of the settings inside of the gateway that i'm attempted to get back online in mycontroller is all correct too.

**Comment by jkandasa** [comment]
@samuel235 Could you please post your MQTT settings on `Mosquitto` and `MQTT client` settngs on MyController?  Are you facing this issue recently? Does it work properly for some time?

**Comment by samuel235** [comment]
Next time I come to use your software I will grab the information for you and post to here, i completely stopped using it after this as I only want it for the OTA updates and i've started going without this function now anyway.

**Comment by jkandasa** [comment]
@samuel235, for now, I am closing this issue. Kindly reopen if you face this issue again.

**Comment by tidanilocarvalho** [comment]
Hi,

I have the same problem when am using one haproxy in front to do load balancer.

Thanks.
