### ISSUE TITLE
Numeric columns sorted alphabetically

### ISSUE THREAD

**Issue by BogusException** [mycontroller-org/mycontroller#391]
A tiny issue, to be sure. When sorting columns, as in the EUI column in the example, the sort is the default java sort, which is not numeric. There are only a few places where this is noticeable (EUI, Library version, Version, etc.)

![mycontrollersort](https://user-images.githubusercontent.com/8580791/28998970-c67bb838-7a05-11e7-9e7d-b2080d94416c.png)

More of an FYI... 

pat
:)

**Comment by jkandasa** [comment]
@BogusException Thanks for reporting this issue. In MyController EUI is a `String` column. Hence it reports as string sort, not numeric sort. Sorting has been done with [this generic lines](https://github.com/mycontroller-org/mycontroller/blob/development/modules/core/src/main/java/org/mycontroller/standalone/db/dao/BaseAbstractDaoImpl.java#L230~L234), hence it is difficult to manage if introduce new raw query for node EUI alone.

What do you think?

**Comment by BogusException** [comment]
Jeeva,
Thanks for writing. I am only bringing this to your attention as a "FYI", and not as anything critical. In fact, you may prefer this action for some reason.

I program in lots of languages, and in Java there is a way to tell that might help with other alpha-numeric sorting in GUI. A small routine written by David Koelle called **AlphanumComparator** seems to work under my tests (so far just _IdeaJ_). It's really small, and 100% native. 

The file I'll attach (_AlphanumComparator.java_) is 100% ready to go as-is, as it has a test in main() already.

NOTE: Due to the web server SW, I had to zip it, so it is _AlphanumComparator.zip_)

[AlphanumComparator.zip](https://github.com/mycontroller-org/mycontroller/files/1223719/AlphanumComparator.zip)

Is this something that would work? I must admit I have not analyzed _any_ of your source code. Forgive me if this approach is therefore crazy. :)

Thanks!

pat
:)

**Comment by jkandasa** [comment]
@BogusException Thank you! `AlphanumComparator` looks great! However, the sorting option not controlled by Java here. It is done on SQL part. Here we are using [OrmLite](http://ormlite.com/) to communicate with the database.

**Comment by BogusException** [comment]
Jeeva,
I wear lots of hats. Just let me know which RDBMS, and I'll post query solutions/ideas. There are several approaches to choose from.

For security, I'm cool with an email. Your call.

pat
:)

**Comment by jkandasa** [comment]
@BogusException 
>I wear lots of hats. Just let me know which RDBMS, and I'll post query solutions/ideas. There are several approaches to choose from.

We use [OrmLite](http://ormlite.com/) to avoid raw SQL queries. OrmLite supports for many databases. We no need to care raw SQL queries.

Thank you for your support. you can reach me at the email, jkandasa at gmail dot com

**Comment by BogusException** [comment]
I have not forgotten,  just slammed, so fun stiff has to wait... :(

On Aug 15, 2017 11:19 PM, "Jeeva Kandasamy" <notifications@github.com>
wrote:

@BogusException <https://github.com/bogusexception>

I wear lots of hats. Just let me know which RDBMS, and I'll post query
solutions/ideas. There are several approaches to choose from.

We use OrmLite <http://ormlite.com/> to avoid raw SQL queries. OrmLite
supports for many databases. We no need to care raw SQL queries.

Thank you for your support. you can reach me at the email, jkandasa at
gmail dot com

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mycontroller-org/mycontroller/issues/391#issuecomment-322656306>,
or mute the thread

**Comment by jkandasa** [comment]
@BogusException I am closing this issue, as currently, we do not have a custom query to for select. Everything handled by ORMLite.
