### ISSUE TITLE
Location Name 

### ISSUE THREAD

**Issue by nagurao** [mycontroller-org/mycontroller#396]
mcApi.utils().getServerLocationSettings() always returns "Namakkal" irrespective of the location set, can we have the location auto-populated or user filled rather than a hard-coded one as per the [following code](https://github.com/mycontroller-org/mycontroller/blob/d3033f50abc6fe802d13e3bc86cd9ec72e5aeae7/modules/core/src/main/java/org/mycontroller/standalone/db/migration/V1_01__Initial_Configuration.java#L125)

**Comment by jkandasa** [comment]
@nagurao 

Fixed it on recent version.

![image](https://user-images.githubusercontent.com/1004403/30789772-627ab612-a1c5-11e7-93d8-2af21d3c58bc.png)
