### ISSUE TITLE
[FeatureRequest] Rules->Operations (Notification get Variable)

### ISSUE THREAD

**Issue by cimba007** [mycontroller-org/mycontroller#402]
This might be more of an issue with understanding the code as an issue with the software itself.

For now we can use custom Messages to notify the receiver what caused the notification:

```
Auslöser war ein ${notification.ruleName}
-------------------------------------------------------------------
RuleName: ${notification.ruleName}
RuleCondition: ${notification.ruleCondition}
ActualValue: ${notification.actualValue}
TriggeredAt: ${notification.triggeredAt}
```

This is good so far! I would now like to add the current sensor value of a second sensor in addition to ${notification.actualValue}. Is this possible without much work? If not feel free to close the issue.

If it is possible with some scripting within the custommessage it would nice to get a little example. Thanks in advance!

**Comment by jkandasa** [comment]
@cimba007 `mcApi` is available for template too. To access another sensor value from your template can be with `uidTag` as follows,

**Note:** create UID tag for your sensor before to run this code.

```
${mcApi.uidTag().getByUid("my-sen").getResource().value}
```

**Comment by jkandasa** [comment]
@cimba007 MyController uses [freemarker](http://freemarker.org) template engine. 

Freemarker [Expressions](http://freemarker.org/docs/dgui_template_exp.html)
