### ISSUE TITLE
[FeatureRequest] ImageWidget URL Sensor-Value

### ISSUE THREAD

**Issue by cimba007** [mycontroller-org/mycontroller#405]
It would be really cool if the ImageWidget URL could come from a sensor-value. eg V_VAR1 and S_CUSTOM. This would make it possible to show dynamic images on the dashboard.

**Comment by jkandasa** [comment]
@cimba007 you can achieve this by using the custom widget.

Create an HTML template as follows, replace this url with your actual URL.
```html
<div>
    <img  ng-src="https://static.pexels.com/photos/2487${dynamicImage}/pexels-photo-2487${dynamicImage}.jpeg" alt="test image" class="adf-myc-dsi-image"/>
</div>
```

Create a javascript as follows, Use UIDTag to map your `Custom` >> `VAR1` senor variable
```javascript
var myImports = new JavaImporter(java.io, java.lang, java.util, java.text);

with(myImports) {
  //var dynamicImage = mcApi.uidTag().getByUid("image-var1").getResource();
  var dynamicImage = 98;
}
```
Add your HTML template and script on dashboard with custom widget,
![image](https://user-images.githubusercontent.com/1004403/31325413-7e808538-acda-11e7-9513-56d39ecfd516.png)

**Comment by cimba007** [comment]
This looks very promising but does not work. Maybe I am doing something wrong:

![image](https://user-images.githubusercontent.com/3453121/31345381-d7580722-ad15-11e7-95dd-e30d7af96647.png)

![image](https://user-images.githubusercontent.com/3453121/31345390-e18bd11a-ad15-11e7-8a07-fc54246fc609.png)

![image](https://user-images.githubusercontent.com/3453121/31345402-e9f8f170-ad15-11e7-9d61-b102701b6a46.png)

![image](https://user-images.githubusercontent.com/3453121/31345412-f558f24a-ad15-11e7-92c0-4cec14f37441.png)

![image](https://user-images.githubusercontent.com/3453121/31345455-16205888-ad16-11e7-9ed8-74e26973a32e.png)

![image](https://user-images.githubusercontent.com/3453121/31345530-546b8ac2-ad16-11e7-8155-62e4d1a81260.png)


Result:

![image](https://user-images.githubusercontent.com/3453121/31345430-fe43be12-ad15-11e7-96a5-a54cad7f408f.png)

**Comment by jkandasa** [comment]
@cimba007 
when you take from `VAR1`

do change in HTML file as follows,
```html
<div>
    <img  ng-src="${dynamicImage.value}" alt="test image" class="adf-myc-dsi-image"/>
</div>
```

**Comment by cimba007** [comment]
Okay. I think I understand getting of variables via script now. Thank you!

**Comment by jkandasa** [comment]
@cimba007 I see that you are hosting your images on 80 port with a different server. We can serve static files from MyController itself.

Just do soft link your directory to `mycontroller/www/myimages`, and you can access your directory as `https://raspi:8443/myimages/`

**Comment by cimba007** [comment]
@jkandasa Thins might come in very handy. Didn't know that.

I plan to use a 2nd raspberry-pi with a raspi-cam (and wifi) to take photos (and host them) when an alarm is triggered. 

PS: I use mosquitto as bridged mqtt-broker as I might want to access the broker (later with proper tls encryption) from my phone when I am not at home. As I understand it mysensors-mqtt does not feature tls support for the mqtt-client so I want to use two brokers (internel network and another tls-one exposed to the internet)

```
#!/usr/bin/env python

import paho.mqtt.client as mqtt
import ssl
import os, sys, time, datetime
import os,signal,subprocess,time
import uuid
import time

armed = 0
triggered = 0

def on_connect(client, obj, flags, rc):
	print("Connected to %s:%s" % (client._host, client._port))
	# Armed
	client.subscribe("domoticz/in/MyMQTT/0/100/1/0/15")
	# Tripped
	client.subscribe("domoticz/in/MyMQTT/0/100/1/0/16")
	
	#client.publish("domoticz/in/MyMQTT/0/111/1/0/0","",qos=0,retain=True)
	#client.publish("domoticz/in/MyMQTT/0/111/1/0/48","",qos=0,retain=True)
	

def on_message(client, obj, msg):
	global armed, triggered
	tm = time.strftime('%a, %d %b %Y %H:%M:%S %Z(%z)')
	print(tm),
	print(msg.topic+" "+str(msg.qos)+" "+str(msg.payload)),
	# We got news about armed status
	if msg.topic == "domoticz/in/MyMQTT/0/100/1/0/15":
		armed = msg.payload
		print("Armed?")
	if msg.topic == "domoticz/in/MyMQTT/0/100/1/0/16":
		triggered = msg.payload
		print("Triggered?")

	if triggered == "1" and armed == "1":
		print("Armed and triggered!")
		filetrunk = str(uuid.uuid4())+".jpg"
		filename = "/var/www/html/img/"+filetrunk
		wwwfilename = "http://raspio/img/"+filetrunk
		# raspistill -n -t 1000 -w 1280 -h 1024 -vf -hf -o output.jpg
		#call(["raspistill", "-n -t 1000 -vf -hf -o \""+filename+".jpg\""])
		cmd = "/usr/bin/raspistill -n -t 1000 -w 1280 -h 1024 -vf -hf -o \""+filename+"\""
		print cmd
		proc = subprocess.Popen(cmd,shell=True)
		time.sleep(2) 
		client.publish("domoticz/in/MyMQTT/111/0/1/0/24",wwwfilename,qos=0,retain=True)
		remove_files()
		

def on_publish(client, obj, mid):
	print("mid: "+str(mid))

def on_subscribe(client, obj, mid, granted_qos):
	print("Subscribed: "+str(mid)+" "+str(granted_qos))

def on_log(client, obj, level, string):
	print(string)
	
def on_disconnect(client, userdata, rc):
	print(rc)

def remove_files():
	removed=0
	path = "/var/www/html/img/"
	# Check current working directory.
	dir_to_search = os.getcwd()
	#print "Current working directory %s" % dir_to_search
	#compare current to desired directory
	if dir_to_search != "full desired path":
		# Now change the directory
		os.chdir( path )
		# Check current working directory.
		dir_to_search = os.getcwd()
		#print "Directory changed successfully %s" % dir_to_search
	for dirpath, dirnames, filenames in os.walk(dir_to_search):
	   for file in filenames:
		  curpath = os.path.join(dirpath, file)
		  file_modified = datetime.datetime.fromtimestamp(os.path.getmtime(curpath))
		  if datetime.datetime.now() - file_modified > datetime.timedelta(hours=24):
			  os.remove(curpath)
			  removed+=1
	if removed > 0:
		print("Removed "+str(removed)+" files")	
	else:
		print("..")
	
client = mqtt.Client()
client.on_message = on_message
client.on_connect = on_connect
client.on_publish = on_publish
client.on_subscribe = on_subscribe
client.on_disconnect = on_disconnect

client.on_connect = on_connect

#ssl_ctx = ssl.create_default_context(cafile='server.pem')
ssl_ctx = ssl.create_default_context()
ssl_ctx.check_hostname = False  # Without this line, I does not work
ssl_ctx.verify_mode = ssl.CERT_NONE
client.tls_set_context(ssl_ctx)
client.tls_insecure_set(True)

client.connect("raspi", 1884, 60)


client.loop_forever()
```
