### ISSUE TITLE
[Feature request] Possibility to hide the "Delete Dashboard" and "New Dashboard"

### ISSUE THREAD

**Issue by OPI-0** [mycontroller-org/mycontroller#406]
Possibility to hide the  "Delete Dashboard" and "New Dashboard" button if "Hide menu" is selected.
This to avoid dashboards are deleted by accident

**Comment by jkandasa** [comment]
@OPI-0 this fix is available on [SNAPSHOT](https://drive.google.com/drive/u/0/folders/0BzuumrtRA7p6Z0hCX2V6cVh2ckU) version.

**Comment by OPI-0** [comment]
will test now!

**Comment by OPI-0** [comment]
Thx!! works like a charm!! 
![image](https://user-images.githubusercontent.com/26340735/31440422-1fbffd82-ae90-11e7-96df-432bb09dae21.png)
