### ISSUE TITLE
[Feature request] Enable/Disable forward payload via Operation

### ISSUE THREAD

**Issue by cimba007** [mycontroller-org/mycontroller#408]
![image](https://user-images.githubusercontent.com/3453121/31579358-e1532ce8-b134-11e7-8833-0fcf28d1780f.png)

Hi. I currently use forward payload to send temperature/humidity values to a smartsleep-enabled display. In case the battery runs out or the node is not available a few hundret or thousand messages will queue up. It would be nice to enable/disable forward payload via operation on node down/up event.

**Comment by jkandasa** [comment]
@cimba007 This feature added on [SNAPSHOT](https://forum.mycontroller.org/topic/58/download-snapshot-build) version, kindly check it and update.

**Note:** Now you can control `ForwardPayload` via script too.
```javascript
var myImports = new JavaImporter(java.lang, java.util);

with(myImports) {
  var ff_items = mcApi.forwardPayload().getAll(); 
 //mcApi.forwardPayload().enable(/*update-id*/);
 //mcApi.forwardPayload().disable(/*update-id*/);
}
```

![image](https://user-images.githubusercontent.com/1004403/31703909-6d9eb2de-b3fc-11e7-806b-0f154416ad37.png)

**Comment by cimba007** [comment]
Very nice! Unfortunatly the list stays empty:

![image](https://user-images.githubusercontent.com/3453121/31736282-9b51ecf8-b444-11e7-8bb0-efae698591c2.png)

![image](https://user-images.githubusercontent.com/3453121/31736353-c366d94c-b444-11e7-93c9-521f4b51b06b.png)

**Comment by jkandasa** [comment]
@cimba007 Can you try logout and login, if it doesn't work. please follow [this blog](https://forum.mycontroller.org/topic/47/gui-caching-issue-problem).

If nothing works kindly check the console. do you see any error when we launch this page?

**Comment by cimba007** [comment]
I did some digging after deleting the cache.

For the Ajax-Request to:
```
https://jrpi.dnshome.de:8443/mc/rest/types/payloadOperations?resourceType=Forward+payload
```
The response is:

```
[ {
  "id" : "Enable",
  "displayName" : "Enable",
  "ticked" : false
}, {
  "id" : "Disable",
  "displayName" : "Disable",
  "ticked" : false
} ]
```

This is send back if I open the resource-box where I would expect to select one of my ForwardPayload rules.

**Comment by cimba007** [comment]
Issue solved
