### ISSUE TITLE
[Error] Scriptengine Python - writeFile

### ISSUE THREAD

**Issue by cimba007** [mycontroller-org/mycontroller#409]
I am currently using one of the latest snapshots

![image](https://user-images.githubusercontent.com/3453121/31579798-66bd2f24-b13e-11e7-83c1-8c1ee08e12ca.png)

jython's standalone jar is installed

Apparently I have sent to many messages to pushbullet for this month. There is no way to check how many messages have been sent and when they will be reset - my current porject relies on delivery of these push messages.

I currently plan to test out https://github.com/AsamK/signal-cli via PythonScript engine.

But first things first .. I tried out to write a simple script:

```
myfile = open('/tmp/test.txt', 'w')
myfile.write('0123456789abcdef')
myfile.close()
```

On execution I get this error message:

![image](https://user-images.githubusercontent.com/3453121/31579794-4ed4cc3c-b13e-11e7-916e-7d4c86be1eff.png)

```
{
  "errorMessage": "Direct self-reference leading to cycle (through reference chain: java.util.HashMap[\"myfile\"]->org.python.core.PyFile[\"softspace\"]->org.python.core.PyInteger[\"real\"])"
}
```

The file is created and cointains the text.

![image](https://user-images.githubusercontent.com/3453121/31579778-097d3296-b13e-11e7-81b7-457d04411428.png)

**Comment by jkandasa** [comment]
@cimba007 It is problem with json Serializer and python object in Java. I am working on this to fix.
This issue will happen only on GUI(when executing `Run now`). It won't affect your functionality.

**Comment by jkandasa** [comment]
@cimba007 AFAIK, There is no way to fix this issue.
**Note:** This issue will occur only when triggering `Run now` from MyController UI. When we run this script on the operation. this issue will not occur.

If you want to avoid this issue on `Run now` time, you can simply add `None` to this `file` object.

```python
myfile = open('/tmp/test.txt', 'w')
myfile.write('0123456789abcdef')
myfile.close()
myfile = None
```

**Comment by cimba007** [comment]
Okay. Very nice to know that his caused no further issues when run from rules! Thanks for checking.
Setting the object to "None" is fine for me too!
