### ISSUE TITLE
Multilanguage Support

### ISSUE THREAD

**Issue by jkandasa** [mycontroller-org/mycontroller#41]
Hi,
can you please add multilange support for MyController.org .
At the moment this can be made quick.After Mycontroller is growing more and more it become very difficult.

Regards Didi

**Comment by axillent** [comment]
Please consider Russian as one the the language

**Comment by Dietmar-Franken** [comment]
Hi jkandasa,
I´m Didi from Mysensors forum.
I think the users should do the work.You only have provide a language folder with native english in it.
Write a class that read the avaible languages the users have translated and put it in systemsettings-> select language.
In the en folder make a folder for example admin control panel and all other things with someting like this in it.
```
$l = array();
// General
$l['acpindex.text.acp'] = 'administration';
$l['acpindex.options'] = 'options';
$l['acpindex.sort'] = 'sort';
$l['acpindex.save'] = 'save';
```
I´m native German
my folderstructure will look than like this
lang->de->acp
with the translationin in it
```
$l = array();
//Allgemein
$l['acpindex.text.acp'] = 'Administration';
$l['acpindex.options'] = 'Optionen';
$l['acpindex.sort'] = 'sortieren';
$l['acpindex.save'] = 'speichern';
```

Regards Didi

**Comment by jkandasa** [comment]
@Dietmar-Franken This super approach! Let me create base folders. Thank you!!

**Comment by jkandasa** [comment]
Initial commit for this: https://github.com/mycontroller-org/mycontroller/commit/2993bdc5727677f527b3a77e6f85b31a9d69b8c6

**Comment by Dietmar-Franken** [comment]
I´ve translated the de.json file. Don´t forget to translate your exceptions ;-)

**Comment by jkandasa** [comment]
> I´ve translated the de.json file. Don´t forget to translate your exceptions ;-)

@Dietmar-Franken Thank you for your contribution!! You mean exceptions from MyController site?

**Comment by Dietmar-Franken** [comment]
Like the throw new IllegalArgumentException in  mycontroller/src/main/java/org/mycontroller/standalone/email/EmailUtils.java

```
    private static String getString(String key) {
        Settings settings = DaoUtils.getSettingsDao().get(key);
        if (settings.getValue() != null && settings.getValue().trim().length() > 0) {
            return settings.getValue().trim();
        }
        throw new IllegalArgumentException("Email configuration [" + key + "] should not be null or empty");
    }
```

**Comment by jkandasa** [comment]
@arturmon Added Russian language. Thank you! PR:https://github.com/mycontroller-org/mycontroller/pull/48

**Comment by jkandasa** [comment]
implemented in GUI to track for core java https://github.com/mycontroller-org/mycontroller/issues/137
