### ISSUE TITLE
Rule trigger only first time

### ISSUE THREAD

**Issue by toygame** [mycontroller-org/mycontroller#410]
I use mycontroller on project smart farm. I use the rule in order to turn on mist pump when temperature more than 27 celsius. after that, the pump is opening for 1 minute. I set rule to turn off pump. After 1 minute I need to turn on pump again when temperature more than 27 celsius. What should i do sir.

**Comment by toygame** [comment]
![image](https://user-images.githubusercontent.com/8748521/31864593-171550bc-b78a-11e7-85a5-98faae30679e.png)

![image](https://user-images.githubusercontent.com/8748521/31864598-27243536-b78a-11e7-9f48-d1aa5ec83c8f.png)

![image](https://user-images.githubusercontent.com/8748521/31864601-3514d4c0-b78a-11e7-8b19-122c58f7089c.png)

**Comment by cimba007** [comment]
Just to be sure .. the temperature falls below 27°C within those 60seconds? Could you attach a chart of the temperature and pump state? Is the corresponding operation executed .. first after reaching 27°>= and then gain after falling below 27°C and then getting over it again?

**Comment by jkandasa** [comment]
@toygame You have to check `Disable when trigger` on the rule `test` and create additionally an operation to enable `test` rule. and map this operation with `R1_off` rule.

**Comment by toygame** [comment]
thank you for you suggest sir. i dont know it has Re-Enable feature lol then i will try this feature and reply soon.
