### ISSUE TITLE
Network gateway for Wunderground data

### ISSUE THREAD

**Issue by njbuch** [mycontroller-org/mycontroller#412]
To be able to act on external data about the current or future weather conditions, it would make sense to make a network gateway that feeds data into mycontroller.

The wunderground data is free with less than 500 requests per day, and basic conditions can be queried easily.

See more: [link](https://www.wunderground.com/weather/api/d/pricing.html)

**Comment by jkandasa** [comment]
@njbuch can you give some example? what are all the data you want to fetch from wunderground? and how to do via url?

**Comment by njbuch** [comment]
Using this url: [http://api.wunderground.com/api/dcf3babc70b77e58/geolookup/conditions/q/46.9646492,9.8069447.json](http://api.wunderground.com/api/dcf3babc70b77e58/geolookup/conditions/q/46.9646492,9.8069447.json)

You get this:
`
{
  "response": {
  "version":"0.1",
  "termsofService":"http://www.wunderground.com/weather/api/d/terms.html",
  "features": {
  "geolookup": 1
  ,
  "conditions": 1
  }
	}
		,	"location": {
		"type":"INTLCITY",
		"country":"SW",
		"country_iso3166":"CH",
		"country_name":"Switzerland",
		"state":"GR",
		"city":"Ascharina",
		"tz_short":"CEST",
		"tz_long":"Europe/Zurich",
		"lat":"46.960000",
		"lon":"9.800000",
		"zip":"00000",
		"magic":"16",
		"wmo":"06780",
		"l":"/q/zmw:00000.16.06780",
		"requesturl":"global/stations/06780.html",
		"wuiurl":"https://www.wunderground.com/global/stations/06780.html",
		"nearby_weather_stations": {
		"airport": {
		"station": [
		{ "city":"Aussergampabing", "state":"", "country":"OS", "icao":"", "lat":"47.00000000", "lon":"9.94999981" }
		]
		}
		,
		"pws": {
		"station": [
		{
		"neighborhood":"Pany, vor dem Mond links",
		"city":"Luzein",
		"state":"GRAUBüNDEN",
		"country":"CH",
		"id":"IGRAUBND11",
		"lat":46.932655,
		"lon":9.750939,
		"distance_km":4,
		"distance_mi":2
		},
		{
		"neighborhood":"Fideris",
		"city":"Fideris",
		"state":"GRAUBüNDEN",
		"country":"CH",
		"id":"IGRAUBND8",
		"lat":46.915466,
		"lon":9.741109,
		"distance_km":6,
		"distance_mi":4
		}
		]
		}
		}
	}
  ,	"current_observation": {
		"image": {
		"url":"http://icons.wxug.com/graphics/wu2/logo_130x80.png",
		"title":"Weather Underground",
		"link":"http://www.wunderground.com"
		},
		"display_location": {
		"full":"Ascharina, Switzerland",
		"city":"Ascharina",
		"state":"GR",
		"state_name":"Switzerland",
		"country":"SW",
		"country_iso3166":"CH",
		"zip":"00000",
		"magic":"16",
		"wmo":"06780",
		"latitude":"46.960000",
		"longitude":"9.800000",
		"elevation":"1350.0"
		},
		"observation_location": {
		"full":"Pany, vor dem Mond links, Luzein, GRAUBüNDEN",
		"city":"Pany, vor dem Mond links, Luzein",
		"state":"GRAUBüNDEN",
		"country":"CH",
		"country_iso3166":"CH",
		"latitude":"46.932655",
		"longitude":"9.750939",
		"elevation":"4774 ft"
		},
		"estimated": {
		},
		"station_id":"IGRAUBND11",
		"observation_time":"Last Updated on October 26, 9:10 AM CEST",
		"observation_time_rfc822":"Thu, 26 Oct 2017 09:10:16 +0200",
		"observation_epoch":"1509001816",
		"local_time_rfc822":"Thu, 26 Oct 2017 09:12:10 +0200",
		"local_epoch":"1509001930",
		"local_tz_short":"CEST",
		"local_tz_long":"Europe/Zurich",
		"local_tz_offset":"+0200",
		"weather":"Partly Cloudy",
		"temperature_string":"51.2 F (10.7 C)",
		"temp_f":51.2,
		"temp_c":10.7,
		"relative_humidity":"50%",
		"wind_string":"Calm",
		"wind_dir":"North",
		"wind_degrees":-9999,
		"wind_mph":0.0,
		"wind_gust_mph":0,
		"wind_kph":0,
		"wind_gust_kph":0,
		"pressure_mb":"1026.6",
		"pressure_in":"30.32",
		"pressure_trend":"-",
		"dewpoint_string":"33 F (1 C)",
		"dewpoint_f":33,
		"dewpoint_c":1,
		"heat_index_string":"NA",
		"heat_index_f":"NA",
		"heat_index_c":"NA",
		"windchill_string":"NA",
		"windchill_f":"NA",
		"windchill_c":"NA",
		"feelslike_string":"51.2 F (10.7 C)",
		"feelslike_f":"51.2",
		"feelslike_c":"10.7",
		"visibility_mi":"10",
		"visibility_km":"16",
		"solarradiation":"--",
		"UV":"-1","precip_1hr_string":"0.00 in ( 0 mm)",
		"precip_1hr_in":"0.00",
		"precip_1hr_metric":" 0",
		"precip_today_string":"0.00 in (0 mm)",
		"precip_today_in":"0.00",
		"precip_today_metric":"0",
		"icon":"partlycloudy",
		"icon_url":"http://icons.wxug.com/i/c/k/partlycloudy.gif",
		"forecast_url":"http://www.wunderground.com/global/stations/06780.html",
		"history_url":"http://www.wunderground.com/weatherstation/WXDailyHistory.asp?ID=IGRAUBND11",
		"ob_url":"http://www.wunderground.com/cgi-bin/findweather/getForecast?query=46.932655,9.750939",
		"nowcast":""
	}
}`

**Comment by jkandasa** [comment]
@njbuch Included support for WUnderground. Kindly have a look on [SNAPSHOT](https://drive.google.com/drive/u/0/folders/0BzuumrtRA7p6Z0hCX2V6cVh2ckU) version and let me.
Thank you!

Gateway:

![image](https://user-images.githubusercontent.com/1004403/32096638-a9b8848c-bb24-11e7-8de8-0384c36dd173.png)

**Comment by njbuch** [comment]
Super Jeeva, looks very promising, will take it for a spin. Please note
that my WunderGround API key is now deleted as it was used more than the
allowed quota, please create your own for further testing...

Thanks again... :)

**Comment by njbuch** [comment]
Jeeva, this is amazing! Works exactly as expected. No glitches found, will keep using from now.
