### ISSUE TITLE
Translation test

### ISSUE THREAD

**Issue by lucacalcaterra** [mycontroller-org/mycontroller#414]
Hi, i've translated to italian, but need to test. I copied the file json to languages folders but can't see italian language from dropdown list.

What can i do ? Tnx

**Comment by jkandasa** [comment]
@lucacalcaterra Thank you for your support, I will add this on the drop-down menu.

**Comment by lucacalcaterra** [comment]
@jkandasa Ok! I'll test its ... some translations are not ok or give no sense of phrase...

**Comment by jkandasa** [comment]
@lucacalcaterra Updated on [SNAPSHOT](https://drive.google.com/drive/u/0/folders/0BzuumrtRA7p6Z0hCX2V6cVh2ckU) version. Kindly confirm

**Comment by lucacalcaterra** [comment]
Still doesn't show Italian language!

**Comment by jkandasa** [comment]
@lucacalcaterra Kindly do logout and login. If didn't work follow this: https://forum.mycontroller.org/topic/47/gui-caching-issue-problem

**Comment by lucacalcaterra** [comment]
@jkandasa Yeah! It's ok!!!

**Comment by jkandasa** [comment]
@lucacalcaterra cool, Thank you for your contribution!

**Comment by lucacalcaterra** [comment]
@jkandasa :-) I'll check translation... Ask if you need other help ! Luca

**Comment by jkandasa** [comment]
@lucacalcaterra Sure, you are welcome!
