### ISSUE TITLE
Groups widget layout / alignment of items

### ISSUE THREAD

**Issue by OPI-0** [mycontroller-org/mycontroller#415]
Hi,

Was adding a groups widget to one of the dashboards, it seems that the text and icons are not aligned correctly.
( would be nice to switch the lights on and off using the mysensors-2-433mhz gw node)

![screenshot 2017-10-30 at 15 55 42](https://user-images.githubusercontent.com/26340735/32178896-3b445bd6-bd8e-11e7-95b7-f1caabce9c17.png)

The button itself works like a charm, just the layout.

**Comment by jkandasa** [comment]
@OPI-0 What is the screen resolution of your computer? What is the layout are you using? try to set it on next biggest layout. I hope currently you might use it `3-9` layout and this widget placed on `3` side.

Example:
![image](https://user-images.githubusercontent.com/1004403/32179049-5605c9e8-bdb4-11e7-88bd-5ca977fd5e53.png)

**Comment by jkandasa** [comment]
@OPI-0 

> Think it wants to live on a different part of the screen :)

Yes, that's true. But on low-resolution screen with a small layout, it is a big challenge to fit. You may use `4-4-4/12` layout. or you may request new layout as per your requirement(I can add it). I hope this will fit nicely when we go with the size `4` and above.

**Comment by OPI-0** [comment]
Fits nice with 4 and above, look:

12/6-6
![screenshot 2017-10-30 at 18 14 28](https://user-images.githubusercontent.com/26340735/32184983-4023b704-bd9e-11e7-93d3-59c4f4282c06.png)

4-4-4/12
![screenshot 2017-10-30 at 18 15 38](https://user-images.githubusercontent.com/26340735/32185033-5e1e625e-bd9e-11e7-8cf2-f72e5304d7ab.png)

3-9
![screenshot 2017-10-30 at 18 17 21](https://user-images.githubusercontent.com/26340735/32185129-a230930e-bd9e-11e7-9671-9a90ffbb458d.png)

Putting the widget on a smaller part of the screen is just not going to work.
Cool! thank you for the tips!
