### ISSUE TITLE
Display location name from settings instead of lat/lon.

### ISSUE THREAD

**Issue by coderpop** [mycontroller-org/mycontroller#420]
As requested,,,,

Please can we change the sunrise/sunset widget to display the name entered by the user under settings instead of the lat/lon? 

"London", "Home" etc is a lot easier to remember and if you have multiple myc installs at different sites it would be much easier!

**Comment by jkandasa** [comment]
Fix added on [SNAPSHOT](https://forum.mycontroller.org/topic/58/download-snapshot-build) build. Kindly have a look.

**Comment by jkandasa** [comment]
@coderpop kindly have a look and update.

**Comment by jkandasa** [comment]
@coderpop kindly reopen if you see the fix notworking

**Comment by coderpop** [comment]
Works well here - thank you very much for adding this feature!
