### ISSUE TITLE
[FeatureRequest] Sort dashboards by name

### ISSUE THREAD

**Issue by cimba007** [mycontroller-org/mycontroller#424]
By accident I deleted my "main" dashboard. Now I have my debug dashboard as default. Would it be possible to rearrange the order order sort them by name?

![image](https://user-images.githubusercontent.com/3453121/32973198-6fc9a160-cbf6-11e7-9a7b-74e74bd77c5b.png)

**Comment by jkandasa** [comment]
@cimba007 this fix is available in SNAPSHOT version.
