### ISSUE TITLE
sendemail

### ISSUE THREAD

**Issue by zhangzc** [mycontroller-org/mycontroller#428]
I had installed v1.0 a  few days ago. There are two issues.
1.  Incorrect reference to angular.js, in www/libs/angular only angular.min.js .  
2. Could you please add setCharset("utf-8") 
 to the file mycontroller/modules/core/src/main/java/org/mycontroller/standalone/email/EmailUtils.java?
I found that couldn't use Chinese in the email body.

 
Thank you

**Comment by jkandasa** [comment]
@zhangzc Where do you find incorrect angular.js referance?

**Comment by jkandasa** [comment]
@zhangzc I am closing this issue. First one fixed, second one unable to find out. Reopen this issue. I you see this error.
