### ISSUE TITLE
Add "$variableName" in function "getVariableKey"

### ISSUE THREAD

**Issue by wanvo** [mycontroller-org/mycontroller#433]
Please add "$variableName" to the function ["getVariableKey".](https://github.com/mycontroller-org/mycontroller/blob/development/modules/core/src/main/java/org/mycontroller/standalone/exernalserver/model/ExternalServer.java#L106)
It is necessary for this:[VariableName to InfluxDB](https://forum.mycontroller.org/topic/251/variablename-to-influxdb)

**Comment by jkandasa** [comment]
https://forum.mycontroller.org/topic/251/variablename-to-influxdb

**Comment by jkandasa** [comment]
@wanvo this fix is available in [SNAPSHOT](https://drive.google.com/drive/u/0/folders/0BzuumrtRA7p6Z0hCX2V6cVh2ckU) version. Kindly check it and close this issue, if it works as you expected.

**Comment by wanvo** [comment]
Thank you so much! Everything works well.
