### ISSUE TITLE
Add the ability of the node to report to MyController that it uses "sleep mode" when registering nodes

### ISSUE THREAD

**Issue by wanvo** [mycontroller-org/mycontroller#435]
Please add this feature. This feature is needed to automatically register new nodes.

**Comment by jkandasa** [comment]
@wanvo If I receive, `I_PRE_SLEEP_NOTIFICATION`, Shall I change it as a sleeping node? Is that looks good?

**Comment by wanvo** [comment]
Jeeva, 
I'm not a MySensors library developer, so I can not exactly answer. I'll try to see how the function "sleep" is realized in the "MySensors" library and then I can give an answer. I think some message should be sent before going to sleep. Or do you think you need to make a standalone mechanism for determining the sleeping node, and it will have to send a special message during the presentation?

**Comment by jkandasa** [comment]
@wanvo I have created a [discussion](https://forum.mysensors.org/topic/8981/is-there-any-uniqueness-parameter-to-find-a-sleep-node-from-controller-side) on MySensors forum.

**Comment by wanvo** [comment]
I think this is what you need. The documentation for the MySensors library states that the I_PRE_SLEEP_NOTIFICATION message is sent from the node before it goes to sleep. This is indicated [here.](https://www.mysensors.org/apidocs-beta/group__MyMessagegrp.html#ggaa6f265dd19e9cad90979fef252e17a87a105639edd79e6f1d0104986aa6370de7)

**Comment by wanvo** [comment]
Jeeva, ok. Let's wait for the community to say.

**Comment by jkandasa** [comment]
@wanvo I have added an implementation in [SNAPSHOT](https://forum.mycontroller.org/topic/58/download-snapshot-build) version. Can you please check it and report back?

**Comment by wanvo** [comment]
@jkandasa I can not test this snapshot now unfortunately. I left for the wild mountainous terrain, and the internet is very slow and expensive here.

**Comment by jkandasa** [comment]
@wanvo no problem. When you back, test this and report the status. Thank you!
