### ISSUE TITLE
Send raw message Error 400 Bad Request

### ISSUE THREAD

**Issue by toygame** [mycontroller-org/mycontroller#439]
![image](https://user-images.githubusercontent.com/8748521/36567687-d8f7ad94-1859-11e8-889e-4c974c9e30cb.png)
![image](https://user-images.githubusercontent.com/8748521/36567710-f1813d62-1859-11e8-8050-0d253bf8c1d0.png)

What should i do sir?
- I have 2 Serial Gateway and 4 node
- I use mycontroller version mycontroller-dist-standalone-1.2.0-SNAPSHOT-bundle

**Comment by jkandasa** [comment]
@toygame This issue has been fixed in [SNAPSHOT](https://forum.mycontroller.org/topic/263/mycontroller-1-2-0-snapshot-version-with-major-provider-changes-and-supports-for-ack) version.

**Comment by jkandasa** [comment]
https://github.com/mycontroller-org/mycontroller/commit/ed81f68481c4b969ecbceb29eeabbc5bdfbb8295

**Comment by jkandasa** [comment]
@toygame If you see this issue kindly reopen

**Comment by toygame** [comment]
Thank you very much sir!!
