### ISSUE TITLE
add status e.g fw updating when node on fota progress 

### ISSUE THREAD

**Issue by pebri86** [mycontroller-org/mycontroller#445]
This is should be labelled as enhancement. I think it would be nice if node in progress of updating it's fw via fota a status appear e.g updating in progress with percentage progress.

**Comment by jkandasa** [comment]
@pebri86 Now OTA update status will be available in Node details page.

Screenshot:
![image](https://user-images.githubusercontent.com/1004403/40044719-e37998f0-5845-11e8-91dc-142dc4420888.png)

**Comment by pebri86** [comment]
@jkandasa Great.. i will try it soon thanks
