### ISSUE TITLE
More simple and modern logo

### ISSUE THREAD

**Issue by linadesteem** [mycontroller-org/mycontroller#448]
Hi.
I try to make more simple and modern logo for this project. here is my design:
![controller](https://user-images.githubusercontent.com/35618068/39417116-5d658212-4c7c-11e8-994f-7dd07aa8afb2.png)
![controllerbw](https://user-images.githubusercontent.com/35618068/39417244-142a257a-4c7d-11e8-9549-e36568b44b6c.png)
![controll_1](https://user-images.githubusercontent.com/35618068/39417302-8614ee18-4c7d-11e8-8cf3-5e90393bbf29.png)

what do you think? if you like it I can send PR with .SVG file

**Comment by jkandasa** [comment]
@linadesteem Thank you for the logo design. It looks nice! Unfortunately, at this time we are not looking new logo. If you want to contribute on logo design kindly create a topic on [MyController forum](https://forum.mycontroller.org), based on users reaction we will react on this topic.
