### ISSUE TITLE
smartSleep for mysensors 2.2.0

### ISSUE THREAD

**Issue by mczerski** [mycontroller-org/mycontroller#453]
Hi,

I can't get smartSleep to work properly with mycontroller.
first it seems that mysensors 2.2.0 sends different message type from smartSleep before going to sleep. I_PRE_SLEEP_NOTIFICATION instead of I_HEARTBEAT_RESPONSE. As I understand, for mycontroller to handle properly sleeping nodes the message must be I_HEARTBEAT_RESPONSE ? So I added seandHeartbeat(); before smartSleep(); But this is not working as expected. I can see in the gateway logs, that when sending raw message to the sleeping node, the message is sent immediately. And when the node wakes and send the heartbeat, I do not see any messages sent to this node from the mycontroller. What am I doing wrong ?

**Comment by mczerski** [comment]
Oh, and ofcourse I checked the "Smart sleep enabled" checkbox on this sleeping node

**Comment by mczerski** [comment]
hmm, as I debug the issue it seems that MyController actually supports mysensors 2.2.0 (it is aware of I_PRE_SLEEP_NOTIFICATION). The issue is that the messages are not put into the smartSleepQueue. I use MQTT and I'm afraid that it is the cause. I set the "Ack enabled' option in the gateway configuration but this is not helping.

**Comment by mczerski** [comment]
it seems like smartSleep is not taken into account when using "send raw message" tab. So how do I send a message to the node from the mycontroller ?

**Comment by mczerski** [comment]
OMG, I have to add a room, to which I add the sensor and only then I can send something to that node using smartSleep functionality ...

**Comment by mczerski** [comment]
after that it works

**Comment by jkandasa** [comment]
@mczerski great! Thank you for the updates!
