### ISSUE TITLE
Node ID/EUI should be shown on the topology chart

### ISSUE THREAD

**Issue by Boggie** [mycontroller-org/mycontroller#463]
When viewing the topology chart for a network with several nodes sharing the same sketch (repeaters, temperature sensors and other standard nodes) it is not possible to see which node on the chart corresponds to which node id.

It would be nice to have the node id / eui shown in the tooltop.

Discussion that lead to this issue can be found here: https://forum.mycontroller.org/topic/330/node-eui-on-topology-chart/4

**Comment by jkandasa** [comment]
@Boggie This change available in [SNAPSHOT](https://forum.mycontroller.org/topic/58/download-snapshot-build) version.

![image](https://user-images.githubusercontent.com/1004403/44308872-22188e00-a3db-11e8-8202-ec7623a3abeb.png)


![image](https://user-images.githubusercontent.com/1004403/44308873-28a70580-a3db-11e8-94e7-c49cee979436.png)
