### ISSUE TITLE
Custom node name 

### ISSUE THREAD

**Issue by seant100** [mycontroller-org/mycontroller#464]
When a node presents itself then MyController will set the Node name to the sketch name in the presentation.
I now have 2 nodes running the same sketch with auto id.
I can then set a custom node name by editing each of the nodes. 
However when I reboot the node or click on the "refresh node info" under actions then the name resets back to the sketch name as sent by the presentation.

**Comment by nikolac** [comment]
+1 this fix my biggest annoyance

**Comment by jkandasa** [comment]
@seant100 @nikolac I have added a fix in [SNAPSHOT](https://forum.mycontroller.org/topic/58/download-snapshot-build) version. 
Kindly check it and update.

When editing a node you should add `"lockNode": true` property in node properties. If you have more number of fields in properties, at the end add comma and attach this property.
**NOTE:** Should not use `"` for the value. It should be `true` or `false`

![image](https://user-images.githubusercontent.com/1004403/45729097-8603c180-bbe8-11e8-8d9d-ff78c557093e.png)

**Comment by seant100** [comment]
@jkandasa Tried this and seems to be working. If any revert back to the sketch name I will let you know. Otherwise all is ok now.
Thank you !

**Comment by seant100** [comment]
@jkandasa Just want to know why this cannot be the default behaviour? If a new node presents itself then it can set the name using the sketch name. After that it should NEVER override the name.

**Comment by jkandasa** [comment]
@seant100 Sometimes a user wants to rename node name via sketch. So I kept sketch name as default. Users like you can lock the node name.
