### ISSUE TITLE
Remote control buttons in MyController

### ISSUE THREAD

**Issue by joaopauloss** [mycontroller-org/mycontroller#47]
jkandasa, as we talk on mysensors forum, it's very kindly and would make mycontroller almost a perfect controller that we can control the IR devices from an interface on own mycontroller website, where you could save the signals of each button of the remote of TV, for example, and send the IR signals with no need of its remote fo this.

Thanks for your support.

**Comment by jkandasa** [comment]
![image](https://cloud.githubusercontent.com/assets/1004403/14522316/9971b3ca-024b-11e6-8300-1063a46add07.png)

Added as dashboard widget. Buttons detail should be in `JSON` format.
To create `json` configuration error free way use http://www.jsoneditoronline.org/
We can include button names as HTML or icons(recommended: font awesome icons)

In configuration `name` and `payload` are mandatory fields.
`btnType` is optional and can be any one of `default`, `primary`, `success`, `info`, `warning`, `danger`

Example `json` as follows,
```
[
  {
    "name": "<i class='fa fa-power-off'></i>",
    "payload": "P",
    "btnType": "danger"
  },
  {
    "name": "1",
    "payload": "1"
  },
  {
    "name": "2",
    "payload": "2"
  },
  {
    "name": "3",
    "payload": "3"
  },
  {
    "name": "4",
    "payload": "4"
  },
  {
    "name": "5",
    "payload": "5"
  },
  {
    "name": "6",
    "payload": "6"
  },
  {
    "name": "7",
    "payload": "7"
  },
  {
    "name": "8",
    "payload": "8"
  },
  {
    "name": "9",
    "payload": "9"
  },
  {
    "name": "0",
    "payload": "0"
  },
  {
    "name": "<i class='fa fa-play'></i>",
    "payload": "PL",
    "btnType":"success"
  },
  {
    "name": "<i class='fa fa-pause'></i>",
    "payload": "PA",
    "btnType":"warning"
  }
]
```
