### ISSUE TITLE
Telegram API for scripting

### ISSUE THREAD

**Issue by nagurao** [mycontroller-org/mycontroller#474]
Can we have API for Telegram on similar lines of PushBullet?

**Comment by jkandasa** [comment]
@nagurao this feature added in [SNAPSHOT](https://forum.mycontroller.org/topic/58/download-snapshot-build) version.
Following api's will be available for Telegram,
```java
mcApi.operation().sendTelegramMessage(String chatId, String parseMode, String text); // supported parseMode: text, html, markdown
mcApi.operation().sendTelegramMessage(String chatId, String text); // default parseMode: text
```
