### ISSUE TITLE
Purge not working

### ISSUE THREAD

**Issue by seant100** [mycontroller-org/mycontroller#475]
Purge data for a sensor does not work. Perhaps it is only clearing the raw data, but it should also purge the data for all time range graphs (eg weekly, yearly etc) based on the conditions and date range set to purge data for.

**Comment by jkandasa** [comment]
@seant100 Can you list the MyController version details?

**Comment by seant100** [comment]
@jkandasa screenshot attached

![image](https://user-images.githubusercontent.com/637145/47475631-a264d080-d81c-11e8-9869-a6ea8b53e7ca.png)

**Comment by jkandasa** [comment]
@seant100 I have modified the source code and updated in [SNAPSHOT](https://forum.mycontroller.org/topic/58/download-snapshot-build) version. Can you check with this change? Kindly confirm with least priority sensor variable.

NOTE: https://forum.mycontroller.org/topic/362/google-analytics-enabled-from-version-1-4-0

**Comment by seant100** [comment]
@jkandasa Updated to latest snapshot. Tried to purge with condition = >60 and all dates and when I select "Year" graph it still shows values of 90+. So purge is still not working. 
Also the latest snapshot gives lots of errors and is incredibly slow for everything. So I have to now revert back to the previous snapshot version I was using.
For interest I have attached the log file showing errors with latest snapshot which I downloaded on 25 Oct 2018.
[mycontroller.zip](https://github.com/mycontroller-org/mycontroller/files/2520234/mycontroller.zip)

**Comment by jkandasa** [comment]
@seant100 can you try with the most recent version? I have added a fix.

New option: only for double type data
* when you pass value alone it will purge `avg` data alone. ie. `>=45.6`
* we can specify min, max and avg with comma separated. ie. `min>=45.6,max>=78.2,avg>=56.3`

Can you check with the most recent version?

**Comment by seant100** [comment]
@jkandasa Thank you. I will give it a try asap.

**Comment by jkandasa** [comment]
@seant100 kindly report back the observations.

**Comment by seant100** [comment]
@jkandasa Thank you. That works. I would suggest to add some "hints" or "usage examples" onto the purge page
