### ISSUE TITLE
how to start on idea

### ISSUE THREAD

**Issue by ycy1991** [mycontroller-org/mycontroller#487]
hi jkandasa:
   After I built the project in win10 64, how to start the project with idea? when I started StartApp.class, the program exited directly without running.Can you give me some advice?
  Thanks

**Comment by jkandasa** [comment]
@ycy1991 can you post your questions on [the forum?](https://forum.mycontroller.org/)

You can see your build under `mycontroller/dist/target/`,
Files: `mycontroller/dist/target/mycontroller-dist-standalone-1.4.0.Final-bundle.tar.gz` or `mycontroller/dist/target/mycontroller-dist-standalone-1.4.0.Final-bundle.zip`, extract either one and run it.
