### ISSUE TITLE
Gateway relay

### ISSUE THREAD

**Issue by jpink** [mycontroller-org/mycontroller#490]
Hi,

I have multiple PC:s (MyController) in my LAN and they all have Arduino (Gateways) connected via USB-serial. There is need to some kind of relay/proxy/repeater application that runs on PC and connects all Gateways to single controller in Ethernet. Protocol can be MQTT (Homie), HTTP (openAPI), etc. Any ideas?

I know this setup can be replaced by RF-connections, but I think there is too few wired options. I have many PC:s, USB cables, Arduinos and encompassing LAN & WLAN so I want to use then before ordering (waiting) new Arduino parts.

**Comment by jkandasa** [comment]
@jpink  If your Gateways are MySensors gateway, you can run [serial2mqtt](https://github.com/mycontroller-org/serial2mqtt) adaptor on your PC's and target to a single MyController instance with multiple gateways.

**Comment by jpink** [comment]
That adapter seems to be just what I'm looking for. Thank you very much!
