### ISSUE TITLE
sendRawMessage REST API call for smart sleep nodes

### ISSUE THREAD

**Issue by mtiutiu** [mycontroller-org/mycontroller#501]
It seems that the sendRawMessage REST api call doesn't take into account smart sleep enabled nodes. From the tests that I did so far it just seems to send the message right away without putting it into the waiting queue.

Environment used:
 1. MySensors back-end with a serial gateway
 2. MyController version 1.4.0.

**Comment by jkandasa** [comment]
@mtiutiu I have updated in [SNAPSHOT](https://drive.google.com/drive/u/0/folders/0BzuumrtRA7p6Z0hCX2V6cVh2ckU) version, could you please confirm?

**Comment by mtiutiu** [comment]
@jkandasa 
Tested and it works as expected now!! This ticket can be closed now. Thanks.
