### ISSUE TITLE
hybrid sleep

### ISSUE THREAD

**Issue by aneantisor** [mycontroller-org/mycontroller#502]
on a solar/batterie powered node, i execute kind of hybrid sleep.
Arduino actually control the charge, so it check the voltage every 4 second and sleep beetween this.
Every 2 minutes, the node send the sensors value and then i execute a smartsleep.
I use smartsleep to send firmware update, and i can change the charging voltage to.
MYSController actually wait for the pre sleep message and it work every time.
MyController.org appear to forget to send the message and so it work about 5% of the time (just a guess).

**Comment by jkandasa** [comment]
@aneantisor can you increase [MY_SMART_SLEEP_WAIT_DURATION_MS](https://github.com/mysensors/MySensors/blob/2.3.1/MyConfig.h#L1223)? may be `1000`?

**Comment by aneantisor** [comment]
It was that. I updated the node and set MY_SMART_SLEEP_WAIT_DURATION_MS 2000. And now it's perfectly working. Thank you

**Comment by jkandasa** [comment]
@aneantisor please note. now your node consumes more power. As it awakes 2000ms instance of 500ms
