### ISSUE TITLE
start.sh fails for Java versions != 1.8

### ISSUE THREAD

**Issue by herm** [mycontroller-org/mycontroller#506]
The version check in start.sh fails for OpenJDK:
```
$ start.sh
/usr/bin/java
java version: 13.0.1
Mycontroller.org server required java version 1.7 or later
```
OpenJDK seems to be unsupported but the error message could be clearer.

```
java --version
openjdk 13.0.1 2019-10-15
OpenJDK Runtime Environment (build 13.0.1+9)
OpenJDK 64-Bit Server VM (build 13.0.1+9, mixed mode)
```

**Comment by jkandasa** [comment]
@herm MyController does not support java > 1.8.
What is your OS?

**Comment by herm** [comment]
I also figured out that everything > 1.8 does not work. It works fine with OpenJDK 8. 

However the version check and the statement in the README is misleading. 
The version check in start.sh say "Mycontroller.org server required java version 1.7 or later".
The [README](https://github.com/mycontroller-org/mycontroller/blob/development/README.adoc) says "Java : 1.8 or later".
And it seems like the actual requirement is Java 1.8 and nothing else works.

My OS is Manjaro, but that's probably irrelevant.

**Comment by jkandasa** [comment]
@herm ah thanks! I will update the doc/start.sh file
