### ISSUE TITLE
make the client for android

### ISSUE THREAD

**Issue by arturmon** [mycontroller-org/mycontroller#56]
your browser does not put all the better to make a single mobile client.
Here are some examples:
https://play.google.com/store/apps/details?id=ru.galakart.majordroid
https://play.google.com/store/apps/details?id=org.openhab.habdroid

**Comment by jkandasa** [comment]
@arturmon thank you for this request. I will work on this, I have to learn bit about android application development.

**Comment by jkandasa** [comment]
http://ionicframework.com/

**Comment by gbrd** [comment]
another solution could be to implement imperihome (http://www.evertygo.com/imperihome) 
standard API on server side

**Comment by danielefrigo** [comment]
any news about this?

**Comment by jkandasa** [comment]
@danielefrigo Just started learning http://ionicframework.com/ hopefully we can expect first mobile version in a couple of months.

**Comment by jkandasa** [comment]
We are not going to create a mobile client for 1.x version.
The mobile client will be added for 2.x version
