### ISSUE TITLE
Full localization and not stores the selected language.

### ISSUE THREAD

**Issue by arturmon** [mycontroller-org/mycontroller#57]
how to make a complete localization? all the files from A folder partials altered.
and after the upgrade page F5 flies selected language. at the entrance to the new page you want to change the language.

**Comment by jkandasa** [comment]
@arturmon I guess you want to select your language permanently. You do not want to change your language every time you login, Am I right? If so it's not a problem already we have an issue to track this one. https://github.com/mycontroller-org/mycontroller/issues/41 in system settings we have to an add entry to hold users preferred language.

**Comment by arturmon** [comment]
Yes that's what I want. Store the state.

**Comment by jkandasa** [comment]
@arturmon I will fix it and make it available in 0.0.2-alpha6 version.

**Comment by arturmon** [comment]
I forgot to ask, why can not translate some words? I understand these values in java files))

**Comment by jkandasa** [comment]
@arturmon Yes, I have to create some base language location like I did for angularJS(html). I'm working on this, I will come with fix soon. 

Thank you!!

**Comment by arturmon** [comment]
translation is made 95%))

**Comment by jkandasa** [comment]
@arturmon, @Dietmar-Franken I appreciate your contribution!! you are doing great work!! you people  has requested this feature at right time!!
We will collaborate together and final outcome **transparent open source product for us by us :wink:**

**Comment by arturmon** [comment]
how to translate this? ))
![3232](https://cloud.githubusercontent.com/assets/7686999/11001731/d311a1fe-84b9-11e5-8780-17968778778c.jpg)
![4554](https://cloud.githubusercontent.com/assets/7686999/11001756/093b55a4-84ba-11e5-82a7-9b4b85b24742.jpg)

**Comment by jkandasa** [comment]
`First` is from angularJS modules, Let me check it. For `Java` I have to create base. I will create it on next week some time.

**Comment by Dietmar-Franken** [comment]
I´ve looked at all files yesterday,there is a lot of work to do. And in between i´ve bought a big book to learn java.

**Comment by arturmon** [comment]
ok. We are waiting for a new release.

**Comment by jkandasa** [comment]
https://github.com/mycontroller-org/mycontroller/commit/6d0f075eef75eb4aae384c1ea03bafdbace9fcc0 

@arturmon 
With this fix we can store our language permanently. 
Go to `System Settings`, change `Language` under `Version`. Do logout and login.

**Comment by arturmon** [comment]
here is how to translate this piece of code?
file 
```
https://github.com/mycontroller-org/mycontroller/blob/master/src/main/package/www/controllers/timer.js
```
```
  $scope.deleteMsg = $sce.trustAsHtml("You are about to delete an timer"
    +"<br>Deletion process will remove complete trace of this timer!" 
    +"<br>Click 'Delete' to proceed."
    +"<br><I>Timer: [Name:"+timer.name+"]</I>");
```

**Comment by jkandasa** [comment]
@arturmon I will come with a solution

**Comment by jkandasa** [comment]
@arturmon This commit (https://github.com/mycontroller-org/mycontroller/commit/13a1aa5e75e9b01368d35a5f5cf38d53def25c6e) will explain how to change text in controllers in angularJs files

**Comment by arturmon** [comment]
It may be worth to use the service https://www.transifex.com or phraseapp.com?

**Comment by jkandasa** [comment]
@arturmon It's like we have to keep our locale `mc_locale_*.json` files in https://www.transifex.com/ and we can collaborate there. It will be synced automatically. with git repository. Am I correct?

**Comment by Dietmar-Franken** [comment]
@jkandasa 
Mysensors added a new controller Calaos.The files are on [Github](https://github.com/calaos) too.They use [Pootle](http://translate.calaos.fr/) to tanslate and it looks very good for me.

**Comment by jkandasa** [comment]
@Dietmar-Franken thank you! It seems we have to host ourself for `Pootle`, but https://www.transifex.com/ it's free for opensource projects. And I believe https://www.transifex.com/ has  all the options that we have it in `Pootle`.

@arturmon @Dietmar-Franken Shall we go with https://www.transifex.com/ ?

**Comment by Dietmar-Franken** [comment]
@jkandasa 
OK, lets go   with  transiflex

**Comment by jkandasa** [comment]
@arturmon @Dietmar-Franken done!!

https://www.transifex.com/mycontrollerorg/gui-angularjs/mc_locale_gui/

**Comment by arturmon** [comment]
goo

**Comment by jkandasa** [comment]
@Dietmar-Franken  @arturmon your id please in https://www.transifex.com

**Comment by jkandasa** [comment]
@arturmon you are the coordinator for https://www.transifex.com/mycontrollerorg/gui-angularjs/language/ru_RU/ Kindly manage completely ru_RU

**Comment by Dietmar-Franken** [comment]
@jkandasa 
What id?

**Comment by arturmon** [comment]
Thank you

**Comment by jkandasa** [comment]
@Dietmar-Franken I need to add you in https://www.transifex.com/mycontrollerorg/gui-angularjs/ to coordinate de_DE language. For that I need your `transifex` id or I can invite you with your email id.

**Comment by Dietmar-Franken** [comment]
@jkandasa 
Please invite me

**Comment by jkandasa** [comment]
@Dietmar-Franken Shall send invitation to ` ***@*m****.*e`? which on i got from `MySensors.org` chat

**Comment by Dietmar-Franken** [comment]
:+1:

**Comment by Dietmar-Franken** [comment]
@jkandasa 
Signed up

**Comment by jkandasa** [comment]
@Dietmar-Franken great! now you can manage https://www.transifex.com/mycontrollerorg/gui-angularjs/language/de_DE/ and you are the coordinator for `de_DE`.

**Comment by Dietmar-Franken** [comment]
@jkandasa 
Thank you

**Comment by jkandasa** [comment]
implemented in GUI, to track core java changes https://github.com/mycontroller-org/mycontroller/issues/137

**Comment by arturmon** [comment]
not a full translation
![1](https://cloud.githubusercontent.com/assets/7686999/14231557/dce839ee-f990-11e5-9c1f-449ef8b31bed.jpg)
![2](https://cloud.githubusercontent.com/assets/7686999/14231558/dd03db18-f990-11e5-8dff-0ffc257ec2a6.jpg)
![3](https://cloud.githubusercontent.com/assets/7686999/14231559/dd17513e-f990-11e5-8b65-e37aa724353e.jpg)
![4](https://cloud.githubusercontent.com/assets/7686999/14231560/dd18d658-f990-11e5-9481-f4ced80a6754.jpg)

**Comment by jkandasa** [comment]
We could not change everything like `Sort By`, `A->Z` etc. those are all managed in addon's. I will change whatever possible from mycontroller.

**Comment by jkandasa** [comment]
closing this issue, in this release(1.x), we are not going to localization 100%. Some of the dependency libraries not supporting.
