### ISSUE TITLE
import and export base. creating backups.

### ISSUE THREAD

**Issue by arturmon** [mycontroller-org/mycontroller#59]
I think it will be in demand

**Comment by arturmon** [comment]
Upgrade, Backup, and Restore
Database Upgrade

The recommended way to upgrade from one version of the database engine to the next version is to create a backup of the database (in the form of a SQL script) using the old engine, and then execute the SQL script using the new engine.

Backup using the Script Tool

The recommended way to backup a database is to create a compressed SQL script file. This will result in a small, human readable, and database version independent backup. Creating the script will also verify the checksums of the database file. The Script tool is ran as follows:
```
java org.h2.tools.Script -url jdbc:h2:~/test -user sa -script test.zip -options compression zip
```
It is also possible to use the SQL command SCRIPT to create the backup of the database. For more information about the options, see the SQL command SCRIPT. The backup can be done remotely, however the file will be created on the server side. The built in FTP server could be used to retrieve the file from the server.

Restore from a Script

To restore a database from a SQL script file, you can use the RunScript tool:
```
java org.h2.tools.RunScript -url jdbc:h2:~/test -user sa -script test.zip -options compression zip
```
For more information about the options, see the SQL command RUNSCRIPT. The restore can be done remotely, however the file needs to be on the server side. The built in FTP server could be used to copy the file to the server. It is also possible to use the SQL command RUNSCRIPT to execute a SQL script. SQL script files may contain references to other script files, in the form of RUNSCRIPT commands. However, when using the server mode, the references script files need to be available on the server side.

Online Backup

The BACKUP SQL statement and the Backup tool both create a zip file with the database file. However, the contents of this file are not human readable.

The resulting backup is transactionally consistent, meaning the consistency and atomicity rules apply.
```
BACKUP TO 'backup.zip'
```
The Backup tool (org.h2.tools.Backup) can not be used to create a online backup; the database must not be in use while running this program.

Creating a backup by copying the database files while the database is running is not supported, except if the file systems support creating snapshots. With other file systems, it can't be guaranteed that the data is copied in the right order.

**Comment by jkandasa** [comment]
@arturmon backup and restore feature added. 

https://github.com/mycontroller-org/mycontroller/commit/d2d41e6bd36abec09319f792cf9ddc1fb741c53d

**Comment by arturmon** [comment]
[image: Встроенное изображение 1]

2016-02-17 1:37 GMT+03:00 Jeeva Kandasamy <notifications@github.com>:
