### ISSUE TITLE
Export Sensor Data

### ISSUE THREAD

**Issue by andykartman** [mycontroller-org/mycontroller#6]
Would be very useful to be able to export specific sensor data so it can be used in another system for further analysis (spreadsheet etc).

Even just a simple CSV data download would be a good start and maybe some filters to select the data range to download. If it was from the Graph screen it could perhaps download the selected data range there?

**Comment by jkandasa** [comment]
@andykartman Thank you for the enhancement request. 

We do not have any dynamic data selection range, graphs are straight forward and predefined, only 4 types, 
1. Last 1 Hour (1 minute Interval) 
2. Last 24 Hours (5 minutes interval)
3. Last 30 days (1 hour interval)
4. All available data (1 day interval)

We can provide some buttons on heading of each graph to download above data.

Note: For ON/OFF type devices there is no aggregation, So there is no interval. Just displays all available data based on time (like last 1 hour, last 24 hours, etc.,)

**Comment by andykartman** [comment]
@jkandasa Thanks. It would be good for the Graphs to have dynamic data selection range. I always find that one of the key reasons for monitoring a physical sensor (temp, humidity, power etc) is so it can be analysed and reported on, so a dynamic range selection (and therefore selectable range for CSV download), would be a really nice thing.

 Of course what you have looks great, but just a suggestion.
