### ISSUE TITLE
I know nothing about Java but want to help with the development of the project. how can I help?  )))

### ISSUE THREAD

**Issue by arturmon** [mycontroller-org/mycontroller#61]
how can I help?

**Comment by jkandasa** [comment]
@arturmon Thank you so much for your interest with this project!! 

MyController is designed this way, backed is working with pure java and it is giving REST API support for outside world. We have used front-end with AngularJS.

Even you do not know `java` you can help for this project in different ways,
- GUI development with AngularJS
- Android application for MyController
- Testing MyController features and report bugs
- Create user documents and videos
- Add content in main website (http://www.mycontroller.org)
- Ask new feature requests
- Donation for this project (Right now we do not have option to donate, will be available soon)

**Comment by arturmon** [comment]
I advise you to do the wiki on the main page.

**Comment by Dietmar-Franken** [comment]
@jkandasa 
Which development environment do you have?

**Comment by jkandasa** [comment]
@Dietmar-Franken I'm working with `Fedora 22` operating system, for `Java` I'm using Eclipse and for HTML/JS `Geany` Editor

**Comment by arturmon** [comment]
how do you feel about NetBeans IDE?

**Comment by jkandasa** [comment]
@arturmon It should work. You can see many people will be using `Eclipse`, as it is most popular and open source project.

**Comment by Dietmar-Franken** [comment]
@jkandasa 
Some questions about the code.
What is placeholder used for and is uib-tooltip show on mouseover?
 ```
 <div class="panel-heading">
		<form class="form-inline">
			<div class="form-group">
				<label class="sr-only" for="search">{{ 'SYSTEM.SEARCH' | translate }}</label>
				<input type="text" class="form-control ng-pristine ng-valid input-sm ng-valid" 
				ng-model="query" id="search" placeholder="Search" ng-model="query" 
				ng-change="updateFilteredList()"/>
			</div>
			<a href='' class="text-default pull-right" ng-click="add()" uib-tooltip="Add"><i class="fa fa-lg fa-plus-square-o"></i></a>
		</form>
	 </div>
```

**Comment by jkandasa** [comment]
@Dietmar-Franken place holder used to show content inside text box. Before entering actual content.
![place-holder](https://cloud.githubusercontent.com/assets/1004403/10993866/461fc7ba-8498-11e5-92e4-482adfeb7ec4.png)

**Comment by Dietmar-Franken** [comment]
@jkandasa 
Thank you now i understand it
