### ISSUE TITLE
Implement MQTT Broker to serve other controllers and clients

### ISSUE THREAD

**Issue by jkandasa** [mycontroller-org/mycontroller#7]
Publish all the events from Serial (or) Ethernet gateway to MQTT. Also public MyController.org related events. We can add any number of controllers and clients. As we are implementing in controller side should support for authentication, hence we can use it in public network.

**Comment by bpair** [comment]
I think publishing all events would be a great feature. You may also want to allow converting /nodeId/childId  to just be /GUID

**Comment by jkandasa** [comment]
@bpair Good idea, I will give the format(MySesnors) to user defined. I will give format variables something like `$nodeid,$sensorid,$messageType,$subType,$payload` So user can define their own format. And nodeid and sensorid always will be in three digits. So it will not confused when they merge both.

Example: 
* `myMQTT/$nodeid/$sensorid/$messageType/$subType/$payload` ->myMQTT/012/004/1/2/1
* `myMQTT/$nodeid$sensorid/$messageType/$subType/$payload` -> myMQTT/012004/1/2/1

And if the enable user friendly mode, output will be like,
* myMQTT/012/004/C_REQ/V_STATUS/1
* myMQTT/012004/C_REQ/V_STATUS/1

**Comment by jkandasa** [comment]
https://github.com/mycontroller-org/mycontroller/commit/61888e64e439c4faad0e4f720e212293b784a350

**Comment by al-uminium** [comment]
Why waste time making when MQTT server already exist?

**Comment by jkandasa** [comment]
@al-uminium Yes, we have MQTT broker setup already. but,

1. However we do not want to spend time with MQTT broker setup separately. So installing of MyController will be like zero setup
2. I want to control authentication with inbuilt MyController users
3. Want to push all the events from Serial (or) Ethernet gateway to MQTT

**Comment by dbaravalle** [comment]
> Publish all the events from Serial (or) Ethernet gateway to MQTT. Also public MyController.org related events.

Hi!

Is this functionality has been added? Is it ready to be used?

I could not find the part of the code where it publishes all events from the serial gateway to MQTT Broker

**Comment by jkandasa** [comment]
@dbaravalle No, this functionality not added till now. May be added later.
For MyController events will be added. But for Serial and Ethernet plan may be dropped.

**Comment by jkandasa** [comment]
dropping this feature request for now. if we receive many request for this feature may reconsider again.

**Comment by jkandasa** [comment]
This feature has been addressed via [serial2mqtt](https://github.com/mycontroller-org/serial2mqtt)
