### ISSUE TITLE
does not display the execution of the timer.

### ISSUE THREAD

**Issue by arturmon** [mycontroller-org/mycontroller#71]
does not display the execution of the timer.
![error](https://cloud.githubusercontent.com/assets/7686999/10923926/97ce6112-8294-11e5-8a69-1a8edfa89f90.jpg)

**Comment by jkandasa** [comment]
@arturmon on the image you have marked validity of the timer. Which should come if you add validity when you create new timer. Kindly refer attached image.
![timer-validity](https://cloud.githubusercontent.com/assets/1004403/10932296/b95575da-82f5-11e5-855d-a34113a34970.png)

**Comment by arturmon** [comment]
I created a new timer
![error](https://cloud.githubusercontent.com/assets/7686999/10933505/f99eba90-82e9-11e5-98de-8786321886e0.jpg)
![error2](https://cloud.githubusercontent.com/assets/7686999/10933504/f99c14a2-82e9-11e5-8e00-d49cc9cab1ba.jpg)

**Comment by jkandasa** [comment]
@arturmon Which is working good with 0.0.2-alpha5, I hope we introduced this issue on multi language support. Let me build locally the recent one and fix this issue. Thank you!

**Comment by jkandasa** [comment]
@arturmon I checked out master branch, unable to reproduce this issue. Can you please check with master branch?

**Comment by arturmon** [comment]
I use the same file from the master branch.I get this result as shown above. how to show the contents of the html file?

**Comment by jkandasa** [comment]
@arturmon can you open in private browser(chrome or firefox), We come to know if you have any cache issue.

**Comment by goranrad** [comment]
Is it possible to add an Edit feature on Timer as there is on alarms?

**Comment by arturmon** [comment]
It opened in chrome.I check in another browser and let know.

**Comment by jkandasa** [comment]
@goranrad We are tracking edit timer feature with https://github.com/mycontroller-org/mycontroller/issues/29 we will make available on 0.0.2-alpha6 release.

**Comment by arturmon** [comment]
Проверил в chore и IE результат тот же, не отображается. Сравнил файлы с демо сайта и после локализации...разница только в локализации. Вот код которые отвечает за построение таблицы.
```
	  <!-- Table -->
	  <table class="table table-hover table-bordered table-striped" at-table at-paginated 
	  at-list="filteredList" at-config="config">
			<thead></thead>
			<tbody>
	      <tr>
					<td class="text-center" at-sortable at-title="{{ 'SYSTEM.ENABLED' | translate }}">
            <a href='' ng-click="enableDisable(item);" class="text-{{item.enabled ? 'success' : 'danger'}}" uib-tooltip="{{item.enabled ? 'Disable' : 'Enable'}}">
              <i class="fa fa-circle"></i>
            </a>
          </td>
          <td at-implicit at-sortable at-attribute="name" at-title="{{ 'SYSTEM.NAME' | translate }}"></td>
					<td at-implicit at-sortable at-attribute="timerDataString" at-title="{{ 'SENSORS.TYPE' | translate }}"></td>
          <td at-implicit at-sortable at-attribute="sensorVariableTypeString" at-title="{{ 'NODE.VARIABLE_TYPE' | translate }}"></td>
          <td at-implicit at-sortable at-attribute="payloadFormatted" at-title="{{ 'RAW.PAYLOAD' | translate }}"></td>
          <td at-implicit at-attribute="validityString" at-sortable at-title="{{ 'TIMER.VALIDITY' | translate }}"></td>
					<td class="text-center">
						<a href='' ng-click="delete(item)" class="text-danger" uib-tooltip="{{ 'SYSTEM.DELETE' | translate }}"><i class="fa fa-lg fa-trash"></i></a>
					</td>
				</tr>
			</tbody>
		</table>
		<at-pagination class="pull-right" at-list="filteredList" at-config="config"></at-pagination>

```

**Comment by jkandasa** [comment]
@arturmon Could you please type in English

**Comment by arturmon** [comment]
Sorry.
I checked in the chrome and IE result is the same, is not displayed. Compare Files with the demo site and after localization ... the only difference is in the localization. Here is the code that is responsible for the construction of the table.

**Comment by jkandasa** [comment]
@arturmon I'm unable to produce this issue. Kindly try once with `private browser` mode. I hope your browser retaining old cache.
https://support.google.com/chrome/answer/95464?source=gsearch&hl=en

**Comment by arturmon** [comment]
```private browser```
same. html file is changed to the original site ... waking did not touch ... where the output processing "Validity"?
![3232](https://cloud.githubusercontent.com/assets/7686999/11001582/df8fac06-84b8-11e5-8de5-3e5ff6f51f19.jpg)

**Comment by jkandasa** [comment]
@arturmon Could you create another timer with validity and check it?

**Comment by arturmon** [comment]
deleted version mycontroller 0.0.2-alpha-5 installed 0.0.2-alpha6-SNAPSHOT release. no changes, does not display the execution of the timer. what am I doing wrong?

**Comment by jkandasa** [comment]
@arturmon Can you list values what exactly you used to create timer?

**Comment by jkandasa** [comment]
unable to reproduce this issue, kindly reopen if you face this issue again
