### ISSUE TITLE
Error running the master-branch

### ISSUE THREAD

**Issue by Dietmar-Franken** [mycontroller-org/mycontroller#73]
@jkandasa 
I try to run the master-branch but no success.
```
pi@raspberrypi ~/mycontroller-master5/mycontroller-master/src/main/package/bin $ ./start.sh
/usr/bin/java
java version: 1.8.0
Start issued for Mycontroller
```
Browser said no connectin to server.
Than i try
```
pi@raspberrypi ~/mycontroller-master5/mycontroller-master/src/main/package/bin $ ./stop.sh
Mycontroller.org server is not running!
```
After that i looked into mycontroller.log and i found this.
```
Error: Unable to access jarfile ../lib/mycontroller-standalone-0.0.2-alpha6-SNAPSHOT-single.jar

```
What have i done wrong ?

**Comment by jkandasa** [comment]
@Dietmar-Franken you cannot run as is. You should create build on your local computer from downloaded source code.

Before to build you should satisfy the following dependencies,
- JDK 1.8 
- maven
- git

Steps to build,
- `git clone https://github.com/mycontroller-org/mycontroller.git`
- `cd mycontroller`
- `mvn package`
- You can find binary build under `mycontroller/target/`
     - `mycontroller-standalone-0.0.2-alpha6-SNAPSHOT-bundle.tar.gz` 
     - `mycontroller-standalone-0.0.2-alpha6-SNAPSHOT-bundle.zip`
- extract any one of file listed above and follow normal steps to run.

**Comment by Dietmar-Franken** [comment]
Thank you works  perfect
![alpa6](https://cloud.githubusercontent.com/assets/12993220/10988085/9b15da98-8439-11e5-9882-4e3ca4def7e4.jpg)

**Comment by arturmon** [comment]
What are the differences between alpha5 and alpha6-SNAPSHOT?

**Comment by jkandasa** [comment]
@arturmon master branch maintained as next release snapshot, once we fixed scheduled issues/features for this release we will release actual version, till then it will be marked as SNAPSHOT.
