### ISSUE TITLE
Serial gateway is not working properly with RPI native serial port

### ISSUE THREAD

**Issue by jkandasa** [mycontroller-org/mycontroller#74]
Serial port gateway is not working properly with Raspberry PI native serial port `ttyAMA0`

**Comment by mannkind** [comment]
I *think* that I am running into this; MyController won't issue NodeIDs despite the logs indicating it's working. If you'd like help testing a fix, I'd be glad to lend a hand.

Nov 7, 2015 6:17:17 PM	Sensor Internal	Sent	[I_ID_RESPONSE], [NodeId:255, SensorId:255, PayLoad: 13]
Nov 7, 2015 6:17:17 PM	Sensor Internal	Received	[I_ID_REQUEST], [NodeId:255, SensorId:255, PayLoad: null]
Nov 7, 2015 6:17:08 PM	Sensor Internal	Sent	[I_ID_RESPONSE], [NodeId:255, SensorId:255, PayLoad: 12]
Nov 7, 2015 6:17:08 PM	Sensor Internal	Received	[I_ID_REQUEST], [NodeId:255, SensorId:255, PayLoad: null]
Nov 7, 2015 6:15:00 PM	Sensor Internal	Sent	[I_ID_RESPONSE], [NodeId:255, SensorId:255, PayLoad: 11]
Nov 7, 2015 6:15:00 PM	Sensor Internal	Received	[I_ID_REQUEST], [NodeId:255, SensorId:255, PayLoad: null]

**Comment by jkandasa** [comment]
@mannkind Thank you to report this issue! Log says MyController issues NodeId, however it doesn't reach target Node, hence it's requesting NodeId again and again.

 Could you please update bit more about your environment like?
- Version of MyController
- Version of MySensors.org API
- Gateway Type
- OS type/version
- If you are using serial gateway, which type of USB to TTL are you using [or] native RPI serial port?
- If you feel to share any other information's

**Comment by mannkind** [comment]
No problem. I just tried to use MyController for the first time today and noticed the Issued ID didn't seem to be working. Here is my setup:

MyController: 0.0.2 alpha5
MySensors: 1.5
Gateway Type: Serial Gateway
Serial Gateway using Raspberry Pi 2 GPIO Tx/Rx pins. 
OS: Raspbian Jessie on Raspberry Pi 2

**Comment by jkandasa** [comment]
@mannkind Thanks to show your interest with MyController! I'm really sorry for the difficult that you are facing at your first site.

Yes, with RPI native serial port it doesn't work properly. I will fix this issue on upcoming releases. I hope you are also facing same kind of issue. 

For now can you try with USB-TTL serial port or Ethernet gateway?

**Comment by mannkind** [comment]
Unfortunately, I don't have either of those available. Appreciate your efforts; looking forward to try it!

**Comment by jkandasa** [comment]
I followed this in RPI and it's working good so far. Let me test it some more time.

>By default, the serial port on the Raspberry Pi is configured as a console port for communicating with the Linux OS shell. If you want to use the serial port in a software program, you must disable the OS from using this port. Please see this blog article by Clayton Smith for step-by-step instructions on how to disable the OS console for this port: http://www.irrational.net/2012/04/19/using-the-raspberry-pis-serial-port/

Source: http://pi4j.com/example/serial.html

**Comment by jkandasa** [comment]
@mannkind If you have not done above step, issue should be here. Otherwise we have to find the root cause.

**Comment by mannkind** [comment]
Yep, I have completed those steps. MyController seems to be reading from the serial port because I can see the gateway's standard output and debug statements in MyController's logs. It appears that maybe output isn't working, but I'm not certain. 

I'm fairly sure the gateway is setup and working correctly – w/debug enabled I can see it exchanging data, nonces (I have signing enabled), etc. 

Maybe it's not MyController; It's just the first controller that I've tried on the Raspberry Pi. After a bit of troubleshooting myself, I decided to check Github and saw this issue. If there's any more logs/debugging I can give you, let me know.

**Comment by mannkind** [comment]
FWIW - Maybe this is just my weird RPi2 or Arduino.

After some testing using Minicom, a custom Go program, and modifying MyController itself...
For some reason there needs to be delay between sending characters to the Serial Gateway. I can replicate it by comparing copy/paste vs typing in Minicom, my custom Go program, and a modified version of MyController. 

Below is output from the modified MyController; nothing has changed in my setup but adding a 5ms delay between writing bytes to the serial port (src/main/java/org/mycontroller/standalone/gateway/serialport/SerialPortPi4jImpl.java)

    Nov 9, 2015 11:28:12 PM	Sensor	Received	[NodeId:2, SensorId:0, Type:V_TEMP, PayLoad:77.2]
    Nov 9, 2015 11:28:10 PM	Sensor Internal	Sent	[I_CONFIG], [NodeId:2, SensorId:255, PayLoad: M]
    Nov 9, 2015 11:28:09 PM	Sensor Internal	Received	[I_CONFIG], [NodeId:2, SensorId:255, PayLoad: 0]
    Nov 9, 2015 11:28:07 PM	Sensor Internal	Sent	[I_ID_RESPONSE], [NodeId:255, SensorId:255, PayLoad: 2]
    Nov 9, 2015 11:28:06 PM	Sensor Internal	Received	[I_ID_REQUEST], [NodeId:255, SensorId:255, PayLoad: null]

**Comment by jkandasa** [comment]
@mannkind I'm also guessing the same, till now my test running perfectly with native RPI serial port.

**Comment by jkandasa** [comment]
@mannkind Is the issue reported by has resolved? I do not face any issue till date, hence I'm planing to close this issue.

**Comment by mannkind** [comment]
I wasn't the one that reported this issue, just thought my issue with MyController may have been related :) 

For anyone that may find this issue in the future -- my issue was resolved by reducing the MySensors baud rate to 38400 for my 3.3v 8mhz arduino pro mini, and then adjusting MyController's settings accordingly.

**Comment by jkandasa** [comment]
@mannkind Thank you! I'm closing this issue now.
