### ISSUE TITLE
broke all the latest updates

### ISSUE THREAD

**Issue by arturmon** [mycontroller-org/mycontroller#81]
broke all the latest updates!!!
![4554](https://cloud.githubusercontent.com/assets/7686999/11048888/77632eb0-874b-11e5-9991-4ae43ffe4331.jpg)

**Comment by Dietmar-Franken** [comment]
I have the same issue from the latest master branch

**Comment by jkandasa** [comment]
@arturmon @Dietmar-Franken let me find the issue and fix it.

**Comment by jkandasa** [comment]
There was an syntax error on language json files. Fix it now.

**Comment by Dietmar-Franken** [comment]
:+1:

**Comment by Dietmar-Franken** [comment]
That´s strange all language files the same error never seen that before
