### ISSUE TITLE
dashboard

### ISSUE THREAD

**Issue by arturmon** [mycontroller-org/mycontroller#82]
Offer to do something similar.
http://themes.getbootstrap.com/products/dashboard
http://shopify.github.io/dashing/
http://fdietz.github.io/team_dashboard/
http://grafana.org/#about
https://github.com/afaqurk/linux-dash
https://github.com/Reportr/dashboard
https://github.com/hopkinschris/dashboard
https://github.com/ModelN/sDashboard
https://github.com/dashku/dashku
https://github.com/obfuscurity/tasseo

**Comment by jkandasa** [comment]
@arturmon looks awesome. Thank you. Let me try with different dashboard

**Comment by arturmon** [comment]
really looking forward to the release))

**Comment by arturmon** [comment]
continued
https://www.pinterest.com/pin/28780885092818483/
https://www.pinterest.com/pin/305541155940762353/
https://econsultancy.com/blog/62844-24-beautifully-designed-web-dashboards-that-data-geeks-will-love/
https://www.freshdesignweb.com/responsive-admin-templates/

**Comment by jkandasa** [comment]
@arturmon after some analysis this dashboard looks good and we can adopt easily with existing GUI framework.

Have to do some sample test with this https://github.com/angular-dashboard-framework/angular-dashboard-framework

**Comment by jkandasa** [comment]
available with  0.0.3-alpha1
