### ISSUE TITLE
Feature Request : Create Roles

### ISSUE THREAD

**Issue by Dietmar-Franken** [mycontroller-org/mycontroller#83]
Feature Request : Create Roles with rights for different nodes

**Comment by arturmon** [comment]
Editor role (ACL) must be correct?

**Comment by Dietmar-Franken** [comment]
@arturmon 
I don´t understandwhat you mean

**Comment by arturmon** [comment]
I'm sorry, I can not understand. I thought the editor roles for the users.

**Comment by jkandasa** [comment]
user roles supported from 0.0.3-alpha1
