### ISSUE TITLE
Feature Request : Variable types under Alarm Threshold field

### ISSUE THREAD

**Issue by S0rc3r3r** [mycontroller-org/mycontroller#84]
When creating an Alarm for eg. Temp Sensor it would be nice to have the possibility to use Sensor variable types under the Threshold field, not just fixed values.

Main reason for this feature request is that I want to be able to use the Temp sensor as a Thermostat and to be able to control my S_HEATER flow state on/off based on the temp sensor s_temp and V_HVAC_SETPOINT_HEAT variables.

**Comment by jkandasa** [comment]
@S0rc3r3r added dynamic support, not only limited with same sensor. Supports other sensor's value also.

![alarm_dynamic](https://cloud.githubusercontent.com/assets/1004403/11437620/2654687c-9515-11e5-8de4-5cee053385d6.png)

![alarm_dynamic_2](https://cloud.githubusercontent.com/assets/1004403/11437638/444bb15a-9515-11e5-9b89-fb945fd56532.png)
