### ISSUE TITLE
not compiled

### ISSUE THREAD

**Issue by arturmon** [mycontroller-org/mycontroller#85]
![image](https://cloud.githubusercontent.com/assets/7686999/11216102/88a1a502-8d5a-11e5-9978-b44259c4d10f.png)

**Comment by jkandasa** [comment]
@arturmon Latest image will not compile until you have local snapshot of `moquette`

I have asked `moquette` team to give a nightly build --> https://github.com/andsel/moquette/issues/127

If they will not give I will upload somewhere to get snapshot build until we will get 0.8 release.

For now the workaround is,

clone https://github.com/andsel/moquette repository locally and build it.
```
clone https://github.com/andsel/moquette
cd moquette
mvn package install
```

Now continue with MyController

**Comment by arturmon** [comment]
ok
